version: "3.9"
services:
  simulation:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
        gitcommithash: HEAD
    image: bodies-in-potential-flow:latest
    volumes: 
      - "./docker/completed:/bodies-in-potential-flow/data"
      - "./docker/in_progress:/bodies-in-potential-flow/temp"
volumes:
  completed:
    external: false
  in_progress:
    external: false
