version: "3.8"

services:
  simulation:
    image: bodies-in-potential-flow:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        buildno: 1
        gitcommithash: HEAD
    deploy:
      resources:
        limits:
          cpus: '${MAX_CPUS}'
          memory: 2048M
        reservations:
          cpus: '1.00'
          memory: 50M
    volumes:
      - type: bind
        source: "./docker/completed"
        target: "/bodies-in-potential-flow/data"
      - type: bind
        source: "./docker/in_progress"
        target: "/bodies-in-potential-flow/temp"

volumes:
  docker_completed:
    external: false
  docker_in_progress:
    external: false
