bodies-in-potential-flow: plotStyling.PlotStyling Class Reference
plotStyling.PlotStyling Class Reference
Public Member Functions
def __init__ (self, numLines, x_label, y_label, title=None, loglog=False, outputDir=None, figName=None, eps=False, continuousColors=False)
def make_plot (self, showPlot=False)
def curve (self, x_data, y_data, thin_curve=False, dashed_curve=False, zorder=None, label=None, color=None)
def scatter (self, x_data, y_data, marker=None, zorder=None, label=None, color=None)
def scatter_dashed (self, x_data, y_data, marker=None, zorder=None, label=None, color=None)
def legend (self, title=None, loc='best', bbox_to_anchor=None, ncol=1)
def textbox (self, text, x_loc, y_loc, horz_align="center", vert_align="center")
def set_yaxis_scientific (self)
def set_xaxis_scientific (self)
def set_xaxis_tick_scalar_formatter (self)
def set_yaxis_tick_scalar_formatter (self)
def set_major_minor_ticks (self, xMajorLoc=None, xMinorLoc=None, yMajorLoc=None, yMinorLoc=None)
def set_latex_axis_labels (self, axis='x', axisScale=np.pi, denominator=2, minorTicks=4, latex=r'\pi')
def save_plot (self, showPlot=False)
def fix_unicode_chars (self)
def suppress_stdout (self)
Public Attributes
x_label
y_label
title
numLines
loglog
fig
ax
figName
outputDir
eps
continuous_colors
color_ID
color_ID_increment
color_map
Static Public Attributes
int title_size = 40
int axis_label_size = 40
int tick_size = 30
int legend_size = 22
int legend_title_size = 26
int label_pad = 10
int line_width = 3
int thin_line_width = 2
int marker_size = 28
list dashes = [5, 2, 1, 2]
col_diverge = cc.bky
col_sunset = cc.CET_L8
col_beetle = mpl.cm.get_cmap('viridis').colors
darkBlue = cc.glasbey_dark[10]
string black = 'k'
red = cc.glasbey_dark[0]
darkgreen = cc.glasbey_dark[2]
magenta = cc.glasbey_dark[13]
orange = cc.glasbey_dark[41]
lightBlue = cc.glasbey_dark[16]
lightGreen = cc.glasbey_dark[44]
purple = cc.glasbey_dark[42]
brown = cc.glasbey_dark[15]
list col_categorical
Detailed Description
Definition at line 59 of file plotStyling.py.
Constructor & Destructor Documentation
__init__()
def plotStyling.PlotStyling.__init__ (self, numLines, x_label, y_label, title = None, loglog = False, outputDir = None, figName = None, eps = False, continuousColors = False)
Definition at line 127 of file plotStyling.py.
                 continuousColors=False):
        # Plot text elements
        self.x_label = x_label
        self.y_label = y_label
        self.title = title
        # Overall figure formatting
        self.numLines = None  # how many data-series will be plotted on current figure
        self.loglog = loglog  # Whether to output log-log scaled axes
        # Handles for the plot (from matplotlib)
        self.fig = None
        self.ax = None
        # Plot I/O
        self.figName = figName      # filename of plot
        self.outputDir = outputDir  # directory to save plot
        self.eps = eps              # whether to output in .eps or .png format
        # Set color scheme
        # REVIEW: There are 3 options for "continuous" colorshemes
        #           * Diverging colors: 'cc.bky'                             (blue-black-brown)
        #           * Linear colors 1:  'cc.CET_L8'                          (blue-purple-pink-orange-yellow)
        #           * Linear colors 2:  'mpl.cm.get_cmap('viridis').colors'  (purple-teal-green-yellow)
        # Colorscheme
        self.continuous_colors = continuousColors
        self.color_ID = 0
        self.color_ID_increment = 1
        self.color_map = None
        if self.continuous_colors:
            # Input checking
            if (numLines > 255):
                raise ValueError(
                    "numLines input must be < 255 for continuous colorscheme output")
            # Choose a map
            self.color_map = self.col_sunset
            self.color_ID_increment = int(255 / numLines)
        else:
            # Input checking
            if (numLines > len(self.col_categorical)):
                raise ValueError(
                    f"numLines input must be < {len(self.col_categorical)} for continuous colorscheme output")
            # Choose a map
            self.color_map = self.col_categorical
# !SECTION
# SECTION: Make the plot figure
References plotStyling.PlotStyling.__init__().
Referenced by plotStyling.PlotStyling.__init__().
Member Function Documentation
make_plot()
def plotStyling.PlotStyling.make_plot (self, showPlot = False)
Definition at line 189 of file plotStyling.py.
    def make_plot(self, showPlot=False):
        if showPlot:
            plt.switch_backend('module://ipykernel.pylab.backend_inline')
            # Lower-resolution figure
            figsize = (10, 7)
            dpi = 400
        else:
            # Does not actually open any GUI so that it can be run on servers
            plt.switch_backend('Agg')
            # High-resolution figure
            figsize = (10, 7)
            dpi = 600
        # Construct plot
        self.fig, self.ax = plt.subplots(figsize=figsize, dpi=dpi)
        # Set axis labels
        self.ax.set_xlabel(
            self.x_label, fontsize=self.axis_label_size, labelpad=self.label_pad)
        self.ax.set_ylabel(
            self.y_label, fontsize=self.axis_label_size, labelpad=self.label_pad)
        # Set title
        if self.title is not None:
            self.ax.set_title(
                self.title, fontsize=self.title_size, fontweight='bold')
        # Update axis ticks
        self.ax.xaxis.set_tick_params(labelsize=self.tick_size, which="major",
                                      direction='in', width=2, length=7)
        self.ax.xaxis.set_tick_params(labelsize=self.tick_size, which="minor",
                                      direction='in', width=1.5, length=7)
        self.ax.yaxis.set_tick_params(labelsize=self.tick_size, which="major",
                                      direction='in', width=2, length=7)
        self.ax.yaxis.set_tick_params(labelsize=self.tick_size, which="minor",
                                      direction='in', width=1.5, length=7)
        self.ax.ticklabel_format(useMathText=True)
        self.ax.yaxis.set_ticks_position('both')
        self.ax.xaxis.set_ticks_position('both')
        # Add minor ticks at all integers for log-log plots
        if self.loglog:
            pass
        # Make border larger
        self.ax.spines["top"].set_linewidth(2)
        self.ax.spines["bottom"].set_linewidth(2)
        self.ax.spines["left"].set_linewidth(2)
        self.ax.spines["right"].set_linewidth(2)
# !SECTION
# SECTION: Continuous curves
References plotStyling.PlotStyling.ax, plotStyling.PlotStyling.axis_label_size, plotStyling.PlotStyling.fig, plotStyling.PlotStyling.label_pad, plotStyling.PlotStyling.loglog, plotStyling.PlotStyling.make_plot(), plotStyling.PlotStyling.tick_size, plotStyling.PlotStyling.title, plotStyling.PlotStyling.title_size, plotStyling.PlotStyling.x_label, and plotStyling.PlotStyling.y_label.
Referenced by plotStyling.PlotStyling.make_plot().
curve()
def plotStyling.PlotStyling.curve (self, x_data, y_data, thin_curve = False, dashed_curve = False, zorder = None, label = None, color = None)
Definition at line 247 of file plotStyling.py.
              zorder=None, label=None, color=None):
        # Set color
        local_color = color
        if local_color is None:
            local_color = self.color_map[self.color_ID]
            self.color_ID += self.color_ID_increment        # Increment color ID
        # Set line style
        local_curve = '-'  # solid line style
        if dashed_curve:
            local_curve = '--'  # dashed line style
        # Set linewidth
        local_linewidth = self.line_width
        if thin_curve:
            local_linewidth = self.thin_line_width
        # Plot input data
        if self.loglog:
            self.ax.loglog(x_data, y_data, local_curve,
                           color=local_color, label=label,
                           linewidth=local_linewidth, zorder=zorder)
        else:
            self.ax.plot(x_data, y_data, local_curve,
                         color=local_color, label=label,
                         linewidth=local_linewidth, zorder=zorder)
        self.fix_unicode_chars()  # Fix any character rendering errors
# !SECTION
# SECTION: Discrete data points
References plotStyling.PlotStyling.ax, plotStyling.PlotStyling.color_ID, plotStyling.PlotStyling.color_ID_increment, plotStyling.PlotStyling.color_map, plotStyling.PlotStyling.curve(), plotStyling.PlotStyling.fix_unicode_chars(), plotStyling.PlotStyling.line_width, plotStyling.PlotStyling.loglog, and plotStyling.PlotStyling.thin_line_width.
Referenced by plotStyling.PlotStyling.curve().
scatter()
def plotStyling.PlotStyling.scatter (self, x_data, y_data, marker = None, zorder = None, label = None, color = None)
Definition at line 284 of file plotStyling.py.
                marker=None, zorder=None, label=None, color=None):
        # Set color
        local_color = color
        if local_color is None:
            local_color = self.color_map[self.color_ID]
            self.color_ID += self.color_ID_increment        # Increment color ID
        # Set marker
        local_marker = marker
        if local_marker is None:
            local_marker = 'o'
        # Plot input data
        if self.loglog:
            scatter = self.ax.loglog(x_data, y_data, local_marker,
                                     color=local_color, label=label,
                                     linewidth=self.line_width, zorder=zorder)
        else:
            scatter = self.ax.plot(x_data, y_data, local_marker,
                                   color=local_color, label=label,
                                   linewidth=self.line_width, zorder=zorder)
        self.fix_unicode_chars()  # Fix any character rendering errors
        return scatter
References plotStyling.PlotStyling.ax, plotStyling.PlotStyling.color_ID, plotStyling.PlotStyling.color_ID_increment, plotStyling.PlotStyling.color_map, plotStyling.PlotStyling.fix_unicode_chars(), plotStyling.PlotStyling.line_width, plotStyling.PlotStyling.loglog, and plotStyling.PlotStyling.scatter().
Referenced by plotStyling.PlotStyling.scatter().
scatter_dashed()
def plotStyling.PlotStyling.scatter_dashed (self, x_data, y_data, marker = None, zorder = None, label = None, color = None)
Definition at line 312 of file plotStyling.py.
    def scatter_dashed(self, x_data, y_data, marker=None, zorder=None, label=None, color=None):
        # Set color
        local_color = color
        if local_color is None:
            local_color = self.color_map[self.color_ID]
            self.color_ID += self.color_ID_increment        # Increment color ID
        # Set marker
        local_marker = marker
        if local_marker is None:
            local_marker = 'o'
        # Plot input data
        if self.loglog:
            scatter, = self.ax.loglog(x_data, y_data, local_marker,
                                      color=local_color, label=label,
                                      linewidth=self.line_width, zorder=zorder)
        else:
            scatter, = self.ax.plot(x_data, y_data, local_marker,
                                    color=local_color, label=label,
                                    linewidth=self.line_width, zorder=zorder)
        scatter.set_dashes(self.dashes)  # Add connecting dashes
        self.fix_unicode_chars()  # Fix any character rendering errors
        return scatter
# !SECTION
# SECTION: Legend
References plotStyling.PlotStyling.ax, plotStyling.PlotStyling.color_ID, plotStyling.PlotStyling.color_ID_increment, plotStyling.PlotStyling.color_map, plotStyling.PlotStyling.dashes, plotStyling.PlotStyling.fix_unicode_chars(), plotStyling.PlotStyling.line_width, plotStyling.PlotStyling.loglog, and plotStyling.PlotStyling.scatter_dashed().
Referenced by plotStyling.PlotStyling.scatter_dashed().
legend()
def plotStyling.PlotStyling.legend (self, title = None, loc = 'best', bbox_to_anchor = None, ncol = 1)
Definition at line 346 of file plotStyling.py.
    def legend(self, title=None, loc='best', bbox_to_anchor=None, ncol=1):
        legend = self.ax.legend(title=title, loc=loc, bbox_to_anchor=bbox_to_anchor,
                                fontsize=self.legend_size,
                                frameon=False, fancybox=True,
                                framealpha=0.90, shadow=False,
                                edgecolor='k',
                                ncol=ncol)
        legend.get_title().set_fontsize(self.legend_title_size)
# !SECTION
# SECTION: Text elements
References plotStyling.PlotStyling.ax, plotStyling.PlotStyling.legend(), plotStyling.PlotStyling.legend_size, and plotStyling.PlotStyling.legend_title_size.
Referenced by plotStyling.PlotStyling.legend().
textbox()
def plotStyling.PlotStyling.textbox (self, text, x_loc, y_loc, horz_align = "center", vert_align = "center")
Definition at line 363 of file plotStyling.py.
                horz_align="center", vert_align="center"):
        plt.text(x_loc, y_loc, text,
                 fontsize=self.legend_title_size,
                 ha=horz_align, va=vert_align)
# SECTION
# SECTION: Axes
References plotStyling.PlotStyling.legend_title_size, and plotStyling.PlotStyling.textbox().
Referenced by plotStyling.PlotStyling.textbox().
set_yaxis_scientific()
def plotStyling.PlotStyling.set_yaxis_scientific (self)
Definition at line 375 of file plotStyling.py.
    def set_yaxis_scientific(self):
        plt.ticklabel_format(style='sci', axis='y',
                             scilimits=(0, 2), useOffset=True)
        t = self.ax.yaxis.get_offset_text()
        t.set_size(self.tick_size)
References plotStyling.PlotStyling.ax, plotStyling.PlotStyling.set_yaxis_scientific(), and plotStyling.PlotStyling.tick_size.
Referenced by plotStyling.PlotStyling.set_yaxis_scientific().
set_xaxis_scientific()
def plotStyling.PlotStyling.set_xaxis_scientific (self)
Definition at line 382 of file plotStyling.py.
    def set_xaxis_scientific(self):
        plt.ticklabel_format(style='sci', axis='x',
                             scilimits=(0, 2), useOffset=True)
        t = self.ax.xaxis.get_offset_text()
        t.set_size(self.tick_size)
References plotStyling.PlotStyling.ax, plotStyling.PlotStyling.set_xaxis_scientific(), and plotStyling.PlotStyling.tick_size.
Referenced by plotStyling.PlotStyling.set_xaxis_scientific().
set_xaxis_tick_scalar_formatter()
def plotStyling.PlotStyling.set_xaxis_tick_scalar_formatter (self)
Definition at line 389 of file plotStyling.py.
    def set_xaxis_tick_scalar_formatter(self):
        self.ax.xaxis.set_minor_formatter(mtk.ScalarFormatter())
        self.ax.xaxis.set_major_formatter(mtk.ScalarFormatter())
References plotStyling.PlotStyling.ax, and plotStyling.PlotStyling.set_xaxis_tick_scalar_formatter().
Referenced by plotStyling.PlotStyling.set_xaxis_tick_scalar_formatter().
set_yaxis_tick_scalar_formatter()
def plotStyling.PlotStyling.set_yaxis_tick_scalar_formatter (self)
Definition at line 394 of file plotStyling.py.
    def set_yaxis_tick_scalar_formatter(self):
        self.ax.yaxis.set_minor_formatter(mtk.ScalarFormatter())
        self.ax.yaxis.set_major_formatter(mtk.ScalarFormatter())
References plotStyling.PlotStyling.ax, and plotStyling.PlotStyling.set_yaxis_tick_scalar_formatter().
Referenced by plotStyling.PlotStyling.set_yaxis_tick_scalar_formatter().
set_major_minor_ticks()
def plotStyling.PlotStyling.set_major_minor_ticks (self, xMajorLoc = None, xMinorLoc = None, yMajorLoc = None, yMinorLoc = None)
Definition at line 399 of file plotStyling.py.
    def set_major_minor_ticks(self, xMajorLoc=None, xMinorLoc=None, yMajorLoc=None, yMinorLoc=None):
        if xMajorLoc is not None:
            self.ax.xaxis.set_major_locator(
                mpl.ticker.MultipleLocator(xMajorLoc))
        if xMinorLoc is not None:
            self.ax.xaxis.set_minor_locator(
                mpl.ticker.MultipleLocator(xMinorLoc))
        if yMajorLoc is not None:
            self.ax.yaxis.set_major_locator(
                mpl.ticker.MultipleLocator(yMajorLoc))
        if yMinorLoc is not None:
            self.ax.yaxis.set_minor_locator(
                mpl.ticker.MultipleLocator(yMinorLoc))
References plotStyling.PlotStyling.ax, and plotStyling.PlotStyling.set_major_minor_ticks().
Referenced by plotStyling.PlotStyling.set_major_minor_ticks().
set_latex_axis_labels()
def plotStyling.PlotStyling.set_latex_axis_labels (self, axis = 'x', axisScale = np.pi, denominator = 2, minorTicks = 4, latex = r'\pi')
Definition at line 417 of file plotStyling.py.
    def set_latex_axis_labels(self, axis='x', axisScale=np.pi, denominator=2, minorTicks=4, latex=r'\pi'):
        major = Multiple(denominator, axisScale, latex)
        minor = Multiple(denominator*minorTicks, axisScale, latex)
        # Output results to figure
        if (axis == 'x'):
            self.ax.xaxis.set_major_locator(major.locator())
            self.ax.xaxis.set_minor_locator(minor.locator())
            self.ax.xaxis.set_major_formatter(major.formatter())
        elif (axis == 'y'):
            self.ax.yaxis.set_major_locator(major.locator())
            self.ax.yaxis.set_minor_locator(minor.locator())
            self.ax.yaxis.set_major_formatter(major.formatter())
# !SECTION
# SECTION: Save figure
References plotStyling.PlotStyling.ax, and plotStyling.PlotStyling.set_latex_axis_labels().
Referenced by plotStyling.PlotStyling.set_latex_axis_labels().
save_plot()
def plotStyling.PlotStyling.save_plot (self, showPlot = False)
Definition at line 438 of file plotStyling.py.
    def save_plot(self, showPlot=False):
        self.fix_unicode_chars()
        if (self.figName is not None) and (self.eps == True):
            with self.suppress_stdout():
                plt.savefig(self.outputDir + self.figName + '.eps',
                            format='eps', bbox_inches='tight')
        elif (self.figName is not None) and (self.eps == False):
            plt.savefig(self.outputDir + self.figName + '.png',
                        format='png', bbox_inches='tight')
        if showPlot:
            plt.show()
# !SECTION
# SECTION: Remove unicode issues
References plotStyling.PlotStyling.eps, plotStyling.PlotStyling.figName, plotStyling.PlotStyling.fix_unicode_chars(), plotStyling.PlotStyling.outputDir, systemData.outputDir(), plotStyling.PlotStyling.save_plot(), and plotStyling.PlotStyling.suppress_stdout().
Referenced by plotStyling.PlotStyling.save_plot().
fix_unicode_chars()
def plotStyling.PlotStyling.fix_unicode_chars (self)
Definition at line 462 of file plotStyling.py.
    def fix_unicode_chars(self):
        # Force the figure to be drawn
        logger = logging.getLogger('matplotlib.mathtext')
        original_level = logger.getEffectiveLevel()
        logger.setLevel(logging.ERROR)
        with warnings.catch_warnings():
            warnings.simplefilter(
                'ignore', category=mpl.mathtext.MathTextWarning)
            self.fig.canvas.draw()
        logger.setLevel(original_level)
        # Remove '\mathdefault' from all minor tick labels
        # 'with' block added by @Alec in December 2020 to avoid UserWarning related to relabling axis
        with warnings.catch_warnings():
            warnings.filterwarnings("ignore")
            labels = [label.get_text().replace(r'\mathdefault', '')
                      for label in self.ax.get_xminorticklabels()]
            self.ax.set_xticklabels(labels, minor=True)
            labels = [label.get_text().replace(r'\mathdefault', '')
                      for label in self.ax.get_yminorticklabels()]
            self.ax.set_yticklabels(labels, minor=True)
        # Added by @Alec
        self.ax.xaxis.set_tick_params(
            which='both', labelsize=self.tick_size, pad=self.label_pad)
        self.ax.yaxis.set_tick_params(
            which='both', labelsize=self.tick_size, pad=self.label_pad)
References plotStyling.PlotStyling.ax, plotStyling.PlotStyling.fig, plotStyling.PlotStyling.fix_unicode_chars(), plotStyling.PlotStyling.label_pad, and plotStyling.PlotStyling.tick_size.
Referenced by plotStyling.PlotStyling.curve(), plotStyling.PlotStyling.fix_unicode_chars(), plotStyling.PlotStyling.save_plot(), plotStyling.PlotStyling.scatter(), and plotStyling.PlotStyling.scatter_dashed().
suppress_stdout()
def plotStyling.PlotStyling.suppress_stdout (self)
Definition at line 500 of file plotStyling.py.
    def suppress_stdout(self):
        with open(os.devnull, "w") as devnull:
            old_stdout = sys.stdout
            sys.stdout = devnull
            old_stderr = sys.stderr
            sys.stderr = devnull
            try:
                yield
            finally:
                sys.stdout = old_stdout
                sys.stderr = old_stderr
# !SECTION
# SECTION: Get \pi in axis labels of plots
# @Source: https://stackoverflow.com/questions/40642061/how-to-set-axis-ticks-in-multiples-of-pi-python-matplotlib
# @User: Scott Centoni
References plotStyling.PlotStyling.suppress_stdout().
Referenced by plotStyling.PlotStyling.save_plot(), and plotStyling.PlotStyling.suppress_stdout().
Member Data Documentation
title_size
int plotStyling.PlotStyling.title_size = 40 static
Definition at line 87 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.make_plot().
axis_label_size
int plotStyling.PlotStyling.axis_label_size = 40 static
Definition at line 88 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.make_plot().
tick_size
int plotStyling.PlotStyling.tick_size = 30 static
Definition at line 89 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.fix_unicode_chars(), plotStyling.PlotStyling.make_plot(), plotStyling.PlotStyling.set_xaxis_scientific(), and plotStyling.PlotStyling.set_yaxis_scientific().
legend_size
int plotStyling.PlotStyling.legend_size = 22 static
Definition at line 90 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.legend().
legend_title_size
int plotStyling.PlotStyling.legend_title_size = 26 static
Definition at line 91 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.legend(), and plotStyling.PlotStyling.textbox().
label_pad
int plotStyling.PlotStyling.label_pad = 10 static
Definition at line 94 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.fix_unicode_chars(), and plotStyling.PlotStyling.make_plot().
line_width
int plotStyling.PlotStyling.line_width = 3 static
Definition at line 97 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.curve(), plotStyling.PlotStyling.scatter(), and plotStyling.PlotStyling.scatter_dashed().
thin_line_width
int plotStyling.PlotStyling.thin_line_width = 2 static
Definition at line 98 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.curve().
marker_size
int plotStyling.PlotStyling.marker_size = 28 static
Definition at line 99 of file plotStyling.py.
dashes
list plotStyling.PlotStyling.dashes = [5, 2, 1, 2] static
Definition at line 100 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.scatter_dashed().
col_diverge
plotStyling.PlotStyling.col_diverge = cc.bky static
Definition at line 103 of file plotStyling.py.
col_sunset
plotStyling.PlotStyling.col_sunset = cc.CET_L8 static
Definition at line 104 of file plotStyling.py.
col_beetle
plotStyling.PlotStyling.col_beetle = mpl.cm.get_cmap('viridis').colors static
Definition at line 105 of file plotStyling.py.
darkBlue
plotStyling.PlotStyling.darkBlue = cc.glasbey_dark[10] static
Definition at line 108 of file plotStyling.py.
black
string plotStyling.PlotStyling.black = 'k' static
Definition at line 109 of file plotStyling.py.
red
plotStyling.PlotStyling.red = cc.glasbey_dark[0] static
Definition at line 110 of file plotStyling.py.
darkgreen
plotStyling.PlotStyling.darkgreen = cc.glasbey_dark[2] static
Definition at line 111 of file plotStyling.py.
magenta
plotStyling.PlotStyling.magenta = cc.glasbey_dark[13] static
Definition at line 112 of file plotStyling.py.
orange
plotStyling.PlotStyling.orange = cc.glasbey_dark[41] static
Definition at line 113 of file plotStyling.py.
lightBlue
plotStyling.PlotStyling.lightBlue = cc.glasbey_dark[16] static
Definition at line 114 of file plotStyling.py.
lightGreen
plotStyling.PlotStyling.lightGreen = cc.glasbey_dark[44] static
Definition at line 115 of file plotStyling.py.
purple
plotStyling.PlotStyling.purple = cc.glasbey_dark[42] static
Definition at line 116 of file plotStyling.py.
brown
plotStyling.PlotStyling.brown = cc.glasbey_dark[15] static
Definition at line 117 of file plotStyling.py.
col_categorical
list plotStyling.PlotStyling.col_categorical static
Initial value:
=  [darkBlue, red, darkgreen, magenta, black,
                       orange, lightBlue, lightGreen, purple, brown]
Definition at line 118 of file plotStyling.py.
x_label
plotStyling.PlotStyling.x_label
Definition at line 134 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.make_plot().
y_label
plotStyling.PlotStyling.y_label
Definition at line 135 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.make_plot().
title
plotStyling.PlotStyling.title
Definition at line 136 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.make_plot().
numLines
plotStyling.PlotStyling.numLines
Definition at line 139 of file plotStyling.py.
loglog
plotStyling.PlotStyling.loglog
Definition at line 140 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.curve(), plotStyling.PlotStyling.make_plot(), plotStyling.PlotStyling.scatter(), and plotStyling.PlotStyling.scatter_dashed().
fig
plotStyling.PlotStyling.fig
Definition at line 143 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.fix_unicode_chars(), and plotStyling.PlotStyling.make_plot().
ax
plotStyling.PlotStyling.ax
Definition at line 144 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.curve(), plotStyling.PlotStyling.fix_unicode_chars(), plotStyling.PlotStyling.legend(), plotStyling.PlotStyling.make_plot(), plotStyling.PlotStyling.scatter(), plotStyling.PlotStyling.scatter_dashed(), plotStyling.PlotStyling.set_latex_axis_labels(), plotStyling.PlotStyling.set_major_minor_ticks(), plotStyling.PlotStyling.set_xaxis_scientific(), plotStyling.PlotStyling.set_xaxis_tick_scalar_formatter(), plotStyling.PlotStyling.set_yaxis_scientific(), and plotStyling.PlotStyling.set_yaxis_tick_scalar_formatter().
figName
plotStyling.PlotStyling.figName
Definition at line 147 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.save_plot().
outputDir
plotStyling.PlotStyling.outputDir
Definition at line 148 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.save_plot().
eps
plotStyling.PlotStyling.eps
Definition at line 149 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.save_plot().
continuous_colors
plotStyling.PlotStyling.continuous_colors
Definition at line 158 of file plotStyling.py.
color_ID
plotStyling.PlotStyling.color_ID
Definition at line 159 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.curve(), plotStyling.PlotStyling.scatter(), and plotStyling.PlotStyling.scatter_dashed().
color_ID_increment
plotStyling.PlotStyling.color_ID_increment
Definition at line 160 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.curve(), plotStyling.PlotStyling.scatter(), and plotStyling.PlotStyling.scatter_dashed().
color_map
plotStyling.PlotStyling.color_map
Definition at line 161 of file plotStyling.py.
Referenced by plotStyling.PlotStyling.curve(), plotStyling.PlotStyling.scatter(), and plotStyling.PlotStyling.scatter_dashed().
The documentation for this class was generated from the following file:
python/plotStyling.py