bodies-in-potential-flow: ProgressBar Class Reference
ProgressBar Class Reference
#include <progressBar.hpp>
Public Member Functions
ProgressBar (unsigned int total, unsigned int width, char complete, char incomplete)
ProgressBar (unsigned int total, unsigned int width)
unsigned int operator++ ()
void display () const
void done () const
Private Attributes
unsigned int ticks = 0
const unsigned int total_ticks
const unsigned int bar_width
const char complete_char = '='
const char incomplete_char = ' '
const std::chrono::steady_clock::time_point start_time = std::chrono::steady_clock::now()
Detailed Description
Definition at line 15 of file progressBar.hpp.
Constructor & Destructor Documentation
ProgressBar() [1/2]
ProgressBar::ProgressBar (unsigned int total, unsigned int width, char complete, char incomplete) inline
Definition at line 27 of file progressBar.hpp.
         : total_ticks{total}, bar_width{width}, complete_char{complete}, incomplete_char{incomplete}
     {
     }
ProgressBar() [2/2]
ProgressBar::ProgressBar (unsigned int total, unsigned int width) inline
Definition at line 32 of file progressBar.hpp.
                                                         : total_ticks{total}, bar_width{width}
     {
     }
Member Function Documentation
operator++()
unsigned int ProgressBar::operator++ () inline
Definition at line 37 of file progressBar.hpp.
     {
         return ++ticks;
     }
References ticks.
display()
void ProgressBar::display () const inline
Definition at line 43 of file progressBar.hpp.
     {
         float        progress = (float)ticks / total_ticks;
         unsigned int pos      = (int)(bar_width * progress);
         std::chrono::steady_clock::time_point now = std::chrono::steady_clock::now();
         auto                                  time_elapsed =
             std::chrono::duration_cast<std::chrono::seconds>(now - start_time).count();
         std::cout << "[";
         for (unsigned int i = 0; i < bar_width; ++i)
         {
             if (i < pos)
                 std::cout << complete_char;
             else if (i == pos)
                 std::cout << ">";
             else
                 std::cout << incomplete_char;
         }
         double hourElapsed = std::floor(double(time_elapsed) / 3600.0);
         double minElapsed  = static_cast<int>(double(time_elapsed) / 60.0) % 60;
         double secElapsed  = static_cast<int>(double(time_elapsed)) % 60;
         double iterationPerSecond = double(ticks) / double(time_elapsed);
         double hourLeft = std::floor(double(total_ticks - ticks) / (iterationPerSecond * 3600));
         double minLeft =
             static_cast<int>(double(total_ticks - ticks) / (iterationPerSecond * 60.0)) % 60;
         double secLeft = static_cast<int>(double(total_ticks - ticks) / iterationPerSecond) % 60;
         std::cout << "] " << int(progress * 100.0) << "% [" << std::setprecision(0) << std::fixed
                   << hourElapsed << ":" << std::setprecision(0) << std::fixed << minElapsed << ":"
                   << std::setprecision(0) << std::fixed << secElapsed << " <- "
                   << std::setprecision(0) << std::fixed << hourLeft << ":" << std::setprecision(0)
                   << std::fixed << minLeft << ":" << std::setprecision(0) << std::fixed << secLeft
                   << ", " << std::setprecision(0) << std::fixed << iterationPerSecond << "it/s"
                   << "]\r";
         std::cout.flush();
     }
References bar_width, complete_char, incomplete_char, start_time, ticks, and total_ticks.
Referenced by done().
done()
void ProgressBar::done () const inline
Definition at line 85 of file progressBar.hpp.
     {
         display();
         std::cout << std::endl;
     }
References display().
Member Data Documentation
ticks
unsigned int ProgressBar::ticks = 0 private
Definition at line 18 of file progressBar.hpp.
Referenced by display(), and operator++().
total_ticks
const unsigned int ProgressBar::total_ticks private
Definition at line 20 of file progressBar.hpp.
Referenced by display().
bar_width
const unsigned int ProgressBar::bar_width private
Definition at line 21 of file progressBar.hpp.
Referenced by display().
complete_char
const char ProgressBar::complete_char = '=' private
Definition at line 22 of file progressBar.hpp.
Referenced by display().
incomplete_char
const char ProgressBar::incomplete_char = ' ' private
Definition at line 23 of file progressBar.hpp.
Referenced by display().
start_time
const std::chrono::steady_clock::time_point ProgressBar::start_time = std::chrono::steady_clock::now() private
Definition at line 24 of file progressBar.hpp.
Referenced by display().
The documentation for this class was generated from the following file:
src/simulation_system/progressBar.hpp