bodies-in-potential-flow: src/cuda_helpers/helper_string.h File Reference
helper_string.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <fstream>
#include <string>
#include <string.h>
#include <strings.h>
Macros
#define STRCASECMP strcasecmp
#define STRNCASECMP strncasecmp
#define STRCPY(sFilePath, nLength, sPath) strcpy(sFilePath, sPath)
#define FOPEN(fHandle, filename, mode) (fHandle = fopen(filename, mode))
#define FOPEN_FAIL(result) (result == NULL)
#define SSCANF sscanf
#define SPRINTF sprintf
#define EXIT_WAIVED 2
Functions
int stringRemoveDelimiter (char delimiter, const char *string)
int getFileExtension (char *filename, char **extension)
bool checkCmdLineFlag (const int argc, const char **argv, const char *string_ref)
template<class T >
bool getCmdLineArgumentValue (const int argc, const char **argv, const char *string_ref, T *value)
int getCmdLineArgumentInt (const int argc, const char **argv, const char *string_ref)
float getCmdLineArgumentFloat (const int argc, const char **argv, const char *string_ref)
bool getCmdLineArgumentString (const int argc, const char **argv, const char *string_ref, char **string_retval)
char * sdkFindFilePath (const char *filename, const char *executable_path)
Macro Definition Documentation
STRCASECMP
#define STRCASECMP strcasecmp
Definition at line 68 of file helper_string.h.
STRNCASECMP
#define STRNCASECMP strncasecmp
Definition at line 71 of file helper_string.h.
STRCPY
#define STRCPY (sFilePath, nLength, sPath) strcpy(sFilePath, sPath)
Definition at line 74 of file helper_string.h.
FOPEN
#define FOPEN (fHandle, filename, mode) (fHandle = fopen(filename, mode))
Definition at line 78 of file helper_string.h.
FOPEN_FAIL
#define FOPEN_FAIL (result) (result == NULL)
Definition at line 81 of file helper_string.h.
SSCANF
#define SSCANF sscanf
Definition at line 84 of file helper_string.h.
SPRINTF
#define SPRINTF sprintf
Definition at line 87 of file helper_string.h.
EXIT_WAIVED
#define EXIT_WAIVED 2
Definition at line 92 of file helper_string.h.
Function Documentation
stringRemoveDelimiter()
int stringRemoveDelimiter (char delimiter, const char * string) inline
Definition at line 96 of file helper_string.h.
{
  int string_start = 0;
  while (string[string_start] == delimiter) {
    string_start++;
  }
  if (string_start >= static_cast<int>(strlen(string) - 1)) {
    return 0;
  }
  return string_start;
}
Referenced by checkCmdLineFlag(), getCmdLineArgumentFloat(), getCmdLineArgumentInt(), getCmdLineArgumentString(), and getCmdLineArgumentValue().
getFileExtension()
int getFileExtension (char * filename, char ** extension) inline
Definition at line 110 of file helper_string.h.
{
  int string_length = static_cast<int>(strlen(filename));
  while (filename[string_length--] != '.') {
    if (string_length == 0) break;
  }
  if (string_length > 0) string_length += 2;
  if (string_length == 0)
    *extension = NULL;
  else
    *extension = &filename[string_length];
  return string_length;
}
checkCmdLineFlag()
bool checkCmdLineFlag (const int argc, const char ** argv, const char * string_ref) inline
Definition at line 127 of file helper_string.h.
{
  bool bFound = false;
  if (argc >= 1) {
    for (int i = 1; i < argc; i++) {
      int string_start = stringRemoveDelimiter('-', argv[i]);
      const char *string_argv = &argv[i][string_start];
      const char *equal_pos = strchr(string_argv, '=');
      int argv_length = static_cast<int>(
          equal_pos == 0 ? strlen(string_argv) : equal_pos - string_argv);
      int length = static_cast<int>(strlen(string_ref));
      if (length == argv_length &&
          !STRNCASECMP(string_argv, string_ref, length)) {
        bFound = true;
        continue;
      }
    }
  }
  return bFound;
}
References length(), stringRemoveDelimiter(), and STRNCASECMP.
getCmdLineArgumentValue()
template<class T > bool getCmdLineArgumentValue (const int argc, const char ** argv, const char * string_ref, T * value) inline
Definition at line 155 of file helper_string.h.
{
  bool bFound = false;
  if (argc >= 1) {
    for (int i = 1; i < argc; i++) {
      int string_start = stringRemoveDelimiter('-', argv[i]);
      const char *string_argv = &argv[i][string_start];
      int length = static_cast<int>(strlen(string_ref));
      if (!STRNCASECMP(string_argv, string_ref, length)) {
        if (length + 1 <= static_cast<int>(strlen(string_argv))) {
          int auto_inc = (string_argv[length] == '=') ? 1 : 0;
          *value = (T)atoi(&string_argv[length + auto_inc]);
        }
        bFound = true;
        i = argc;
      }
    }
  }
  return bFound;
}
References length(), stringRemoveDelimiter(), and STRNCASECMP.
getCmdLineArgumentInt()
int getCmdLineArgumentInt (const int argc, const char ** argv, const char * string_ref) inline
Definition at line 180 of file helper_string.h.
{
  bool bFound = false;
  int value = -1;
  if (argc >= 1) {
    for (int i = 1; i < argc; i++) {
      int string_start = stringRemoveDelimiter('-', argv[i]);
      const char *string_argv = &argv[i][string_start];
      int length = static_cast<int>(strlen(string_ref));
      if (!STRNCASECMP(string_argv, string_ref, length)) {
        if (length + 1 <= static_cast<int>(strlen(string_argv))) {
          int auto_inc = (string_argv[length] == '=') ? 1 : 0;
          value = atoi(&string_argv[length + auto_inc]);
        } else {
          value = 0;
        }
        bFound = true;
        continue;
      }
    }
  }
  if (bFound) {
    return value;
  } else {
    return 0;
  }
}
References length(), stringRemoveDelimiter(), and STRNCASECMP.
getCmdLineArgumentFloat()
float getCmdLineArgumentFloat (const int argc, const char ** argv, const char * string_ref) inline
Definition at line 212 of file helper_string.h.
{
  bool bFound = false;
  float value = -1;
  if (argc >= 1) {
    for (int i = 1; i < argc; i++) {
      int string_start = stringRemoveDelimiter('-', argv[i]);
      const char *string_argv = &argv[i][string_start];
      int length = static_cast<int>(strlen(string_ref));
      if (!STRNCASECMP(string_argv, string_ref, length)) {
        if (length + 1 <= static_cast<int>(strlen(string_argv))) {
          int auto_inc = (string_argv[length] == '=') ? 1 : 0;
          value = static_cast<float>(atof(&string_argv[length + auto_inc]));
        } else {
          value = 0.f;
        }
        bFound = true;
        continue;
      }
    }
  }
  if (bFound) {
    return value;
  } else {
    return 0;
  }
}
References length(), stringRemoveDelimiter(), and STRNCASECMP.
getCmdLineArgumentString()
bool getCmdLineArgumentString (const int argc, const char ** argv, const char * string_ref, char ** string_retval) inline
Definition at line 244 of file helper_string.h.
{
  bool bFound = false;
  if (argc >= 1) {
    for (int i = 1; i < argc; i++) {
      int string_start = stringRemoveDelimiter('-', argv[i]);
      char *string_argv = const_cast<char *>(&argv[i][string_start]);
      int length = static_cast<int>(strlen(string_ref));
      if (!STRNCASECMP(string_argv, string_ref, length)) {
        *string_retval = &string_argv[length + 1];
        bFound = true;
        continue;
      }
    }
  }
  if (!bFound) {
    *string_retval = NULL;
  }
  return bFound;
}
References length(), stringRemoveDelimiter(), and STRNCASECMP.
sdkFindFilePath()
char * sdkFindFilePath (const char * filename, const char * executable_path) inline
Find the path for a file assuming that files are found in the searchPath.
Returns
the path if succeeded, otherwise 0
Parameters
filename name of the file
executable_path optional absolute path of the executable
Definition at line 278 of file helper_string.h.
{
  // <executable_name> defines a variable that is replaced with the name of the
  // executable
  // Typical relative search paths to locate needed companion files (e.g. sample
  // input data, or JIT source files) The origin for the relative search may be
  // the .exe file, a .bat file launching an .exe, a browser .exe launching the
  // .exe or .bat, etc
  const char *searchPath[] = {
      "./",                                          // same dir
      "./data/",                                      // same dir
      "../../../../Samples/<executable_name>/",       // up 4 in tree
      "../../../Samples/<executable_name>/",          // up 3 in tree
      "../../Samples/<executable_name>/",             // up 2 in tree
      "../../../../Samples/<executable_name>/data/",  // up 4 in tree
      "../../../Samples/<executable_name>/data/",     // up 3 in tree
      "../../Samples/<executable_name>/data/",        // up 2 in tree
      "../../../../Common/data/",                     // up 4 in tree
      "../../../Common/data/",                        // up 3 in tree
      "../../Common/data/"                            // up 2 in tree
  };
  // Extract the executable name
  std::string executable_name;
  if (executable_path != 0) {
    executable_name = std::string(executable_path);
#if defined(WIN32) || defined(_WIN32) || defined(WIN64) || defined(_WIN64)
    // Windows path delimiter
    size_t delimiter_pos = executable_name.find_last_of('\\');
    executable_name.erase(0, delimiter_pos + 1);
    if (executable_name.rfind(".exe") != std::string::npos) {
      // we strip .exe, only if the .exe is found
      executable_name.resize(executable_name.size() - 4);
    }
#else
    // Linux & OSX path delimiter
    size_t delimiter_pos = executable_name.find_last_of('/');
    executable_name.erase(0, delimiter_pos + 1);
#endif
  }
  // Loop over all search paths and return the first hit
  for (unsigned int i = 0; i < sizeof(searchPath) / sizeof(char *); ++i) {
    std::string path(searchPath[i]);
    size_t executable_name_pos = path.find("<executable_name>");
    // If there is executable_name variable in the searchPath
    // replace it with the value
    if (executable_name_pos != std::string::npos) {
      if (executable_path != 0) {
        path.replace(executable_name_pos, strlen("<executable_name>"),
                     executable_name);
      } else {
        // Skip this path entry if no executable argument is given
        continue;
      }
    }
#ifdef _DEBUG
    printf("sdkFindFilePath <%s> in %s\n", filename, path.c_str());
#endif
    // Test if the file exists
    path.append(filename);
    FILE *fp;
    FOPEN(fp, path.c_str(), "rb");
    if (fp != NULL) {
      fclose(fp);
      // File found
      // returning an allocated array here for backwards compatibility reasons
      char *file_path = reinterpret_cast<char *>(malloc(path.length() + 1));
      STRCPY(file_path, path.length() + 1, path.c_str());
      return file_path;
    }
    if (fp) {
      fclose(fp);
    }
  }
  // File not found
  return 0;
}
References FOPEN, and STRCPY.