Bodies in Potential Flow: src/helpers/eigen/helper_eigenTensorConversion.hpp File Reference
helper_eigenTensorConversion.hpp File Reference
Prototypes
template<typename T , typename Device = Eigen::DefaultDevice>
auto asEval (const Eigen::TensorBase< T, Eigen::ReadOnlyAccessors > &expr, const Device &device=Device())
Convert between Eigen::Tensor and Eigen::Matrix classes.
template<typename T , typename sizeType , typename Device = Eigen::DefaultDevice>
auto MatrixCast (const Eigen::TensorBase< T, Eigen::ReadOnlyAccessors > &expr, const sizeType rows, const sizeType cols, const Device &device=Device())
template<typename T , typename Device = Eigen::DefaultDevice>
auto VectorCast (const Eigen::TensorBase< T, Eigen::ReadOnlyAccessors > &expr, const Device &device=Device())
template<typename Scalar , auto rank, typename sizeType >
auto MatrixMap (const Eigen::Tensor< Scalar, rank > &tensor, const sizeType rows, const sizeType cols)
template<typename Scalar >
auto MatrixMap (const Eigen::Tensor< Scalar, 2 > &tensor)
template<typename Scalar , auto rank>
auto VectorMap (const Eigen::Tensor< Scalar, rank > &tensor)
template<typename Derived , typename T , auto rank>
Eigen::Tensor< typename Derived::Scalar, rank > TensorCast (const Eigen::EigenBase< Derived > &matrix, const std::array< T, rank > &dims)
Convert Eigen::Matrix --> Eigen::Tensor.
template<typename Derived , typename T , auto rank>
Eigen::Tensor< typename Derived::Scalar, rank > TensorCast (const Eigen::EigenBase< Derived > &matrix, const Eigen::DSizes< T, rank > &dims)
template<typename Derived , typename... Dims>
auto TensorCast (const Eigen::EigenBase< Derived > &matrix, const Dims... dims)
template<typename Derived >
auto TensorCast (const Eigen::EigenBase< Derived > &matrix)
template<typename Derived , auto rank>
auto TensorMap (const Eigen::PlainObjectBase< Derived > &matrix, const std::array< long, rank > &dims)
template<typename Derived , typename... Dims>
auto TensorMap (const Eigen::PlainObjectBase< Derived > &matrix, const Dims... dims)
template<typename Derived >
auto TensorMap (const Eigen::PlainObjectBase< Derived > &matrix)
#include <eigen3/Eigen/Core>
#include <eigen3/Eigen/Eigen>
#include <eigen3/unsupported/Eigen/CXX11/Tensor>
Macros
#define EIGEN_NO_AUTOMATIC_RESIZING
#define EIGEN_USE_MKL_ALL
#define EIGEN_USE_THREADS
Typedefs
template<typename T >
using MatrixType = Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic >
template<typename T >
using VectorType = Eigen::Matrix< T, Eigen::Dynamic, 1 >
Macro Definition Documentation
EIGEN_NO_AUTOMATIC_RESIZING
#define EIGEN_NO_AUTOMATIC_RESIZING
Definition at line 15 of file helper_eigenTensorConversion.hpp.
EIGEN_USE_MKL_ALL
#define EIGEN_USE_MKL_ALL
Definition at line 16 of file helper_eigenTensorConversion.hpp.
EIGEN_USE_THREADS
#define EIGEN_USE_THREADS
Definition at line 17 of file helper_eigenTensorConversion.hpp.
Typedef Documentation
MatrixType
template<typename T > using MatrixType = Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic>
Definition at line 22 of file helper_eigenTensorConversion.hpp.
VectorType
template<typename T > using VectorType = Eigen::Matrix<T, Eigen::Dynamic, 1>
Definition at line 23 of file helper_eigenTensorConversion.hpp.
Function Documentation
asEval()
template<typename T , typename Device = Eigen::DefaultDevice> auto asEval (const Eigen::TensorBase< T, Eigen::ReadOnlyAccessors > & expr, const Device & device = Device())
Convert between Eigen::Tensor and Eigen::Matrix classes.
Note
example useage:
Eigen::Tensor<double, 4> my_rank4(2, 2, 2, 2);
my_rank4.setRandom();
Eigen::MatrixXd          mymatrix = MatrixCast(my_rank4, 4, 4);    // Cast Eigen::Tensor --> Eigen::Matrix
Eigen::Tensor<double, 3> my_rank3 = TensorCast(mymatrix, 2, 2, 4); // Cast Eigen::Matrix --> Eigen::Tensor
Convert Eigen::Tensor --> Eigen::Matrix
Definition at line 47 of file helper_eigenTensorConversion.hpp.
 {
     using Evaluator                         = Eigen::TensorEvaluator<const Eigen::TensorForcedEvalOp<const T>, Device>;
     Eigen::TensorForcedEvalOp<const T> eval = expr.eval();
     Evaluator                          tensor(eval, device);
     tensor.evalSubExprsIfNeeded(nullptr);
     return tensor;
 }
Referenced by MatrixCast(), and VectorCast().
MatrixCast()
template<typename T , typename sizeType , typename Device = Eigen::DefaultDevice> auto MatrixCast (const Eigen::TensorBase< T, Eigen::ReadOnlyAccessors > & expr, const sizeType rows, const sizeType cols, const Device & device = Device())
Definition at line 62 of file helper_eigenTensorConversion.hpp.
 {
     auto tensor  = asEval(expr, device);
     using Scalar = typename Eigen::internal::remove_const<typename decltype(tensor)::Scalar>::type;
     return static_cast<MatrixType<Scalar>>(Eigen::Map<const MatrixType<Scalar>>(tensor.data(), rows, cols));
 }
References asEval().
Referenced by potentialHydrodynamics::calcBodyTensors(), and potentialHydrodynamics::calcHydroForces().
VectorCast()
template<typename T , typename Device = Eigen::DefaultDevice> auto VectorCast (const Eigen::TensorBase< T, Eigen::ReadOnlyAccessors > & expr, const Device & device = Device())
Definition at line 73 of file helper_eigenTensorConversion.hpp.
 {
     auto tensor  = asEval(expr, device);
     auto size    = Eigen::internal::array_prod(tensor.dimensions());
     using Scalar = typename Eigen::internal::remove_const<typename decltype(tensor)::Scalar>::type;
     return static_cast<VectorType<Scalar>>(Eigen::Map<const VectorType<Scalar>>(tensor.data(), size));
 }
References asEval().
MatrixMap() [1/2]
template<typename Scalar , auto rank, typename sizeType > auto MatrixMap (const Eigen::Tensor< Scalar, rank > & tensor, const sizeType rows, const sizeType cols)
Definition at line 84 of file helper_eigenTensorConversion.hpp.
 {
     return Eigen::Map<const MatrixType<Scalar>>(tensor.data(), rows, cols);
 }
MatrixMap() [2/2]
template<typename Scalar > auto MatrixMap (const Eigen::Tensor< Scalar, 2 > & tensor)
Definition at line 93 of file helper_eigenTensorConversion.hpp.
 {
     return Eigen::Map<const MatrixType<Scalar>>(tensor.data(), tensor.dimension(0), tensor.dimension(1));
 }
VectorMap()
template<typename Scalar , auto rank> auto VectorMap (const Eigen::Tensor< Scalar, rank > & tensor)
Definition at line 102 of file helper_eigenTensorConversion.hpp.
 {
     return Eigen::Map<const VectorType<Scalar>>(tensor.data(), tensor.size());
 }
TensorCast() [1/4]
template<typename Derived , typename T , auto rank> Eigen::Tensor<typename Derived::Scalar, rank> TensorCast (const Eigen::EigenBase< Derived > & matrix, const std::array< T, rank > & dims)
Convert Eigen::Matrix --> Eigen::Tensor.
Definition at line 117 of file helper_eigenTensorConversion.hpp.
 {
     return Eigen::TensorMap<const Eigen::Tensor<const typename Derived::Scalar, rank>>(matrix.derived().eval().data(),
                                                                                        dims);
 }
Referenced by potentialHydrodynamics::calcAddedMassGrad(), potentialHydrodynamics::calcHydroForces(), potentialHydrodynamics::calcTotalMass(), systemData::gradientChangeOfVariableTensors(), systemData::rigidBodyMotionTensors(), and TensorCast().
TensorCast() [2/4]
template<typename Derived , typename T , auto rank> Eigen::Tensor<typename Derived::Scalar, rank> TensorCast (const Eigen::EigenBase< Derived > & matrix, const Eigen::DSizes< T, rank > & dims)
Definition at line 127 of file helper_eigenTensorConversion.hpp.
 {
     return Eigen::TensorMap<const Eigen::Tensor<const typename Derived::Scalar, rank>>(matrix.derived().eval().data(),
                                                                                        dims);
 }
TensorCast() [3/4]
template<typename Derived , typename... Dims> auto TensorCast (const Eigen::EigenBase< Derived > & matrix, const Dims... dims)
Definition at line 137 of file helper_eigenTensorConversion.hpp.
 {
     static_assert(sizeof...(Dims) > 0, "TensorCast: sizeof... (Dims) must be larger than 0");
     return TensorCast(matrix, std::array<Eigen::Index, sizeof...(Dims)>{dims...});
 }
References TensorCast().
TensorCast() [4/4]
template<typename Derived > auto TensorCast (const Eigen::EigenBase< Derived > & matrix)
Definition at line 147 of file helper_eigenTensorConversion.hpp.
 {
     if constexpr (Derived::ColsAtCompileTime == 1 or Derived::RowsAtCompileTime == 1)
     {
         return TensorCast(matrix, matrix.size());
     }
     else
     {
         return TensorCast(matrix, matrix.rows(), matrix.cols());
     }
 }
References TensorCast().
TensorMap() [1/3]
template<typename Derived , auto rank> auto TensorMap (const Eigen::PlainObjectBase< Derived > & matrix, const std::array< long, rank > & dims)
Definition at line 163 of file helper_eigenTensorConversion.hpp.
 {
     return Eigen::TensorMap<const Eigen::Tensor<const typename Derived::Scalar, rank>>(matrix.derived().data(), dims);
 }
Referenced by TensorMap().
TensorMap() [2/3]
template<typename Derived , typename... Dims> auto TensorMap (const Eigen::PlainObjectBase< Derived > & matrix, const Dims... dims)
Definition at line 172 of file helper_eigenTensorConversion.hpp.
 {
     return TensorMap(matrix, std::array<long, static_cast<int>(sizeof...(Dims))>{dims...});
 }
References TensorMap().
TensorMap() [3/3]
template<typename Derived > auto TensorMap (const Eigen::PlainObjectBase< Derived > & matrix)
Definition at line 181 of file helper_eigenTensorConversion.hpp.
 {
     if constexpr (Derived::ColsAtCompileTime == 1 or Derived::RowsAtCompileTime == 1)
     {
         return TensorMap(matrix, matrix.size());
     }
     else
     {
         return TensorMap(matrix, matrix.rows(), matrix.cols());
     }
 }
References TensorMap().