Bodies in Potential Flow: src/helpers/cuda/helper_cusolver.h File Reference
helper_cusolver.h File Reference
Prototypes
double vec_norminf (int n, const double *x)
double mat_norminf (int m, int n, const double *A, int lda)
double csr_mat_norminf (int m, int n, int nnzA, const cusparseMatDescr_t descrA, const double *csrValA, const int *csrRowPtrA, const int *csrColIndA)
void display_matrix (int m, int n, int nnzA, const cusparseMatDescr_t descrA, const double *csrValA, const int *csrRowPtrA, const int *csrColIndA)
#include <ctype.h>
#include <cuda_runtime.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cusparse.h"
Classes
struct testOpts
Macros
#define SWITCH_CHAR '-'
Macro Definition Documentation
SWITCH_CHAR
#define SWITCH_CHAR '-'
Definition at line 40 of file helper_cusolver.h.
Function Documentation
vec_norminf()
double vec_norminf (int n, const double * x)
Definition at line 49 of file helper_cusolver.h.
{
   double norminf = 0;
   for (int j = 0; j < n; j++) {
     double x_abs = fabs(x[j]);
     norminf = (norminf > x_abs) ? norminf : x_abs;
   }
   return norminf;
 }
References fabs(), and collinear-swimmer-wall-configuration::n.
mat_norminf()
double mat_norminf (int m, int n, const double * A, int lda)
Definition at line 61 of file helper_cusolver.h.
{
   double norminf = 0;
   for (int i = 0; i < m; i++) {
     double sum = 0.0;
     for (int j = 0; j < n; j++) {
       double A_abs = fabs(A[i + j * lda]);
       sum += A_abs;
     }
     norminf = (norminf > sum) ? norminf : sum;
   }
   return norminf;
 }
References fabs(), and collinear-swimmer-wall-configuration::n.
csr_mat_norminf()
double csr_mat_norminf (int m, int n, int nnzA, const cusparseMatDescr_t descrA, const double * csrValA, const int * csrRowPtrA, const int * csrColIndA)
Definition at line 77 of file helper_cusolver.h.
{
   const int baseA =
       (CUSPARSE_INDEX_BASE_ONE == cusparseGetMatIndexBase(descrA)) ? 1 : 0;
   double norminf = 0;
   for (int i = 0; i < m; i++) {
     double sum = 0.0;
     const int start = csrRowPtrA[i] - baseA;
     const int end = csrRowPtrA[i + 1] - baseA;
     for (int colidx = start; colidx < end; colidx++) {
       // const int j = csrColIndA[colidx] - baseA;
       double A_abs = fabs(csrValA[colidx]);
       sum += A_abs;
     }
     norminf = (norminf > sum) ? norminf : sum;
   }
   return norminf;
 }
References fabs().
display_matrix()
void display_matrix (int m, int n, int nnzA, const cusparseMatDescr_t descrA, const double * csrValA, const int * csrRowPtrA, const int * csrColIndA)
Definition at line 98 of file helper_cusolver.h.
{
   const int baseA =
       (CUSPARSE_INDEX_BASE_ONE == cusparseGetMatIndexBase(descrA)) ? 1 : 0;
   printf("m = %d, n = %d, nnz = %d, matlab base-1\n", m, n, nnzA);
   for (int row = 0; row < m; row++) {
     const int start = csrRowPtrA[row] - baseA;
     const int end = csrRowPtrA[row + 1] - baseA;
     for (int colidx = start; colidx < end; colidx++) {
       const int col = csrColIndA[colidx] - baseA;
       double Areg = csrValA[colidx];
       printf("A(%d, %d) = %20.16E\n", row + 1, col + 1, Areg);
     }
   }
 }
References collinear-swimmer-wall-configuration::n.