Bodies in Potential Flow: src/helpers/cuda/helper_math.h File Reference
helper_math.h File Reference
Prototypes
float fminf (float a, float b)
float fmaxf (float a, float b)
int max (int a, int b)
int min (int a, int b)
float rsqrtf (float x)
__host__ __device__ float2 make_float2 (float s)
__host__ __device__ float2 make_float2 (float3 a)
__host__ __device__ float2 make_float2 (int2 a)
__host__ __device__ float2 make_float2 (uint2 a)
__host__ __device__ int2 make_int2 (int s)
__host__ __device__ int2 make_int2 (int3 a)
__host__ __device__ int2 make_int2 (uint2 a)
__host__ __device__ int2 make_int2 (float2 a)
__host__ __device__ uint2 make_uint2 (uint s)
__host__ __device__ uint2 make_uint2 (uint3 a)
__host__ __device__ uint2 make_uint2 (int2 a)
__host__ __device__ float3 make_float3 (float s)
__host__ __device__ float3 make_float3 (float2 a)
__host__ __device__ float3 make_float3 (float2 a, float s)
__host__ __device__ float3 make_float3 (float4 a)
__host__ __device__ float3 make_float3 (int3 a)
__host__ __device__ float3 make_float3 (uint3 a)
__host__ __device__ int3 make_int3 (int s)
__host__ __device__ int3 make_int3 (int2 a)
__host__ __device__ int3 make_int3 (int2 a, int s)
__host__ __device__ int3 make_int3 (uint3 a)
__host__ __device__ int3 make_int3 (float3 a)
__host__ __device__ uint3 make_uint3 (uint s)
__host__ __device__ uint3 make_uint3 (uint2 a)
__host__ __device__ uint3 make_uint3 (uint2 a, uint s)
__host__ __device__ uint3 make_uint3 (uint4 a)
__host__ __device__ uint3 make_uint3 (int3 a)
__host__ __device__ float4 make_float4 (float s)
__host__ __device__ float4 make_float4 (float3 a)
__host__ __device__ float4 make_float4 (float3 a, float w)
__host__ __device__ float4 make_float4 (int4 a)
__host__ __device__ float4 make_float4 (uint4 a)
__host__ __device__ int4 make_int4 (int s)
__host__ __device__ int4 make_int4 (int3 a)
__host__ __device__ int4 make_int4 (int3 a, int w)
__host__ __device__ int4 make_int4 (uint4 a)
__host__ __device__ int4 make_int4 (float4 a)
__host__ __device__ uint4 make_uint4 (uint s)
__host__ __device__ uint4 make_uint4 (uint3 a)
__host__ __device__ uint4 make_uint4 (uint3 a, uint w)
__host__ __device__ uint4 make_uint4 (int4 a)
__host__ __device__ float2 operator- (float2 &a)
__host__ __device__ int2 operator- (int2 &a)
__host__ __device__ float3 operator- (float3 &a)
__host__ __device__ int3 operator- (int3 &a)
__host__ __device__ float4 operator- (float4 &a)
__host__ __device__ int4 operator- (int4 &a)
__host__ __device__ float2 operator+ (float2 a, float2 b)
__host__ __device__ void operator+= (float2 &a, float2 b)
__host__ __device__ float2 operator+ (float2 a, float b)
__host__ __device__ float2 operator+ (float b, float2 a)
__host__ __device__ void operator+= (float2 &a, float b)
__host__ __device__ int2 operator+ (int2 a, int2 b)
__host__ __device__ void operator+= (int2 &a, int2 b)
__host__ __device__ int2 operator+ (int2 a, int b)
__host__ __device__ int2 operator+ (int b, int2 a)
__host__ __device__ void operator+= (int2 &a, int b)
__host__ __device__ uint2 operator+ (uint2 a, uint2 b)
__host__ __device__ void operator+= (uint2 &a, uint2 b)
__host__ __device__ uint2 operator+ (uint2 a, uint b)
__host__ __device__ uint2 operator+ (uint b, uint2 a)
__host__ __device__ void operator+= (uint2 &a, uint b)
__host__ __device__ float3 operator+ (float3 a, float3 b)
__host__ __device__ void operator+= (float3 &a, float3 b)
__host__ __device__ float3 operator+ (float3 a, float b)
__host__ __device__ void operator+= (float3 &a, float b)
__host__ __device__ int3 operator+ (int3 a, int3 b)
__host__ __device__ void operator+= (int3 &a, int3 b)
__host__ __device__ int3 operator+ (int3 a, int b)
__host__ __device__ void operator+= (int3 &a, int b)
__host__ __device__ uint3 operator+ (uint3 a, uint3 b)
__host__ __device__ void operator+= (uint3 &a, uint3 b)
__host__ __device__ uint3 operator+ (uint3 a, uint b)
__host__ __device__ void operator+= (uint3 &a, uint b)
__host__ __device__ int3 operator+ (int b, int3 a)
__host__ __device__ uint3 operator+ (uint b, uint3 a)
__host__ __device__ float3 operator+ (float b, float3 a)
__host__ __device__ float4 operator+ (float4 a, float4 b)
__host__ __device__ void operator+= (float4 &a, float4 b)
__host__ __device__ float4 operator+ (float4 a, float b)
__host__ __device__ float4 operator+ (float b, float4 a)
__host__ __device__ void operator+= (float4 &a, float b)
__host__ __device__ int4 operator+ (int4 a, int4 b)
__host__ __device__ void operator+= (int4 &a, int4 b)
__host__ __device__ int4 operator+ (int4 a, int b)
__host__ __device__ int4 operator+ (int b, int4 a)
__host__ __device__ void operator+= (int4 &a, int b)
__host__ __device__ uint4 operator+ (uint4 a, uint4 b)
__host__ __device__ void operator+= (uint4 &a, uint4 b)
__host__ __device__ uint4 operator+ (uint4 a, uint b)
__host__ __device__ uint4 operator+ (uint b, uint4 a)
__host__ __device__ void operator+= (uint4 &a, uint b)
__host__ __device__ float2 operator- (float2 a, float2 b)
__host__ __device__ void operator-= (float2 &a, float2 b)
__host__ __device__ float2 operator- (float2 a, float b)
__host__ __device__ float2 operator- (float b, float2 a)
__host__ __device__ void operator-= (float2 &a, float b)
__host__ __device__ int2 operator- (int2 a, int2 b)
__host__ __device__ void operator-= (int2 &a, int2 b)
__host__ __device__ int2 operator- (int2 a, int b)
__host__ __device__ int2 operator- (int b, int2 a)
__host__ __device__ void operator-= (int2 &a, int b)
__host__ __device__ uint2 operator- (uint2 a, uint2 b)
__host__ __device__ void operator-= (uint2 &a, uint2 b)
__host__ __device__ uint2 operator- (uint2 a, uint b)
__host__ __device__ uint2 operator- (uint b, uint2 a)
__host__ __device__ void operator-= (uint2 &a, uint b)
__host__ __device__ float3 operator- (float3 a, float3 b)
__host__ __device__ void operator-= (float3 &a, float3 b)
__host__ __device__ float3 operator- (float3 a, float b)
__host__ __device__ float3 operator- (float b, float3 a)
__host__ __device__ void operator-= (float3 &a, float b)
__host__ __device__ int3 operator- (int3 a, int3 b)
__host__ __device__ void operator-= (int3 &a, int3 b)
__host__ __device__ int3 operator- (int3 a, int b)
__host__ __device__ int3 operator- (int b, int3 a)
__host__ __device__ void operator-= (int3 &a, int b)
__host__ __device__ uint3 operator- (uint3 a, uint3 b)
__host__ __device__ void operator-= (uint3 &a, uint3 b)
__host__ __device__ uint3 operator- (uint3 a, uint b)
__host__ __device__ uint3 operator- (uint b, uint3 a)
__host__ __device__ void operator-= (uint3 &a, uint b)
__host__ __device__ float4 operator- (float4 a, float4 b)
__host__ __device__ void operator-= (float4 &a, float4 b)
__host__ __device__ float4 operator- (float4 a, float b)
__host__ __device__ void operator-= (float4 &a, float b)
__host__ __device__ int4 operator- (int4 a, int4 b)
__host__ __device__ void operator-= (int4 &a, int4 b)
__host__ __device__ int4 operator- (int4 a, int b)
__host__ __device__ int4 operator- (int b, int4 a)
__host__ __device__ void operator-= (int4 &a, int b)
__host__ __device__ uint4 operator- (uint4 a, uint4 b)
__host__ __device__ void operator-= (uint4 &a, uint4 b)
__host__ __device__ uint4 operator- (uint4 a, uint b)
__host__ __device__ uint4 operator- (uint b, uint4 a)
__host__ __device__ void operator-= (uint4 &a, uint b)
__host__ __device__ float2 operator* (float2 a, float2 b)
__host__ __device__ void operator*= (float2 &a, float2 b)
__host__ __device__ float2 operator* (float2 a, float b)
__host__ __device__ float2 operator* (float b, float2 a)
__host__ __device__ void operator*= (float2 &a, float b)
__host__ __device__ int2 operator* (int2 a, int2 b)
__host__ __device__ void operator*= (int2 &a, int2 b)
__host__ __device__ int2 operator* (int2 a, int b)
__host__ __device__ int2 operator* (int b, int2 a)
__host__ __device__ void operator*= (int2 &a, int b)
__host__ __device__ uint2 operator* (uint2 a, uint2 b)
__host__ __device__ void operator*= (uint2 &a, uint2 b)
__host__ __device__ uint2 operator* (uint2 a, uint b)
__host__ __device__ uint2 operator* (uint b, uint2 a)
__host__ __device__ void operator*= (uint2 &a, uint b)
__host__ __device__ float3 operator* (float3 a, float3 b)
__host__ __device__ void operator*= (float3 &a, float3 b)
__host__ __device__ float3 operator* (float3 a, float b)
__host__ __device__ float3 operator* (float b, float3 a)
__host__ __device__ void operator*= (float3 &a, float b)
__host__ __device__ int3 operator* (int3 a, int3 b)
__host__ __device__ void operator*= (int3 &a, int3 b)
__host__ __device__ int3 operator* (int3 a, int b)
__host__ __device__ int3 operator* (int b, int3 a)
__host__ __device__ void operator*= (int3 &a, int b)
__host__ __device__ uint3 operator* (uint3 a, uint3 b)
__host__ __device__ void operator*= (uint3 &a, uint3 b)
__host__ __device__ uint3 operator* (uint3 a, uint b)
__host__ __device__ uint3 operator* (uint b, uint3 a)
__host__ __device__ void operator*= (uint3 &a, uint b)
__host__ __device__ float4 operator* (float4 a, float4 b)
__host__ __device__ void operator*= (float4 &a, float4 b)
__host__ __device__ float4 operator* (float4 a, float b)
__host__ __device__ float4 operator* (float b, float4 a)
__host__ __device__ void operator*= (float4 &a, float b)
__host__ __device__ int4 operator* (int4 a, int4 b)
__host__ __device__ void operator*= (int4 &a, int4 b)
__host__ __device__ int4 operator* (int4 a, int b)
__host__ __device__ int4 operator* (int b, int4 a)
__host__ __device__ void operator*= (int4 &a, int b)
__host__ __device__ uint4 operator* (uint4 a, uint4 b)
__host__ __device__ void operator*= (uint4 &a, uint4 b)
__host__ __device__ uint4 operator* (uint4 a, uint b)
__host__ __device__ uint4 operator* (uint b, uint4 a)
__host__ __device__ void operator*= (uint4 &a, uint b)
__host__ __device__ float2 operator/ (float2 a, float2 b)
__host__ __device__ void operator/= (float2 &a, float2 b)
__host__ __device__ float2 operator/ (float2 a, float b)
__host__ __device__ void operator/= (float2 &a, float b)
__host__ __device__ float2 operator/ (float b, float2 a)
__host__ __device__ float3 operator/ (float3 a, float3 b)
__host__ __device__ void operator/= (float3 &a, float3 b)
__host__ __device__ float3 operator/ (float3 a, float b)
__host__ __device__ void operator/= (float3 &a, float b)
__host__ __device__ float3 operator/ (float b, float3 a)
__host__ __device__ float4 operator/ (float4 a, float4 b)
__host__ __device__ void operator/= (float4 &a, float4 b)
__host__ __device__ float4 operator/ (float4 a, float b)
__host__ __device__ void operator/= (float4 &a, float b)
__host__ __device__ float4 operator/ (float b, float4 a)
__host__ __device__ float2 fminf (float2 a, float2 b)
__host__ __device__ float3 fminf (float3 a, float3 b)
__host__ __device__ float4 fminf (float4 a, float4 b)
__host__ __device__ int2 min (int2 a, int2 b)
__host__ __device__ int3 min (int3 a, int3 b)
__host__ __device__ int4 min (int4 a, int4 b)
__host__ __device__ uint2 min (uint2 a, uint2 b)
__host__ __device__ uint3 min (uint3 a, uint3 b)
__host__ __device__ uint4 min (uint4 a, uint4 b)
__host__ __device__ float2 fmaxf (float2 a, float2 b)
__host__ __device__ float3 fmaxf (float3 a, float3 b)
__host__ __device__ float4 fmaxf (float4 a, float4 b)
__host__ __device__ int2 max (int2 a, int2 b)
__host__ __device__ int3 max (int3 a, int3 b)
__host__ __device__ int4 max (int4 a, int4 b)
__host__ __device__ uint2 max (uint2 a, uint2 b)
__host__ __device__ uint3 max (uint3 a, uint3 b)
__host__ __device__ uint4 max (uint4 a, uint4 b)
__device__ __host__ float lerp (float a, float b, float t)
__device__ __host__ float2 lerp (float2 a, float2 b, float t)
__device__ __host__ float3 lerp (float3 a, float3 b, float t)
__device__ __host__ float4 lerp (float4 a, float4 b, float t)
__device__ __host__ float clamp (float f, float a, float b)
__device__ __host__ int clamp (int f, int a, int b)
__device__ __host__ uint clamp (uint f, uint a, uint b)
__device__ __host__ float2 clamp (float2 v, float a, float b)
__device__ __host__ float2 clamp (float2 v, float2 a, float2 b)
__device__ __host__ float3 clamp (float3 v, float a, float b)
__device__ __host__ float3 clamp (float3 v, float3 a, float3 b)
__device__ __host__ float4 clamp (float4 v, float a, float b)
__device__ __host__ float4 clamp (float4 v, float4 a, float4 b)
__device__ __host__ int2 clamp (int2 v, int a, int b)
__device__ __host__ int2 clamp (int2 v, int2 a, int2 b)
__device__ __host__ int3 clamp (int3 v, int a, int b)
__device__ __host__ int3 clamp (int3 v, int3 a, int3 b)
__device__ __host__ int4 clamp (int4 v, int a, int b)
__device__ __host__ int4 clamp (int4 v, int4 a, int4 b)
__device__ __host__ uint2 clamp (uint2 v, uint a, uint b)
__device__ __host__ uint2 clamp (uint2 v, uint2 a, uint2 b)
__device__ __host__ uint3 clamp (uint3 v, uint a, uint b)
__device__ __host__ uint3 clamp (uint3 v, uint3 a, uint3 b)
__device__ __host__ uint4 clamp (uint4 v, uint a, uint b)
__device__ __host__ uint4 clamp (uint4 v, uint4 a, uint4 b)
__host__ __device__ float dot (float2 a, float2 b)
__host__ __device__ float dot (float3 a, float3 b)
__host__ __device__ float dot (float4 a, float4 b)
__host__ __device__ int dot (int2 a, int2 b)
__host__ __device__ int dot (int3 a, int3 b)
__host__ __device__ int dot (int4 a, int4 b)
__host__ __device__ uint dot (uint2 a, uint2 b)
__host__ __device__ uint dot (uint3 a, uint3 b)
__host__ __device__ uint dot (uint4 a, uint4 b)
__host__ __device__ float length (float2 v)
__host__ __device__ float length (float3 v)
__host__ __device__ float length (float4 v)
__host__ __device__ float2 normalize (float2 v)
__host__ __device__ float3 normalize (float3 v)
__host__ __device__ float4 normalize (float4 v)
__host__ __device__ float2 floorf (float2 v)
__host__ __device__ float3 floorf (float3 v)
__host__ __device__ float4 floorf (float4 v)
__host__ __device__ float fracf (float v)
__host__ __device__ float2 fracf (float2 v)
__host__ __device__ float3 fracf (float3 v)
__host__ __device__ float4 fracf (float4 v)
__host__ __device__ float2 fmodf (float2 a, float2 b)
__host__ __device__ float3 fmodf (float3 a, float3 b)
__host__ __device__ float4 fmodf (float4 a, float4 b)
__host__ __device__ float2 fabs (float2 v)
__host__ __device__ float3 fabs (float3 v)
__host__ __device__ float4 fabs (float4 v)
__host__ __device__ int2 abs (int2 v)
__host__ __device__ int3 abs (int3 v)
__host__ __device__ int4 abs (int4 v)
__host__ __device__ float3 reflect (float3 i, float3 n)
__host__ __device__ float3 cross (float3 a, float3 b)
__device__ __host__ float smoothstep (float a, float b, float x)
__device__ __host__ float2 smoothstep (float2 a, float2 b, float2 x)
__device__ __host__ float3 smoothstep (float3 a, float3 b, float3 x)
__device__ __host__ float4 smoothstep (float4 a, float4 b, float4 x)
#include "cuda_runtime.h"
#include <math.h>
Macros
#define EXIT_WAIVED 2
Typedefs
typedef unsigned int uint
typedef unsigned short ushort
Macro Definition Documentation
EXIT_WAIVED
#define EXIT_WAIVED 2
Definition at line 48 of file helper_math.h.
Typedef Documentation
uint
typedef unsigned int uint
Definition at line 44 of file helper_math.h.
ushort
typedef unsigned short ushort
Definition at line 45 of file helper_math.h.
Function Documentation
fminf() [1/4]
float fminf (float a, float b) inline
Definition at line 58 of file helper_math.h.
 {
     return a < b ? a : b;
 }
Referenced by clamp(), and fminf().
fmaxf() [1/4]
float fmaxf (float a, float b) inline
Definition at line 63 of file helper_math.h.
 {
     return a > b ? a : b;
 }
Referenced by clamp(), and fmaxf().
max() [1/7]
int max (int a, int b) inline
Definition at line 68 of file helper_math.h.
 {
     return a > b ? a : b;
 }
Referenced by clamp(), and max().
min() [1/7]
int min (int a, int b) inline
Definition at line 73 of file helper_math.h.
 {
     return a < b ? a : b;
 }
Referenced by clamp(), and min().
rsqrtf()
float rsqrtf (float x) inline
Definition at line 78 of file helper_math.h.
 {
     return 1.0f / sqrtf(x);
 }
Referenced by normalize().
make_float2() [1/4]
__host__ __device__ float2 make_float2 (float s) inline
Definition at line 88 of file helper_math.h.
 {
     return make_float2(s, s);
 }
Referenced by clamp(), fabs(), floorf(), fmaxf(), fminf(), fmodf(), fracf(), make_float2(), operator*(), operator+(), operator-(), operator/(), and smoothstep().
make_float2() [2/4]
__host__ __device__ float2 make_float2 (float3 a) inline
Definition at line 92 of file helper_math.h.
 {
     return make_float2(a.x, a.y);
 }
References make_float2().
make_float2() [3/4]
__host__ __device__ float2 make_float2 (int2 a) inline
Definition at line 96 of file helper_math.h.
 {
     return make_float2(float(a.x), float(a.y));
 }
References make_float2().
make_float2() [4/4]
__host__ __device__ float2 make_float2 (uint2 a) inline
Definition at line 100 of file helper_math.h.
 {
     return make_float2(float(a.x), float(a.y));
 }
References make_float2().
make_int2() [1/4]
__host__ __device__ int2 make_int2 (int s) inline
Definition at line 105 of file helper_math.h.
 {
     return make_int2(s, s);
 }
Referenced by abs(), clamp(), make_int2(), max(), min(), operator*(), operator+(), and operator-().
make_int2() [2/4]
__host__ __device__ int2 make_int2 (int3 a) inline
Definition at line 109 of file helper_math.h.
 {
     return make_int2(a.x, a.y);
 }
References make_int2().
make_int2() [3/4]
__host__ __device__ int2 make_int2 (uint2 a) inline
Definition at line 113 of file helper_math.h.
 {
     return make_int2(int(a.x), int(a.y));
 }
References make_int2().
make_int2() [4/4]
__host__ __device__ int2 make_int2 (float2 a) inline
Definition at line 117 of file helper_math.h.
 {
     return make_int2(int(a.x), int(a.y));
 }
References make_int2().
make_uint2() [1/3]
__host__ __device__ uint2 make_uint2 (uint s) inline
Definition at line 122 of file helper_math.h.
 {
     return make_uint2(s, s);
 }
Referenced by clamp(), make_uint2(), max(), min(), operator*(), operator+(), and operator-().
make_uint2() [2/3]
__host__ __device__ uint2 make_uint2 (uint3 a) inline
Definition at line 126 of file helper_math.h.
 {
     return make_uint2(a.x, a.y);
 }
References make_uint2().
make_uint2() [3/3]
__host__ __device__ uint2 make_uint2 (int2 a) inline
Definition at line 130 of file helper_math.h.
 {
     return make_uint2(uint(a.x), uint(a.y));
 }
References make_uint2().
make_float3() [1/6]
__host__ __device__ float3 make_float3 (float s) inline
Definition at line 135 of file helper_math.h.
 {
     return make_float3(s, s, s);
 }
Referenced by clamp(), cross(), fabs(), floorf(), fmaxf(), fminf(), fmodf(), fracf(), make_float3(), operator*(), operator+(), operator-(), operator/(), and smoothstep().
make_float3() [2/6]
__host__ __device__ float3 make_float3 (float2 a) inline
Definition at line 139 of file helper_math.h.
 {
     return make_float3(a.x, a.y, 0.0f);
 }
References make_float3().
make_float3() [3/6]
__host__ __device__ float3 make_float3 (float2 a, float s) inline
Definition at line 143 of file helper_math.h.
 {
     return make_float3(a.x, a.y, s);
 }
References make_float3().
make_float3() [4/6]
__host__ __device__ float3 make_float3 (float4 a) inline
Definition at line 147 of file helper_math.h.
 {
     return make_float3(a.x, a.y, a.z);
 }
References make_float3().
make_float3() [5/6]
__host__ __device__ float3 make_float3 (int3 a) inline
Definition at line 151 of file helper_math.h.
 {
     return make_float3(float(a.x), float(a.y), float(a.z));
 }
References make_float3().
make_float3() [6/6]
__host__ __device__ float3 make_float3 (uint3 a) inline
Definition at line 155 of file helper_math.h.
 {
     return make_float3(float(a.x), float(a.y), float(a.z));
 }
References make_float3().
make_int3() [1/5]
__host__ __device__ int3 make_int3 (int s) inline
Definition at line 160 of file helper_math.h.
 {
     return make_int3(s, s, s);
 }
Referenced by abs(), clamp(), make_int3(), max(), min(), operator*(), operator+(), and operator-().
make_int3() [2/5]
__host__ __device__ int3 make_int3 (int2 a) inline
Definition at line 164 of file helper_math.h.
 {
     return make_int3(a.x, a.y, 0);
 }
References make_int3().
make_int3() [3/5]
__host__ __device__ int3 make_int3 (int2 a, int s) inline
Definition at line 168 of file helper_math.h.
 {
     return make_int3(a.x, a.y, s);
 }
References make_int3().
make_int3() [4/5]
__host__ __device__ int3 make_int3 (uint3 a) inline
Definition at line 172 of file helper_math.h.
 {
     return make_int3(int(a.x), int(a.y), int(a.z));
 }
References make_int3().
make_int3() [5/5]
__host__ __device__ int3 make_int3 (float3 a) inline
Definition at line 176 of file helper_math.h.
 {
     return make_int3(int(a.x), int(a.y), int(a.z));
 }
References make_int3().
make_uint3() [1/5]
__host__ __device__ uint3 make_uint3 (uint s) inline
Definition at line 181 of file helper_math.h.
 {
     return make_uint3(s, s, s);
 }
Referenced by clamp(), make_uint3(), max(), min(), operator*(), operator+(), and operator-().
make_uint3() [2/5]
__host__ __device__ uint3 make_uint3 (uint2 a) inline
Definition at line 185 of file helper_math.h.
 {
     return make_uint3(a.x, a.y, 0);
 }
References make_uint3().
make_uint3() [3/5]
__host__ __device__ uint3 make_uint3 (uint2 a, uint s) inline
Definition at line 189 of file helper_math.h.
 {
     return make_uint3(a.x, a.y, s);
 }
References make_uint3().
make_uint3() [4/5]
__host__ __device__ uint3 make_uint3 (uint4 a) inline
Definition at line 193 of file helper_math.h.
 {
     return make_uint3(a.x, a.y, a.z);
 }
References make_uint3().
make_uint3() [5/5]
__host__ __device__ uint3 make_uint3 (int3 a) inline
Definition at line 197 of file helper_math.h.
 {
     return make_uint3(uint(a.x), uint(a.y), uint(a.z));
 }
References make_uint3().
make_float4() [1/5]
__host__ __device__ float4 make_float4 (float s) inline
Definition at line 202 of file helper_math.h.
 {
     return make_float4(s, s, s, s);
 }
Referenced by clamp(), fabs(), floorf(), fmaxf(), fminf(), fmodf(), fracf(), make_float4(), operator*(), operator+(), operator-(), operator/(), and smoothstep().
make_float4() [2/5]
__host__ __device__ float4 make_float4 (float3 a) inline
Definition at line 206 of file helper_math.h.
 {
     return make_float4(a.x, a.y, a.z, 0.0f);
 }
References make_float4().
make_float4() [3/5]
__host__ __device__ float4 make_float4 (float3 a, float w) inline
Definition at line 210 of file helper_math.h.
 {
     return make_float4(a.x, a.y, a.z, w);
 }
References make_float4().
make_float4() [4/5]
__host__ __device__ float4 make_float4 (int4 a) inline
Definition at line 214 of file helper_math.h.
 {
     return make_float4(float(a.x), float(a.y), float(a.z), float(a.w));
 }
References make_float4().
make_float4() [5/5]
__host__ __device__ float4 make_float4 (uint4 a) inline
Definition at line 218 of file helper_math.h.
 {
     return make_float4(float(a.x), float(a.y), float(a.z), float(a.w));
 }
References make_float4().
make_int4() [1/5]
__host__ __device__ int4 make_int4 (int s) inline
Definition at line 223 of file helper_math.h.
 {
     return make_int4(s, s, s, s);
 }
Referenced by abs(), clamp(), make_int4(), max(), min(), operator*(), operator+(), and operator-().
make_int4() [2/5]
__host__ __device__ int4 make_int4 (int3 a) inline
Definition at line 227 of file helper_math.h.
 {
     return make_int4(a.x, a.y, a.z, 0);
 }
References make_int4().
make_int4() [3/5]
__host__ __device__ int4 make_int4 (int3 a, int w) inline
Definition at line 231 of file helper_math.h.
 {
     return make_int4(a.x, a.y, a.z, w);
 }
References make_int4().
make_int4() [4/5]
__host__ __device__ int4 make_int4 (uint4 a) inline
Definition at line 235 of file helper_math.h.
 {
     return make_int4(int(a.x), int(a.y), int(a.z), int(a.w));
 }
References make_int4().
make_int4() [5/5]
__host__ __device__ int4 make_int4 (float4 a) inline
Definition at line 239 of file helper_math.h.
 {
     return make_int4(int(a.x), int(a.y), int(a.z), int(a.w));
 }
References make_int4().
make_uint4() [1/4]
__host__ __device__ uint4 make_uint4 (uint s) inline
Definition at line 245 of file helper_math.h.
 {
     return make_uint4(s, s, s, s);
 }
Referenced by clamp(), make_uint4(), max(), min(), operator*(), operator+(), and operator-().
make_uint4() [2/4]
__host__ __device__ uint4 make_uint4 (uint3 a) inline
Definition at line 249 of file helper_math.h.
 {
     return make_uint4(a.x, a.y, a.z, 0);
 }
References make_uint4().
make_uint4() [3/4]
__host__ __device__ uint4 make_uint4 (uint3 a, uint w) inline
Definition at line 253 of file helper_math.h.
 {
     return make_uint4(a.x, a.y, a.z, w);
 }
References make_uint4().
make_uint4() [4/4]
__host__ __device__ uint4 make_uint4 (int4 a) inline
Definition at line 257 of file helper_math.h.
 {
     return make_uint4(uint(a.x), uint(a.y), uint(a.z), uint(a.w));
 }
References make_uint4().
operator-() [1/32]
__host__ __device__ float2 operator- (float2 & a) inline
Definition at line 266 of file helper_math.h.
 {
     return make_float2(-a.x, -a.y);
 }
References make_float2().
operator-() [2/32]
__host__ __device__ int2 operator- (int2 & a) inline
Definition at line 270 of file helper_math.h.
 {
     return make_int2(-a.x, -a.y);
 }
References make_int2().
operator-() [3/32]
__host__ __device__ float3 operator- (float3 & a) inline
Definition at line 274 of file helper_math.h.
 {
     return make_float3(-a.x, -a.y, -a.z);
 }
References make_float3().
operator-() [4/32]
__host__ __device__ int3 operator- (int3 & a) inline
Definition at line 278 of file helper_math.h.
 {
     return make_int3(-a.x, -a.y, -a.z);
 }
References make_int3().
operator-() [5/32]
__host__ __device__ float4 operator- (float4 & a) inline
Definition at line 282 of file helper_math.h.
 {
     return make_float4(-a.x, -a.y, -a.z, -a.w);
 }
References make_float4().
operator-() [6/32]
__host__ __device__ int4 operator- (int4 & a) inline
Definition at line 286 of file helper_math.h.
 {
     return make_int4(-a.x, -a.y, -a.z, -a.w);
 }
References make_int4().
operator+() [1/27]
__host__ __device__ float2 operator+ (float2 a, float2 b) inline
Definition at line 295 of file helper_math.h.
 {
     return make_float2(a.x + b.x, a.y + b.y);
 }
References make_float2().
operator+=() [1/18]
__host__ __device__ void operator+= (float2 & a, float2 b) inline
Definition at line 299 of file helper_math.h.
 {
     a.x += b.x;
     a.y += b.y;
 }
operator+() [2/27]
__host__ __device__ float2 operator+ (float2 a, float b) inline
Definition at line 304 of file helper_math.h.
 {
     return make_float2(a.x + b, a.y + b);
 }
References make_float2().
operator+() [3/27]
__host__ __device__ float2 operator+ (float b, float2 a) inline
Definition at line 308 of file helper_math.h.
 {
     return make_float2(a.x + b, a.y + b);
 }
References make_float2().
operator+=() [2/18]
__host__ __device__ void operator+= (float2 & a, float b) inline
Definition at line 312 of file helper_math.h.
 {
     a.x += b;
     a.y += b;
 }
operator+() [4/27]
__host__ __device__ int2 operator+ (int2 a, int2 b) inline
Definition at line 318 of file helper_math.h.
 {
     return make_int2(a.x + b.x, a.y + b.y);
 }
References make_int2().
operator+=() [3/18]
__host__ __device__ void operator+= (int2 & a, int2 b) inline
Definition at line 322 of file helper_math.h.
 {
     a.x += b.x;
     a.y += b.y;
 }
operator+() [5/27]
__host__ __device__ int2 operator+ (int2 a, int b) inline
Definition at line 327 of file helper_math.h.
 {
     return make_int2(a.x + b, a.y + b);
 }
References make_int2().
operator+() [6/27]
__host__ __device__ int2 operator+ (int b, int2 a) inline
Definition at line 331 of file helper_math.h.
 {
     return make_int2(a.x + b, a.y + b);
 }
References make_int2().
operator+=() [4/18]
__host__ __device__ void operator+= (int2 & a, int b) inline
Definition at line 335 of file helper_math.h.
 {
     a.x += b;
     a.y += b;
 }
operator+() [7/27]
__host__ __device__ uint2 operator+ (uint2 a, uint2 b) inline
Definition at line 341 of file helper_math.h.
 {
     return make_uint2(a.x + b.x, a.y + b.y);
 }
References make_uint2().
operator+=() [5/18]
__host__ __device__ void operator+= (uint2 & a, uint2 b) inline
Definition at line 345 of file helper_math.h.
 {
     a.x += b.x;
     a.y += b.y;
 }
operator+() [8/27]
__host__ __device__ uint2 operator+ (uint2 a, uint b) inline
Definition at line 350 of file helper_math.h.
 {
     return make_uint2(a.x + b, a.y + b);
 }
References make_uint2().
operator+() [9/27]
__host__ __device__ uint2 operator+ (uint b, uint2 a) inline
Definition at line 354 of file helper_math.h.
 {
     return make_uint2(a.x + b, a.y + b);
 }
References make_uint2().
operator+=() [6/18]
__host__ __device__ void operator+= (uint2 & a, uint b) inline
Definition at line 358 of file helper_math.h.
 {
     a.x += b;
     a.y += b;
 }
operator+() [10/27]
__host__ __device__ float3 operator+ (float3 a, float3 b) inline
Definition at line 365 of file helper_math.h.
 {
     return make_float3(a.x + b.x, a.y + b.y, a.z + b.z);
 }
References make_float3().
operator+=() [7/18]
__host__ __device__ void operator+= (float3 & a, float3 b) inline
Definition at line 369 of file helper_math.h.
 {
     a.x += b.x;
     a.y += b.y;
     a.z += b.z;
 }
operator+() [11/27]
__host__ __device__ float3 operator+ (float3 a, float b) inline
Definition at line 375 of file helper_math.h.
 {
     return make_float3(a.x + b, a.y + b, a.z + b);
 }
References make_float3().
operator+=() [8/18]
__host__ __device__ void operator+= (float3 & a, float b) inline
Definition at line 379 of file helper_math.h.
 {
     a.x += b;
     a.y += b;
     a.z += b;
 }
operator+() [12/27]
__host__ __device__ int3 operator+ (int3 a, int3 b) inline
Definition at line 386 of file helper_math.h.
 {
     return make_int3(a.x + b.x, a.y + b.y, a.z + b.z);
 }
References make_int3().
operator+=() [9/18]
__host__ __device__ void operator+= (int3 & a, int3 b) inline
Definition at line 390 of file helper_math.h.
 {
     a.x += b.x;
     a.y += b.y;
     a.z += b.z;
 }
operator+() [13/27]
__host__ __device__ int3 operator+ (int3 a, int b) inline
Definition at line 396 of file helper_math.h.
 {
     return make_int3(a.x + b, a.y + b, a.z + b);
 }
References make_int3().
operator+=() [10/18]
__host__ __device__ void operator+= (int3 & a, int b) inline
Definition at line 400 of file helper_math.h.
 {
     a.x += b;
     a.y += b;
     a.z += b;
 }
operator+() [14/27]
__host__ __device__ uint3 operator+ (uint3 a, uint3 b) inline
Definition at line 407 of file helper_math.h.
 {
     return make_uint3(a.x + b.x, a.y + b.y, a.z + b.z);
 }
References make_uint3().
operator+=() [11/18]
__host__ __device__ void operator+= (uint3 & a, uint3 b) inline
Definition at line 411 of file helper_math.h.
 {
     a.x += b.x;
     a.y += b.y;
     a.z += b.z;
 }
operator+() [15/27]
__host__ __device__ uint3 operator+ (uint3 a, uint b) inline
Definition at line 417 of file helper_math.h.
 {
     return make_uint3(a.x + b, a.y + b, a.z + b);
 }
References make_uint3().
operator+=() [12/18]
__host__ __device__ void operator+= (uint3 & a, uint b) inline
Definition at line 421 of file helper_math.h.
 {
     a.x += b;
     a.y += b;
     a.z += b;
 }
operator+() [16/27]
__host__ __device__ int3 operator+ (int b, int3 a) inline
Definition at line 428 of file helper_math.h.
 {
     return make_int3(a.x + b, a.y + b, a.z + b);
 }
References make_int3().
operator+() [17/27]
__host__ __device__ uint3 operator+ (uint b, uint3 a) inline
Definition at line 432 of file helper_math.h.
 {
     return make_uint3(a.x + b, a.y + b, a.z + b);
 }
References make_uint3().
operator+() [18/27]
__host__ __device__ float3 operator+ (float b, float3 a) inline
Definition at line 436 of file helper_math.h.
 {
     return make_float3(a.x + b, a.y + b, a.z + b);
 }
References make_float3().
operator+() [19/27]
__host__ __device__ float4 operator+ (float4 a, float4 b) inline
Definition at line 441 of file helper_math.h.
 {
     return make_float4(a.x + b.x, a.y + b.y, a.z + b.z,  a.w + b.w);
 }
References make_float4().
operator+=() [13/18]
__host__ __device__ void operator+= (float4 & a, float4 b) inline
Definition at line 445 of file helper_math.h.
 {
     a.x += b.x;
     a.y += b.y;
     a.z += b.z;
     a.w += b.w;
 }
operator+() [20/27]
__host__ __device__ float4 operator+ (float4 a, float b) inline
Definition at line 452 of file helper_math.h.
 {
     return make_float4(a.x + b, a.y + b, a.z + b, a.w + b);
 }
References make_float4().
operator+() [21/27]
__host__ __device__ float4 operator+ (float b, float4 a) inline
Definition at line 456 of file helper_math.h.
 {
     return make_float4(a.x + b, a.y + b, a.z + b, a.w + b);
 }
References make_float4().
operator+=() [14/18]
__host__ __device__ void operator+= (float4 & a, float b) inline
Definition at line 460 of file helper_math.h.
 {
     a.x += b;
     a.y += b;
     a.z += b;
     a.w += b;
 }
operator+() [22/27]
__host__ __device__ int4 operator+ (int4 a, int4 b) inline
Definition at line 468 of file helper_math.h.
 {
     return make_int4(a.x + b.x, a.y + b.y, a.z + b.z,  a.w + b.w);
 }
References make_int4().
operator+=() [15/18]
__host__ __device__ void operator+= (int4 & a, int4 b) inline
Definition at line 472 of file helper_math.h.
 {
     a.x += b.x;
     a.y += b.y;
     a.z += b.z;
     a.w += b.w;
 }
operator+() [23/27]
__host__ __device__ int4 operator+ (int4 a, int b) inline
Definition at line 479 of file helper_math.h.
 {
     return make_int4(a.x + b, a.y + b, a.z + b,  a.w + b);
 }
References make_int4().
operator+() [24/27]
__host__ __device__ int4 operator+ (int b, int4 a) inline
Definition at line 483 of file helper_math.h.
 {
     return make_int4(a.x + b, a.y + b, a.z + b,  a.w + b);
 }
References make_int4().
operator+=() [16/18]
__host__ __device__ void operator+= (int4 & a, int b) inline
Definition at line 487 of file helper_math.h.
 {
     a.x += b;
     a.y += b;
     a.z += b;
     a.w += b;
 }
operator+() [25/27]
__host__ __device__ uint4 operator+ (uint4 a, uint4 b) inline
Definition at line 495 of file helper_math.h.
 {
     return make_uint4(a.x + b.x, a.y + b.y, a.z + b.z,  a.w + b.w);
 }
References make_uint4().
operator+=() [17/18]
__host__ __device__ void operator+= (uint4 & a, uint4 b) inline
Definition at line 499 of file helper_math.h.
 {
     a.x += b.x;
     a.y += b.y;
     a.z += b.z;
     a.w += b.w;
 }
operator+() [26/27]
__host__ __device__ uint4 operator+ (uint4 a, uint b) inline
Definition at line 506 of file helper_math.h.
 {
     return make_uint4(a.x + b, a.y + b, a.z + b,  a.w + b);
 }
References make_uint4().
operator+() [27/27]
__host__ __device__ uint4 operator+ (uint b, uint4 a) inline
Definition at line 510 of file helper_math.h.
 {
     return make_uint4(a.x + b, a.y + b, a.z + b,  a.w + b);
 }
References make_uint4().
operator+=() [18/18]
__host__ __device__ void operator+= (uint4 & a, uint b) inline
Definition at line 514 of file helper_math.h.
 {
     a.x += b;
     a.y += b;
     a.z += b;
     a.w += b;
 }
operator-() [7/32]
__host__ __device__ float2 operator- (float2 a, float2 b) inline
Definition at line 526 of file helper_math.h.
 {
     return make_float2(a.x - b.x, a.y - b.y);
 }
References make_float2().
operator-=() [1/18]
__host__ __device__ void operator-= (float2 & a, float2 b) inline
Definition at line 530 of file helper_math.h.
 {
     a.x -= b.x;
     a.y -= b.y;
 }
operator-() [8/32]
__host__ __device__ float2 operator- (float2 a, float b) inline
Definition at line 535 of file helper_math.h.
 {
     return make_float2(a.x - b, a.y - b);
 }
References make_float2().
operator-() [9/32]
__host__ __device__ float2 operator- (float b, float2 a) inline
Definition at line 539 of file helper_math.h.
 {
     return make_float2(b - a.x, b - a.y);
 }
References make_float2().
operator-=() [2/18]
__host__ __device__ void operator-= (float2 & a, float b) inline
Definition at line 543 of file helper_math.h.
 {
     a.x -= b;
     a.y -= b;
 }
operator-() [10/32]
__host__ __device__ int2 operator- (int2 a, int2 b) inline
Definition at line 549 of file helper_math.h.
 {
     return make_int2(a.x - b.x, a.y - b.y);
 }
References make_int2().
operator-=() [3/18]
__host__ __device__ void operator-= (int2 & a, int2 b) inline
Definition at line 553 of file helper_math.h.
 {
     a.x -= b.x;
     a.y -= b.y;
 }
operator-() [11/32]
__host__ __device__ int2 operator- (int2 a, int b) inline
Definition at line 558 of file helper_math.h.
 {
     return make_int2(a.x - b, a.y - b);
 }
References make_int2().
operator-() [12/32]
__host__ __device__ int2 operator- (int b, int2 a) inline
Definition at line 562 of file helper_math.h.
 {
     return make_int2(b - a.x, b - a.y);
 }
References make_int2().
operator-=() [4/18]
__host__ __device__ void operator-= (int2 & a, int b) inline
Definition at line 566 of file helper_math.h.
 {
     a.x -= b;
     a.y -= b;
 }
operator-() [13/32]
__host__ __device__ uint2 operator- (uint2 a, uint2 b) inline
Definition at line 572 of file helper_math.h.
 {
     return make_uint2(a.x - b.x, a.y - b.y);
 }
References make_uint2().
operator-=() [5/18]
__host__ __device__ void operator-= (uint2 & a, uint2 b) inline
Definition at line 576 of file helper_math.h.
 {
     a.x -= b.x;
     a.y -= b.y;
 }
operator-() [14/32]
__host__ __device__ uint2 operator- (uint2 a, uint b) inline
Definition at line 581 of file helper_math.h.
 {
     return make_uint2(a.x - b, a.y - b);
 }
References make_uint2().
operator-() [15/32]
__host__ __device__ uint2 operator- (uint b, uint2 a) inline
Definition at line 585 of file helper_math.h.
 {
     return make_uint2(b - a.x, b - a.y);
 }
References make_uint2().
operator-=() [6/18]
__host__ __device__ void operator-= (uint2 & a, uint b) inline
Definition at line 589 of file helper_math.h.
 {
     a.x -= b;
     a.y -= b;
 }
operator-() [16/32]
__host__ __device__ float3 operator- (float3 a, float3 b) inline
Definition at line 595 of file helper_math.h.
 {
     return make_float3(a.x - b.x, a.y - b.y, a.z - b.z);
 }
References make_float3().
operator-=() [7/18]
__host__ __device__ void operator-= (float3 & a, float3 b) inline
Definition at line 599 of file helper_math.h.
 {
     a.x -= b.x;
     a.y -= b.y;
     a.z -= b.z;
 }
operator-() [17/32]
__host__ __device__ float3 operator- (float3 a, float b) inline
Definition at line 605 of file helper_math.h.
 {
     return make_float3(a.x - b, a.y - b, a.z - b);
 }
References make_float3().
operator-() [18/32]
__host__ __device__ float3 operator- (float b, float3 a) inline
Definition at line 609 of file helper_math.h.
 {
     return make_float3(b - a.x, b - a.y, b - a.z);
 }
References make_float3().
operator-=() [8/18]
__host__ __device__ void operator-= (float3 & a, float b) inline
Definition at line 613 of file helper_math.h.
 {
     a.x -= b;
     a.y -= b;
     a.z -= b;
 }
operator-() [19/32]
__host__ __device__ int3 operator- (int3 a, int3 b) inline
Definition at line 620 of file helper_math.h.
 {
     return make_int3(a.x - b.x, a.y - b.y, a.z - b.z);
 }
References make_int3().
operator-=() [9/18]
__host__ __device__ void operator-= (int3 & a, int3 b) inline
Definition at line 624 of file helper_math.h.
 {
     a.x -= b.x;
     a.y -= b.y;
     a.z -= b.z;
 }
operator-() [20/32]
__host__ __device__ int3 operator- (int3 a, int b) inline
Definition at line 630 of file helper_math.h.
 {
     return make_int3(a.x - b, a.y - b, a.z - b);
 }
References make_int3().
operator-() [21/32]
__host__ __device__ int3 operator- (int b, int3 a) inline
Definition at line 634 of file helper_math.h.
 {
     return make_int3(b - a.x, b - a.y, b - a.z);
 }
References make_int3().
operator-=() [10/18]
__host__ __device__ void operator-= (int3 & a, int b) inline
Definition at line 638 of file helper_math.h.
 {
     a.x -= b;
     a.y -= b;
     a.z -= b;
 }
operator-() [22/32]
__host__ __device__ uint3 operator- (uint3 a, uint3 b) inline
Definition at line 645 of file helper_math.h.
 {
     return make_uint3(a.x - b.x, a.y - b.y, a.z - b.z);
 }
References make_uint3().
operator-=() [11/18]
__host__ __device__ void operator-= (uint3 & a, uint3 b) inline
Definition at line 649 of file helper_math.h.
 {
     a.x -= b.x;
     a.y -= b.y;
     a.z -= b.z;
 }
operator-() [23/32]
__host__ __device__ uint3 operator- (uint3 a, uint b) inline
Definition at line 655 of file helper_math.h.
 {
     return make_uint3(a.x - b, a.y - b, a.z - b);
 }
References make_uint3().
operator-() [24/32]
__host__ __device__ uint3 operator- (uint b, uint3 a) inline
Definition at line 659 of file helper_math.h.
 {
     return make_uint3(b - a.x, b - a.y, b - a.z);
 }
References make_uint3().
operator-=() [12/18]
__host__ __device__ void operator-= (uint3 & a, uint b) inline
Definition at line 663 of file helper_math.h.
 {
     a.x -= b;
     a.y -= b;
     a.z -= b;
 }
operator-() [25/32]
__host__ __device__ float4 operator- (float4 a, float4 b) inline
Definition at line 670 of file helper_math.h.
 {
     return make_float4(a.x - b.x, a.y - b.y, a.z - b.z,  a.w - b.w);
 }
References make_float4().
operator-=() [13/18]
__host__ __device__ void operator-= (float4 & a, float4 b) inline
Definition at line 674 of file helper_math.h.
 {
     a.x -= b.x;
     a.y -= b.y;
     a.z -= b.z;
     a.w -= b.w;
 }
operator-() [26/32]
__host__ __device__ float4 operator- (float4 a, float b) inline
Definition at line 681 of file helper_math.h.
 {
     return make_float4(a.x - b, a.y - b, a.z - b,  a.w - b);
 }
References make_float4().
operator-=() [14/18]
__host__ __device__ void operator-= (float4 & a, float b) inline
Definition at line 685 of file helper_math.h.
 {
     a.x -= b;
     a.y -= b;
     a.z -= b;
     a.w -= b;
 }
operator-() [27/32]
__host__ __device__ int4 operator- (int4 a, int4 b) inline
Definition at line 693 of file helper_math.h.
 {
     return make_int4(a.x - b.x, a.y - b.y, a.z - b.z,  a.w - b.w);
 }
References make_int4().
operator-=() [15/18]
__host__ __device__ void operator-= (int4 & a, int4 b) inline
Definition at line 697 of file helper_math.h.
 {
     a.x -= b.x;
     a.y -= b.y;
     a.z -= b.z;
     a.w -= b.w;
 }
operator-() [28/32]
__host__ __device__ int4 operator- (int4 a, int b) inline
Definition at line 704 of file helper_math.h.
 {
     return make_int4(a.x - b, a.y - b, a.z - b,  a.w - b);
 }
References make_int4().
operator-() [29/32]
__host__ __device__ int4 operator- (int b, int4 a) inline
Definition at line 708 of file helper_math.h.
 {
     return make_int4(b - a.x, b - a.y, b - a.z, b - a.w);
 }
References make_int4().
operator-=() [16/18]
__host__ __device__ void operator-= (int4 & a, int b) inline
Definition at line 712 of file helper_math.h.
 {
     a.x -= b;
     a.y -= b;
     a.z -= b;
     a.w -= b;
 }
operator-() [30/32]
__host__ __device__ uint4 operator- (uint4 a, uint4 b) inline
Definition at line 720 of file helper_math.h.
 {
     return make_uint4(a.x - b.x, a.y - b.y, a.z - b.z,  a.w - b.w);
 }
References make_uint4().
operator-=() [17/18]
__host__ __device__ void operator-= (uint4 & a, uint4 b) inline
Definition at line 724 of file helper_math.h.
 {
     a.x -= b.x;
     a.y -= b.y;
     a.z -= b.z;
     a.w -= b.w;
 }
operator-() [31/32]
__host__ __device__ uint4 operator- (uint4 a, uint b) inline
Definition at line 731 of file helper_math.h.
 {
     return make_uint4(a.x - b, a.y - b, a.z - b,  a.w - b);
 }
References make_uint4().
operator-() [32/32]
__host__ __device__ uint4 operator- (uint b, uint4 a) inline
Definition at line 735 of file helper_math.h.
 {
     return make_uint4(b - a.x, b - a.y, b - a.z, b - a.w);
 }
References make_uint4().
operator-=() [18/18]
__host__ __device__ void operator-= (uint4 & a, uint b) inline
Definition at line 739 of file helper_math.h.
 {
     a.x -= b;
     a.y -= b;
     a.z -= b;
     a.w -= b;
 }
operator*() [1/27]
__host__ __device__ float2 operator* (float2 a, float2 b) inline
Definition at line 751 of file helper_math.h.
 {
     return make_float2(a.x * b.x, a.y * b.y);
 }
References make_float2().
operator*=() [1/18]
__host__ __device__ void operator*= (float2 & a, float2 b) inline
Definition at line 755 of file helper_math.h.
 {
     a.x *= b.x;
     a.y *= b.y;
 }
operator*() [2/27]
__host__ __device__ float2 operator* (float2 a, float b) inline
Definition at line 760 of file helper_math.h.
 {
     return make_float2(a.x * b, a.y * b);
 }
References make_float2().
operator*() [3/27]
__host__ __device__ float2 operator* (float b, float2 a) inline
Definition at line 764 of file helper_math.h.
 {
     return make_float2(b * a.x, b * a.y);
 }
References make_float2().
operator*=() [2/18]
__host__ __device__ void operator*= (float2 & a, float b) inline
Definition at line 768 of file helper_math.h.
 {
     a.x *= b;
     a.y *= b;
 }
operator*() [4/27]
__host__ __device__ int2 operator* (int2 a, int2 b) inline
Definition at line 774 of file helper_math.h.
 {
     return make_int2(a.x * b.x, a.y * b.y);
 }
References make_int2().
operator*=() [3/18]
__host__ __device__ void operator*= (int2 & a, int2 b) inline
Definition at line 778 of file helper_math.h.
 {
     a.x *= b.x;
     a.y *= b.y;
 }
operator*() [5/27]
__host__ __device__ int2 operator* (int2 a, int b) inline
Definition at line 783 of file helper_math.h.
 {
     return make_int2(a.x * b, a.y * b);
 }
References make_int2().
operator*() [6/27]
__host__ __device__ int2 operator* (int b, int2 a) inline
Definition at line 787 of file helper_math.h.
 {
     return make_int2(b * a.x, b * a.y);
 }
References make_int2().
operator*=() [4/18]
__host__ __device__ void operator*= (int2 & a, int b) inline
Definition at line 791 of file helper_math.h.
 {
     a.x *= b;
     a.y *= b;
 }
operator*() [7/27]
__host__ __device__ uint2 operator* (uint2 a, uint2 b) inline
Definition at line 797 of file helper_math.h.
 {
     return make_uint2(a.x * b.x, a.y * b.y);
 }
References make_uint2().
operator*=() [5/18]
__host__ __device__ void operator*= (uint2 & a, uint2 b) inline
Definition at line 801 of file helper_math.h.
 {
     a.x *= b.x;
     a.y *= b.y;
 }
operator*() [8/27]
__host__ __device__ uint2 operator* (uint2 a, uint b) inline
Definition at line 806 of file helper_math.h.
 {
     return make_uint2(a.x * b, a.y * b);
 }
References make_uint2().
operator*() [9/27]
__host__ __device__ uint2 operator* (uint b, uint2 a) inline
Definition at line 810 of file helper_math.h.
 {
     return make_uint2(b * a.x, b * a.y);
 }
References make_uint2().
operator*=() [6/18]
__host__ __device__ void operator*= (uint2 & a, uint b) inline
Definition at line 814 of file helper_math.h.
 {
     a.x *= b;
     a.y *= b;
 }
operator*() [10/27]
__host__ __device__ float3 operator* (float3 a, float3 b) inline
Definition at line 820 of file helper_math.h.
 {
     return make_float3(a.x * b.x, a.y * b.y, a.z * b.z);
 }
References make_float3().
operator*=() [7/18]
__host__ __device__ void operator*= (float3 & a, float3 b) inline
Definition at line 824 of file helper_math.h.
 {
     a.x *= b.x;
     a.y *= b.y;
     a.z *= b.z;
 }
operator*() [11/27]
__host__ __device__ float3 operator* (float3 a, float b) inline
Definition at line 830 of file helper_math.h.
 {
     return make_float3(a.x * b, a.y * b, a.z * b);
 }
References make_float3().
operator*() [12/27]
__host__ __device__ float3 operator* (float b, float3 a) inline
Definition at line 834 of file helper_math.h.
 {
     return make_float3(b * a.x, b * a.y, b * a.z);
 }
References make_float3().
operator*=() [8/18]
__host__ __device__ void operator*= (float3 & a, float b) inline
Definition at line 838 of file helper_math.h.
 {
     a.x *= b;
     a.y *= b;
     a.z *= b;
 }
operator*() [13/27]
__host__ __device__ int3 operator* (int3 a, int3 b) inline
Definition at line 845 of file helper_math.h.
 {
     return make_int3(a.x * b.x, a.y * b.y, a.z * b.z);
 }
References make_int3().
operator*=() [9/18]
__host__ __device__ void operator*= (int3 & a, int3 b) inline
Definition at line 849 of file helper_math.h.
 {
     a.x *= b.x;
     a.y *= b.y;
     a.z *= b.z;
 }
operator*() [14/27]
__host__ __device__ int3 operator* (int3 a, int b) inline
Definition at line 855 of file helper_math.h.
 {
     return make_int3(a.x * b, a.y * b, a.z * b);
 }
References make_int3().
operator*() [15/27]
__host__ __device__ int3 operator* (int b, int3 a) inline
Definition at line 859 of file helper_math.h.
 {
     return make_int3(b * a.x, b * a.y, b * a.z);
 }
References make_int3().
operator*=() [10/18]
__host__ __device__ void operator*= (int3 & a, int b) inline
Definition at line 863 of file helper_math.h.
 {
     a.x *= b;
     a.y *= b;
     a.z *= b;
 }
operator*() [16/27]
__host__ __device__ uint3 operator* (uint3 a, uint3 b) inline
Definition at line 870 of file helper_math.h.
 {
     return make_uint3(a.x * b.x, a.y * b.y, a.z * b.z);
 }
References make_uint3().
operator*=() [11/18]
__host__ __device__ void operator*= (uint3 & a, uint3 b) inline
Definition at line 874 of file helper_math.h.
 {
     a.x *= b.x;
     a.y *= b.y;
     a.z *= b.z;
 }
operator*() [17/27]
__host__ __device__ uint3 operator* (uint3 a, uint b) inline
Definition at line 880 of file helper_math.h.
 {
     return make_uint3(a.x * b, a.y * b, a.z * b);
 }
References make_uint3().
operator*() [18/27]
__host__ __device__ uint3 operator* (uint b, uint3 a) inline
Definition at line 884 of file helper_math.h.
 {
     return make_uint3(b * a.x, b * a.y, b * a.z);
 }
References make_uint3().
operator*=() [12/18]
__host__ __device__ void operator*= (uint3 & a, uint b) inline
Definition at line 888 of file helper_math.h.
 {
     a.x *= b;
     a.y *= b;
     a.z *= b;
 }
operator*() [19/27]
__host__ __device__ float4 operator* (float4 a, float4 b) inline
Definition at line 895 of file helper_math.h.
 {
     return make_float4(a.x * b.x, a.y * b.y, a.z * b.z,  a.w * b.w);
 }
References make_float4().
operator*=() [13/18]
__host__ __device__ void operator*= (float4 & a, float4 b) inline
Definition at line 899 of file helper_math.h.
 {
     a.x *= b.x;
     a.y *= b.y;
     a.z *= b.z;
     a.w *= b.w;
 }
operator*() [20/27]
__host__ __device__ float4 operator* (float4 a, float b) inline
Definition at line 906 of file helper_math.h.
 {
     return make_float4(a.x * b, a.y * b, a.z * b,  a.w * b);
 }
References make_float4().
operator*() [21/27]
__host__ __device__ float4 operator* (float b, float4 a) inline
Definition at line 910 of file helper_math.h.
 {
     return make_float4(b * a.x, b * a.y, b * a.z, b * a.w);
 }
References make_float4().
operator*=() [14/18]
__host__ __device__ void operator*= (float4 & a, float b) inline
Definition at line 914 of file helper_math.h.
 {
     a.x *= b;
     a.y *= b;
     a.z *= b;
     a.w *= b;
 }
operator*() [22/27]
__host__ __device__ int4 operator* (int4 a, int4 b) inline
Definition at line 922 of file helper_math.h.
 {
     return make_int4(a.x * b.x, a.y * b.y, a.z * b.z,  a.w * b.w);
 }
References make_int4().
operator*=() [15/18]
__host__ __device__ void operator*= (int4 & a, int4 b) inline
Definition at line 926 of file helper_math.h.
 {
     a.x *= b.x;
     a.y *= b.y;
     a.z *= b.z;
     a.w *= b.w;
 }
operator*() [23/27]
__host__ __device__ int4 operator* (int4 a, int b) inline
Definition at line 933 of file helper_math.h.
 {
     return make_int4(a.x * b, a.y * b, a.z * b,  a.w * b);
 }
References make_int4().
operator*() [24/27]
__host__ __device__ int4 operator* (int b, int4 a) inline
Definition at line 937 of file helper_math.h.
 {
     return make_int4(b * a.x, b * a.y, b * a.z, b * a.w);
 }
References make_int4().
operator*=() [16/18]
__host__ __device__ void operator*= (int4 & a, int b) inline
Definition at line 941 of file helper_math.h.
 {
     a.x *= b;
     a.y *= b;
     a.z *= b;
     a.w *= b;
 }
operator*() [25/27]
__host__ __device__ uint4 operator* (uint4 a, uint4 b) inline
Definition at line 949 of file helper_math.h.
 {
     return make_uint4(a.x * b.x, a.y * b.y, a.z * b.z,  a.w * b.w);
 }
References make_uint4().
operator*=() [17/18]
__host__ __device__ void operator*= (uint4 & a, uint4 b) inline
Definition at line 953 of file helper_math.h.
 {
     a.x *= b.x;
     a.y *= b.y;
     a.z *= b.z;
     a.w *= b.w;
 }
operator*() [26/27]
__host__ __device__ uint4 operator* (uint4 a, uint b) inline
Definition at line 960 of file helper_math.h.
 {
     return make_uint4(a.x * b, a.y * b, a.z * b,  a.w * b);
 }
References make_uint4().
operator*() [27/27]
__host__ __device__ uint4 operator* (uint b, uint4 a) inline
Definition at line 964 of file helper_math.h.
 {
     return make_uint4(b * a.x, b * a.y, b * a.z, b * a.w);
 }
References make_uint4().
operator*=() [18/18]
__host__ __device__ void operator*= (uint4 & a, uint b) inline
Definition at line 968 of file helper_math.h.
 {
     a.x *= b;
     a.y *= b;
     a.z *= b;
     a.w *= b;
 }
operator/() [1/9]
__host__ __device__ float2 operator/ (float2 a, float2 b) inline
Definition at line 980 of file helper_math.h.
 {
     return make_float2(a.x / b.x, a.y / b.y);
 }
References make_float2().
operator/=() [1/6]
__host__ __device__ void operator/= (float2 & a, float2 b) inline
Definition at line 984 of file helper_math.h.
 {
     a.x /= b.x;
     a.y /= b.y;
 }
operator/() [2/9]
__host__ __device__ float2 operator/ (float2 a, float b) inline
Definition at line 989 of file helper_math.h.
 {
     return make_float2(a.x / b, a.y / b);
 }
References make_float2().
operator/=() [2/6]
__host__ __device__ void operator/= (float2 & a, float b) inline
Definition at line 993 of file helper_math.h.
 {
     a.x /= b;
     a.y /= b;
 }
operator/() [3/9]
__host__ __device__ float2 operator/ (float b, float2 a) inline
Definition at line 998 of file helper_math.h.
 {
     return make_float2(b / a.x, b / a.y);
 }
References make_float2().
operator/() [4/9]
__host__ __device__ float3 operator/ (float3 a, float3 b) inline
Definition at line 1003 of file helper_math.h.
 {
     return make_float3(a.x / b.x, a.y / b.y, a.z / b.z);
 }
References make_float3().
operator/=() [3/6]
__host__ __device__ void operator/= (float3 & a, float3 b) inline
Definition at line 1007 of file helper_math.h.
 {
     a.x /= b.x;
     a.y /= b.y;
     a.z /= b.z;
 }
operator/() [5/9]
__host__ __device__ float3 operator/ (float3 a, float b) inline
Definition at line 1013 of file helper_math.h.
 {
     return make_float3(a.x / b, a.y / b, a.z / b);
 }
References make_float3().
operator/=() [4/6]
__host__ __device__ void operator/= (float3 & a, float b) inline
Definition at line 1017 of file helper_math.h.
 {
     a.x /= b;
     a.y /= b;
     a.z /= b;
 }
operator/() [6/9]
__host__ __device__ float3 operator/ (float b, float3 a) inline
Definition at line 1023 of file helper_math.h.
 {
     return make_float3(b / a.x, b / a.y, b / a.z);
 }
References make_float3().
operator/() [7/9]
__host__ __device__ float4 operator/ (float4 a, float4 b) inline
Definition at line 1028 of file helper_math.h.
 {
     return make_float4(a.x / b.x, a.y / b.y, a.z / b.z,  a.w / b.w);
 }
References make_float4().
operator/=() [5/6]
__host__ __device__ void operator/= (float4 & a, float4 b) inline
Definition at line 1032 of file helper_math.h.
 {
     a.x /= b.x;
     a.y /= b.y;
     a.z /= b.z;
     a.w /= b.w;
 }
operator/() [8/9]
__host__ __device__ float4 operator/ (float4 a, float b) inline
Definition at line 1039 of file helper_math.h.
 {
     return make_float4(a.x / b, a.y / b, a.z / b,  a.w / b);
 }
References make_float4().
operator/=() [6/6]
__host__ __device__ void operator/= (float4 & a, float b) inline
Definition at line 1043 of file helper_math.h.
 {
     a.x /= b;
     a.y /= b;
     a.z /= b;
     a.w /= b;
 }
operator/() [9/9]
__host__ __device__ float4 operator/ (float b, float4 a) inline
Definition at line 1050 of file helper_math.h.
 {
     return make_float4(b / a.x, b / a.y, b / a.z, b / a.w);
 }
References make_float4().
fminf() [2/4]
__host__ __device__ float2 fminf (float2 a, float2 b) inline
Definition at line 1059 of file helper_math.h.
 {
     return make_float2(fminf(a.x,b.x), fminf(a.y,b.y));
 }
References fminf(), and make_float2().
fminf() [3/4]
__host__ __device__ float3 fminf (float3 a, float3 b) inline
Definition at line 1063 of file helper_math.h.
 {
     return make_float3(fminf(a.x,b.x), fminf(a.y,b.y), fminf(a.z,b.z));
 }
References fminf(), and make_float3().
fminf() [4/4]
__host__ __device__ float4 fminf (float4 a, float4 b) inline
Definition at line 1067 of file helper_math.h.
 {
     return make_float4(fminf(a.x,b.x), fminf(a.y,b.y), fminf(a.z,b.z), fminf(a.w,b.w));
 }
References fminf(), and make_float4().
min() [2/7]
__host__ __device__ int2 min (int2 a, int2 b) inline
Definition at line 1072 of file helper_math.h.
 {
     return make_int2(min(a.x,b.x), min(a.y,b.y));
 }
References make_int2(), and min().
min() [3/7]
__host__ __device__ int3 min (int3 a, int3 b) inline
Definition at line 1076 of file helper_math.h.
 {
     return make_int3(min(a.x,b.x), min(a.y,b.y), min(a.z,b.z));
 }
References make_int3(), and min().
min() [4/7]
__host__ __device__ int4 min (int4 a, int4 b) inline
Definition at line 1080 of file helper_math.h.
 {
     return make_int4(min(a.x,b.x), min(a.y,b.y), min(a.z,b.z), min(a.w,b.w));
 }
References make_int4(), and min().
min() [5/7]
__host__ __device__ uint2 min (uint2 a, uint2 b) inline
Definition at line 1085 of file helper_math.h.
 {
     return make_uint2(min(a.x,b.x), min(a.y,b.y));
 }
References make_uint2(), and min().
min() [6/7]
__host__ __device__ uint3 min (uint3 a, uint3 b) inline
Definition at line 1089 of file helper_math.h.
 {
     return make_uint3(min(a.x,b.x), min(a.y,b.y), min(a.z,b.z));
 }
References make_uint3(), and min().
min() [7/7]
__host__ __device__ uint4 min (uint4 a, uint4 b) inline
Definition at line 1093 of file helper_math.h.
 {
     return make_uint4(min(a.x,b.x), min(a.y,b.y), min(a.z,b.z), min(a.w,b.w));
 }
References make_uint4(), and min().
fmaxf() [2/4]
__host__ __device__ float2 fmaxf (float2 a, float2 b) inline
Definition at line 1102 of file helper_math.h.
 {
     return make_float2(fmaxf(a.x,b.x), fmaxf(a.y,b.y));
 }
References fmaxf(), and make_float2().
fmaxf() [3/4]
__host__ __device__ float3 fmaxf (float3 a, float3 b) inline
Definition at line 1106 of file helper_math.h.
 {
     return make_float3(fmaxf(a.x,b.x), fmaxf(a.y,b.y), fmaxf(a.z,b.z));
 }
References fmaxf(), and make_float3().
fmaxf() [4/4]
__host__ __device__ float4 fmaxf (float4 a, float4 b) inline
Definition at line 1110 of file helper_math.h.
 {
     return make_float4(fmaxf(a.x,b.x), fmaxf(a.y,b.y), fmaxf(a.z,b.z), fmaxf(a.w,b.w));
 }
References fmaxf(), and make_float4().
max() [2/7]
__host__ __device__ int2 max (int2 a, int2 b) inline
Definition at line 1115 of file helper_math.h.
 {
     return make_int2(max(a.x,b.x), max(a.y,b.y));
 }
References make_int2(), and max().
max() [3/7]
__host__ __device__ int3 max (int3 a, int3 b) inline
Definition at line 1119 of file helper_math.h.
 {
     return make_int3(max(a.x,b.x), max(a.y,b.y), max(a.z,b.z));
 }
References make_int3(), and max().
max() [4/7]
__host__ __device__ int4 max (int4 a, int4 b) inline
Definition at line 1123 of file helper_math.h.
 {
     return make_int4(max(a.x,b.x), max(a.y,b.y), max(a.z,b.z), max(a.w,b.w));
 }
References make_int4(), and max().
max() [5/7]
__host__ __device__ uint2 max (uint2 a, uint2 b) inline
Definition at line 1128 of file helper_math.h.
 {
     return make_uint2(max(a.x,b.x), max(a.y,b.y));
 }
References make_uint2(), and max().
max() [6/7]
__host__ __device__ uint3 max (uint3 a, uint3 b) inline
Definition at line 1132 of file helper_math.h.
 {
     return make_uint3(max(a.x,b.x), max(a.y,b.y), max(a.z,b.z));
 }
References make_uint3(), and max().
max() [7/7]
__host__ __device__ uint4 max (uint4 a, uint4 b) inline
Definition at line 1136 of file helper_math.h.
 {
     return make_uint4(max(a.x,b.x), max(a.y,b.y), max(a.z,b.z), max(a.w,b.w));
 }
References make_uint4(), and max().
lerp() [1/4]
__device__ __host__ float lerp (float a, float b, float t) inline
Definition at line 1146 of file helper_math.h.
 {
     return a + t*(b-a);
 }
References collinear-swimmer-wall-configuration::t.
lerp() [2/4]
__device__ __host__ float2 lerp (float2 a, float2 b, float t) inline
Definition at line 1150 of file helper_math.h.
 {
     return a + t*(b-a);
 }
References collinear-swimmer-wall-configuration::t.
lerp() [3/4]
__device__ __host__ float3 lerp (float3 a, float3 b, float t) inline
Definition at line 1154 of file helper_math.h.
 {
     return a + t*(b-a);
 }
References collinear-swimmer-wall-configuration::t.
lerp() [4/4]
__device__ __host__ float4 lerp (float4 a, float4 b, float t) inline
Definition at line 1158 of file helper_math.h.
 {
     return a + t*(b-a);
 }
References collinear-swimmer-wall-configuration::t.
clamp() [1/21]
__device__ __host__ float clamp (float f, float a, float b) inline
Definition at line 1168 of file helper_math.h.
 {
     return fmaxf(a, fminf(f, b));
 }
References fmaxf(), and fminf().
Referenced by clamp(), and smoothstep().
clamp() [2/21]
__device__ __host__ int clamp (int f, int a, int b) inline
Definition at line 1172 of file helper_math.h.
 {
     return max(a, min(f, b));
 }
References max(), and min().
clamp() [3/21]
__device__ __host__ uint clamp (uint f, uint a, uint b) inline
Definition at line 1176 of file helper_math.h.
 {
     return max(a, min(f, b));
 }
References max(), and min().
clamp() [4/21]
__device__ __host__ float2 clamp (float2 v, float a, float b) inline
Definition at line 1181 of file helper_math.h.
 {
     return make_float2(clamp(v.x, a, b), clamp(v.y, a, b));
 }
References clamp(), and make_float2().
clamp() [5/21]
__device__ __host__ float2 clamp (float2 v, float2 a, float2 b) inline
Definition at line 1185 of file helper_math.h.
 {
     return make_float2(clamp(v.x, a.x, b.x), clamp(v.y, a.y, b.y));
 }
References clamp(), and make_float2().
clamp() [6/21]
__device__ __host__ float3 clamp (float3 v, float a, float b) inline
Definition at line 1189 of file helper_math.h.
 {
     return make_float3(clamp(v.x, a, b), clamp(v.y, a, b), clamp(v.z, a, b));
 }
References clamp(), and make_float3().
clamp() [7/21]
__device__ __host__ float3 clamp (float3 v, float3 a, float3 b) inline
Definition at line 1193 of file helper_math.h.
 {
     return make_float3(clamp(v.x, a.x, b.x), clamp(v.y, a.y, b.y), clamp(v.z, a.z, b.z));
 }
References clamp(), and make_float3().
clamp() [8/21]
__device__ __host__ float4 clamp (float4 v, float a, float b) inline
Definition at line 1197 of file helper_math.h.
 {
     return make_float4(clamp(v.x, a, b), clamp(v.y, a, b), clamp(v.z, a, b), clamp(v.w, a, b));
 }
References clamp(), and make_float4().
clamp() [9/21]
__device__ __host__ float4 clamp (float4 v, float4 a, float4 b) inline
Definition at line 1201 of file helper_math.h.
 {
     return make_float4(clamp(v.x, a.x, b.x), clamp(v.y, a.y, b.y), clamp(v.z, a.z, b.z), clamp(v.w, a.w, b.w));
 }
References clamp(), and make_float4().
clamp() [10/21]
__device__ __host__ int2 clamp (int2 v, int a, int b) inline
Definition at line 1206 of file helper_math.h.
 {
     return make_int2(clamp(v.x, a, b), clamp(v.y, a, b));
 }
References clamp(), and make_int2().
clamp() [11/21]
__device__ __host__ int2 clamp (int2 v, int2 a, int2 b) inline
Definition at line 1210 of file helper_math.h.
 {
     return make_int2(clamp(v.x, a.x, b.x), clamp(v.y, a.y, b.y));
 }
References clamp(), and make_int2().
clamp() [12/21]
__device__ __host__ int3 clamp (int3 v, int a, int b) inline
Definition at line 1214 of file helper_math.h.
 {
     return make_int3(clamp(v.x, a, b), clamp(v.y, a, b), clamp(v.z, a, b));
 }
References clamp(), and make_int3().
clamp() [13/21]
__device__ __host__ int3 clamp (int3 v, int3 a, int3 b) inline
Definition at line 1218 of file helper_math.h.
 {
     return make_int3(clamp(v.x, a.x, b.x), clamp(v.y, a.y, b.y), clamp(v.z, a.z, b.z));
 }
References clamp(), and make_int3().
clamp() [14/21]
__device__ __host__ int4 clamp (int4 v, int a, int b) inline
Definition at line 1222 of file helper_math.h.
 {
     return make_int4(clamp(v.x, a, b), clamp(v.y, a, b), clamp(v.z, a, b), clamp(v.w, a, b));
 }
References clamp(), and make_int4().
clamp() [15/21]
__device__ __host__ int4 clamp (int4 v, int4 a, int4 b) inline
Definition at line 1226 of file helper_math.h.
 {
     return make_int4(clamp(v.x, a.x, b.x), clamp(v.y, a.y, b.y), clamp(v.z, a.z, b.z), clamp(v.w, a.w, b.w));
 }
References clamp(), and make_int4().
clamp() [16/21]
__device__ __host__ uint2 clamp (uint2 v, uint a, uint b) inline
Definition at line 1231 of file helper_math.h.
 {
     return make_uint2(clamp(v.x, a, b), clamp(v.y, a, b));
 }
References clamp(), and make_uint2().
clamp() [17/21]
__device__ __host__ uint2 clamp (uint2 v, uint2 a, uint2 b) inline
Definition at line 1235 of file helper_math.h.
 {
     return make_uint2(clamp(v.x, a.x, b.x), clamp(v.y, a.y, b.y));
 }
References clamp(), and make_uint2().
clamp() [18/21]
__device__ __host__ uint3 clamp (uint3 v, uint a, uint b) inline
Definition at line 1239 of file helper_math.h.
 {
     return make_uint3(clamp(v.x, a, b), clamp(v.y, a, b), clamp(v.z, a, b));
 }
References clamp(), and make_uint3().
clamp() [19/21]
__device__ __host__ uint3 clamp (uint3 v, uint3 a, uint3 b) inline
Definition at line 1243 of file helper_math.h.
 {
     return make_uint3(clamp(v.x, a.x, b.x), clamp(v.y, a.y, b.y), clamp(v.z, a.z, b.z));
 }
References clamp(), and make_uint3().
clamp() [20/21]
__device__ __host__ uint4 clamp (uint4 v, uint a, uint b) inline
Definition at line 1247 of file helper_math.h.
 {
     return make_uint4(clamp(v.x, a, b), clamp(v.y, a, b), clamp(v.z, a, b), clamp(v.w, a, b));
 }
References clamp(), and make_uint4().
clamp() [21/21]
__device__ __host__ uint4 clamp (uint4 v, uint4 a, uint4 b) inline
Definition at line 1251 of file helper_math.h.
 {
     return make_uint4(clamp(v.x, a.x, b.x), clamp(v.y, a.y, b.y), clamp(v.z, a.z, b.z), clamp(v.w, a.w, b.w));
 }
References clamp(), and make_uint4().
dot() [1/9]
__host__ __device__ float dot (float2 a, float2 b) inline
Definition at line 1260 of file helper_math.h.
 {
     return a.x * b.x + a.y * b.y;
 }
Referenced by length(), normalize(), and reflect().
dot() [2/9]
__host__ __device__ float dot (float3 a, float3 b) inline
Definition at line 1264 of file helper_math.h.
 {
     return a.x * b.x + a.y * b.y + a.z * b.z;
 }
dot() [3/9]
__host__ __device__ float dot (float4 a, float4 b) inline
Definition at line 1268 of file helper_math.h.
 {
     return a.x * b.x + a.y * b.y + a.z * b.z + a.w * b.w;
 }
dot() [4/9]
__host__ __device__ int dot (int2 a, int2 b) inline
Definition at line 1273 of file helper_math.h.
 {
     return a.x * b.x + a.y * b.y;
 }
dot() [5/9]
__host__ __device__ int dot (int3 a, int3 b) inline
Definition at line 1277 of file helper_math.h.
 {
     return a.x * b.x + a.y * b.y + a.z * b.z;
 }
dot() [6/9]
__host__ __device__ int dot (int4 a, int4 b) inline
Definition at line 1281 of file helper_math.h.
 {
     return a.x * b.x + a.y * b.y + a.z * b.z + a.w * b.w;
 }
dot() [7/9]
__host__ __device__ uint dot (uint2 a, uint2 b) inline
Definition at line 1286 of file helper_math.h.
 {
     return a.x * b.x + a.y * b.y;
 }
dot() [8/9]
__host__ __device__ uint dot (uint3 a, uint3 b) inline
Definition at line 1290 of file helper_math.h.
 {
     return a.x * b.x + a.y * b.y + a.z * b.z;
 }
dot() [9/9]
__host__ __device__ uint dot (uint4 a, uint4 b) inline
Definition at line 1294 of file helper_math.h.
 {
     return a.x * b.x + a.y * b.y + a.z * b.z + a.w * b.w;
 }
length() [1/3]
__host__ __device__ float length (float2 v) inline
Definition at line 1303 of file helper_math.h.
 {
     return sqrtf(dot(v, v));
 }
References dot().
Referenced by checkCmdLineFlag(), getCmdLineArgumentFloat(), getCmdLineArgumentInt(), getCmdLineArgumentString(), and getCmdLineArgumentValue().
length() [2/3]
__host__ __device__ float length (float3 v) inline
Definition at line 1307 of file helper_math.h.
 {
     return sqrtf(dot(v, v));
 }
References dot().
length() [3/3]
__host__ __device__ float length (float4 v) inline
Definition at line 1311 of file helper_math.h.
 {
     return sqrtf(dot(v, v));
 }
References dot().
normalize() [1/3]
__host__ __device__ float2 normalize (float2 v) inline
Definition at line 1320 of file helper_math.h.
 {
     float invLen = rsqrtf(dot(v, v));
     return v * invLen;
 }
References dot(), and rsqrtf().
normalize() [2/3]
__host__ __device__ float3 normalize (float3 v) inline
Definition at line 1325 of file helper_math.h.
 {
     float invLen = rsqrtf(dot(v, v));
     return v * invLen;
 }
References dot(), and rsqrtf().
normalize() [3/3]
__host__ __device__ float4 normalize (float4 v) inline
Definition at line 1330 of file helper_math.h.
 {
     float invLen = rsqrtf(dot(v, v));
     return v * invLen;
 }
References dot(), and rsqrtf().
floorf() [1/3]
__host__ __device__ float2 floorf (float2 v) inline
Definition at line 1340 of file helper_math.h.
 {
     return make_float2(floorf(v.x), floorf(v.y));
 }
References make_float2().
Referenced by floorf(), and fracf().
floorf() [2/3]
__host__ __device__ float3 floorf (float3 v) inline
Definition at line 1344 of file helper_math.h.
 {
     return make_float3(floorf(v.x), floorf(v.y), floorf(v.z));
 }
References floorf(), and make_float3().
floorf() [3/3]
__host__ __device__ float4 floorf (float4 v) inline
Definition at line 1348 of file helper_math.h.
 {
     return make_float4(floorf(v.x), floorf(v.y), floorf(v.z), floorf(v.w));
 }
References floorf(), and make_float4().
fracf() [1/4]
__host__ __device__ float fracf (float v) inline
Definition at line 1357 of file helper_math.h.
 {
     return v - floorf(v);
 }
References floorf().
Referenced by fracf().
fracf() [2/4]
__host__ __device__ float2 fracf (float2 v) inline
Definition at line 1361 of file helper_math.h.
 {
     return make_float2(fracf(v.x), fracf(v.y));
 }
References fracf(), and make_float2().
fracf() [3/4]
__host__ __device__ float3 fracf (float3 v) inline
Definition at line 1365 of file helper_math.h.
 {
     return make_float3(fracf(v.x), fracf(v.y), fracf(v.z));
 }
References fracf(), and make_float3().
fracf() [4/4]
__host__ __device__ float4 fracf (float4 v) inline
Definition at line 1369 of file helper_math.h.
 {
     return make_float4(fracf(v.x), fracf(v.y), fracf(v.z), fracf(v.w));
 }
References fracf(), and make_float4().
fmodf() [1/3]
__host__ __device__ float2 fmodf (float2 a, float2 b) inline
Definition at line 1378 of file helper_math.h.
 {
     return make_float2(fmodf(a.x, b.x), fmodf(a.y, b.y));
 }
References make_float2().
Referenced by fmodf().
fmodf() [2/3]
__host__ __device__ float3 fmodf (float3 a, float3 b) inline
Definition at line 1382 of file helper_math.h.
 {
     return make_float3(fmodf(a.x, b.x), fmodf(a.y, b.y), fmodf(a.z, b.z));
 }
References fmodf(), and make_float3().
fmodf() [3/3]
__host__ __device__ float4 fmodf (float4 a, float4 b) inline
Definition at line 1386 of file helper_math.h.
 {
     return make_float4(fmodf(a.x, b.x), fmodf(a.y, b.y), fmodf(a.z, b.z), fmodf(a.w, b.w));
 }
References fmodf(), and make_float4().
fabs() [1/3]
__host__ __device__ float2 fabs (float2 v) inline
Definition at line 1395 of file helper_math.h.
 {
     return make_float2(fabs(v.x), fabs(v.y));
 }
References make_float2().
Referenced by csr_mat_norminf(), fabs(), mat_norminf(), and vec_norminf().
fabs() [2/3]
__host__ __device__ float3 fabs (float3 v) inline
Definition at line 1399 of file helper_math.h.
 {
     return make_float3(fabs(v.x), fabs(v.y), fabs(v.z));
 }
References fabs(), and make_float3().
fabs() [3/3]
__host__ __device__ float4 fabs (float4 v) inline
Definition at line 1403 of file helper_math.h.
 {
     return make_float4(fabs(v.x), fabs(v.y), fabs(v.z), fabs(v.w));
 }
References fabs(), and make_float4().
abs() [1/3]
__host__ __device__ int2 abs (int2 v) inline
Definition at line 1408 of file helper_math.h.
 {
     return make_int2(abs(v.x), abs(v.y));
 }
References make_int2().
Referenced by abs().
abs() [2/3]
__host__ __device__ int3 abs (int3 v) inline
Definition at line 1412 of file helper_math.h.
 {
     return make_int3(abs(v.x), abs(v.y), abs(v.z));
 }
References abs(), and make_int3().
abs() [3/3]
__host__ __device__ int4 abs (int4 v) inline
Definition at line 1416 of file helper_math.h.
 {
     return make_int4(abs(v.x), abs(v.y), abs(v.z), abs(v.w));
 }
References abs(), and make_int4().
reflect()
__host__ __device__ float3 reflect (float3 i, float3 n) inline
Definition at line 1427 of file helper_math.h.
 {
     return i - 2.0f * n * dot(n,i);
 }
References dot(), and collinear-swimmer-wall-configuration::n.
cross()
__host__ __device__ float3 cross (float3 a, float3 b) inline
Definition at line 1436 of file helper_math.h.
 {
     return make_float3(a.y*b.z - a.z*b.y, a.z*b.x - a.x*b.z, a.x*b.y - a.y*b.x);
 }
References make_float3().
smoothstep() [1/4]
__device__ __host__ float smoothstep (float a, float b, float x) inline
Definition at line 1448 of file helper_math.h.
 {
     float y = clamp((x - a) / (b - a), 0.0f, 1.0f);
     return (y*y*(3.0f - (2.0f*y)));
 }
References clamp().
smoothstep() [2/4]
__device__ __host__ float2 smoothstep (float2 a, float2 b, float2 x) inline
Definition at line 1453 of file helper_math.h.
 {
     float2 y = clamp((x - a) / (b - a), 0.0f, 1.0f);
     return (y*y*(make_float2(3.0f) - (make_float2(2.0f)*y)));
 }
References clamp(), and make_float2().
smoothstep() [3/4]
__device__ __host__ float3 smoothstep (float3 a, float3 b, float3 x) inline
Definition at line 1458 of file helper_math.h.
 {
     float3 y = clamp((x - a) / (b - a), 0.0f, 1.0f);
     return (y*y*(make_float3(3.0f) - (make_float3(2.0f)*y)));
 }
References clamp(), and make_float3().
smoothstep() [4/4]
__device__ __host__ float4 smoothstep (float4 a, float4 b, float4 x) inline
Definition at line 1463 of file helper_math.h.
 {
     float4 y = clamp((x - a) / (b - a), 0.0f, 1.0f);
     return (y*y*(make_float4(3.0f) - (make_float4(2.0f)*y)));
 }
References clamp(), and make_float4().