Bodies in Potential Flow: plotStyling Namespace Reference
plotStyling Namespace Reference
Classes
class Multiple
class PlotStyling
Functions
def multiple_formatter (denominator=2, number=np.pi, latex=r'\pi')
Function Documentation
multiple_formatter()
def plotStyling.multiple_formatter (denominator = 2, number = np.pi, latex = r'\pi')
Definition at line 522 of file plotStyling.py.
def multiple_formatter(denominator=2, number=np.pi, latex=r'\pi'):
    def gcd(a, b):
        while b:
            a, b = b, a % b
        return a
    def _multiple_formatter(x, pos):
        den = denominator
        num = np.int(np.rint(den*x/number))
        com = gcd(num, den)
        (num, den) = (int(num/com), int(den/com))
        if den == 1:
            if num == 0:
                return r'$0$'
            if num == 1:
                return r'$%s$' % latex
            elif num == -1:
                return r'$-%s$' % latex
            else:
                return r'$%s%s$' % (num, latex)
        else:
            if num == 1:
                return r'$\frac{%s}{%s}$' % (latex, den)
            elif num == -1:
                return r'$\frac{-%s}{%s}$' % (latex, den)
            else:
                return r'$\frac{%s%s}{%s}$' % (num, latex, den)
    return _multiple_formatter
References multiple_formatter().
Referenced by plotStyling.Multiple.formatter(), and multiple_formatter().