Bodies in Potential Flow: collinear-swimmer-internal-dynamics-configuration Namespace Reference
collinear-swimmer-internal-dynamics-configuration Namespace Reference
Functions
def initializeGSD (gsd_path, N, M, dt, ti, tf, tau, num_steps_output, fluid_density, particle_density, wca_epsilon, wca_sigma, image_system)
Create GSD, set log parameters, set particle parameters.
def setInitialConditions (gsd_class, N, M, num_particles_per_body, Z_height, image_system)
Set initial kinematics of GSD file.
def setSystemData (gsd_class, M, R_avg, Z_height, U0, omega, phase_angle)
Set system-specific parameters to GSD class.
def saveGSDFrame (gsd_class)
Save GSD frame to file.
Variables
parser = OptionParser()
dest
help
metavar
int num_steps_output = 1000
float fluid_density = 1.0
float particle_density = 1.0
float wca_epsilon = 0.0
float wca_sigma = 0.0
int num_particles_per_body = 3
list types = ['constrained', 'locater']
options
remainder
gsd_path = str(options.u_gsd_path)
dt = np.double(options.u_dt)
ti = np.double(options.u_ti)
tf = np.double(options.u_tf)
R_avg = np.double(options.u_R_avg)
Z_height = np.double(options.u_Z_height)
phase_angle = np.double(options.u_phase_angle)
U0 = np.double(options.u_U0)
omega = np.double(options.u_omega)
image_system = int(options.u_image_system)
M = int(options.u_number_bodies)
int N = num_particles_per_body * M
tuple tau = (2.0 * np.pi) / omega
tuple epsilon = (U0 / omega) / R_avg
def gsd_class
Function Documentation
initializeGSD()
def collinear-swimmer-internal-dynamics-configuration.initializeGSD (gsd_path, N, M, dt, ti, tf, tau, num_steps_output, fluid_density, particle_density, wca_epsilon, wca_sigma, image_system)
Create GSD, set log parameters, set particle parameters.
Parameters
gsd_path path to GSD file to create
N number of particles to simulate
M number of bodies to simulate
num_particles_per_body number of particles per body
dt integrator finite delta-t
ti integrator initial time
tf integrator final time
tau characteristic simulation time
num_steps_output number of frames to write to GSD during simulation
fluid_density fluid mass density
particle_density particle mass density
wca_epsilon WCA potential energy scale
wca_sigma WCA potential length scale
image_system Integer boolean deciding if simulation is an image system
Returns
GSD_class GSD helper class
Definition at line 113 of file collinear-swimmer-internal-dynamics-configuration.py.
         image_system (int): Integer boolean deciding if simulation is an image system
     Returns:
         GSD_class: GSD helper class
     """
     # Set particle type-ids
     typeid = [None] * N
     for i in range(M):
         typeid[3 * i] = 1
         typeid[3 * i + 1] = 0
         typeid[3 * i + 2] = 0
     # Convert typeid to type required by GSD schema
     typeid = np.array(typeid, dtype=np.uint32)
     # Create GSD
     gsd_class = GSDUtilPy(gsd_path, create_gsd=True)
     # Set GSD log parameters
     gsd_class.setLogParameters(dt, ti, tf, tau,
                                num_steps_output,
                                fluid_density, particle_density,
                                wca_epsilon, wca_sigma,
                                image_system)
     # Set GSD particle parameters
     gsd_class.setParticleParameters(N, types=types, typeid=typeid)
     return gsd_class
 def setInitialConditions(gsd_class,
                          N, M, num_particles_per_body,
setInitialConditions()
def collinear-swimmer-internal-dynamics-configuration.setInitialConditions (gsd_class, N, M, num_particles_per_body, Z_height, image_system)
Set initial kinematics of GSD file.
Parameters
gsd_class GSD helper class
N number of particles to simulate
M number of bodies to simulate
num_particles_per_body number of particles per body
Z_height z-axis height of bodies
image_system Integer boolean deciding if simulation is an image system
Definition at line 154 of file collinear-swimmer-internal-dynamics-configuration.py.
         image_system (int): Integer boolean deciding if simulation is an image system
     """
     # orientation
     quat = np.zeros((N, 4), dtype=np.double)
     no_rotation_quat = np.array([1.0, 0.0, 0.0, 0.0], dtype=np.double)
     for i in range(N):
         quat[i] = no_rotation_quat
     # position (only need to specify locater position, articulation calculated in C++ simulation)
     pos = np.zeros((N, 3), dtype=np.double)
     for i in range(M):
         Ni = 3 * i
         for j in range(num_particles_per_body):
             # "Real" particles in image system
             if ((i < (M/2)) and (image_system == 1)):
                 pos[Ni + j] = [0.0, 0.0, Z_height]
             # "Image" particles in image system
             elif ((i >= (M/2)) and (image_system == 1)):
                 pos[Ni + j] = [0.0, 0.0, -Z_height]
             # All particles in non-image system
             else:
                 pos[Ni + j] = [0.0, 0.0, Z_height]
     vel = np.zeros_like(pos, dtype=np.double)  # Calculated in C++ simulation
     acc = np.zeros_like(pos, dtype=np.double)  # Calculated in C++ simulation
     # output data
     gsd_class.setKinematics(quat, pos, vel, acc)
 def setSystemData(gsd_class,
                   M,
setSystemData()
def collinear-swimmer-internal-dynamics-configuration.setSystemData (gsd_class, M, R_avg, Z_height, U0, omega, phase_angle)
Set system-specific parameters to GSD class.
Parameters
gsd_class GSD helper class
M number of bodies to simulate
R_avg average spacing between particle pairs over course of simulation
Z_height z-axis height of body initially
U0 internal oscillation amplitude of body
omega internal oscillation frequency of body
phase_angle internal oscillation phase angle between particle pairs
Definition at line 210 of file collinear-swimmer-internal-dynamics-configuration.py.
         phase_angle (double): internal oscillation phase angle between particle pairs
     """
     # get snapshot
     snapshot = gsd_class.snapshot
     # convert data to GSD expected type
     l_R_avg = np.array([R_avg], dtype=np.double)
     l_Z_height = np.array([Z_height], dtype=np.double)
     l_U0 = np.array([U0], dtype=np.double)
     l_omega = np.array([omega], dtype=np.double)
     l_phase_angle = np.array([phase_angle], dtype=np.double)
     l_U_swim = np.zeros(6 * M, dtype=np.double)
     l_A_swim = np.zeros(6 * M, dtype=np.double)
     # output data
     snapshot.log['swimmer/R_avg'] = l_R_avg
     snapshot.log['swimmer/Z_height'] = l_Z_height
     snapshot.log['swimmer/U0'] = l_U0
     snapshot.log['swimmer/omega'] = l_omega
     snapshot.log['swimmer/phase_shift'] = l_phase_angle
     snapshot.log['swimmer/U_swim'] = l_U_swim
     snapshot.log['swimmer/A_swim'] = l_A_swim
 def saveGSDFrame(gsd_class):
     """Save GSD frame to file
saveGSDFrame()
def collinear-swimmer-internal-dynamics-configuration.saveGSDFrame (gsd_class)
Save GSD frame to file.
Parameters
gsd_class GSD helper class
Definition at line 242 of file collinear-swimmer-internal-dynamics-configuration.py.
     gsd_class.saveSnapshot()
 # !SECTION: (GSD Creation)
 # SECTION: For use when being called from command line
 if __name__ == "__main__":
     """Main method
Variable Documentation
parser
collinear-swimmer-internal-dynamics-configuration.parser = OptionParser()
Definition at line 28 of file collinear-swimmer-internal-dynamics-configuration.py.
dest
collinear-swimmer-internal-dynamics-configuration.dest
Definition at line 29 of file collinear-swimmer-internal-dynamics-configuration.py.
help
collinear-swimmer-internal-dynamics-configuration.help
Definition at line 30 of file collinear-swimmer-internal-dynamics-configuration.py.
metavar
collinear-swimmer-internal-dynamics-configuration.metavar
Definition at line 31 of file collinear-swimmer-internal-dynamics-configuration.py.
num_steps_output
int collinear-swimmer-internal-dynamics-configuration.num_steps_output = 1000
Definition at line 73 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by GSDUtil.readParameters(), and SystemData.setNumStepsOutput().
fluid_density
float collinear-swimmer-internal-dynamics-configuration.fluid_density = 1.0
Definition at line 76 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by GSDUtil.readParameters(), and SystemData.setFluidDensity().
particle_density
float collinear-swimmer-internal-dynamics-configuration.particle_density = 1.0
Definition at line 77 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by GSDUtil.readParameters(), and SystemData.setParticleDensity().
wca_epsilon
float collinear-swimmer-internal-dynamics-configuration.wca_epsilon = 0.0
Definition at line 80 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by GSDUtil.readParameters(), and SystemData.setWcaEpsilon().
wca_sigma
float collinear-swimmer-internal-dynamics-configuration.wca_sigma = 0.0
Definition at line 81 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by GSDUtil.readParameters(), and SystemData.setWcaSigma().
num_particles_per_body
int collinear-swimmer-internal-dynamics-configuration.num_particles_per_body = 3
Definition at line 84 of file collinear-swimmer-internal-dynamics-configuration.py.
types
list collinear-swimmer-internal-dynamics-configuration.types = ['constrained', 'locater']
Definition at line 85 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by GSDUtil.readParameters().
options
collinear-swimmer-internal-dynamics-configuration.options
Definition at line 256 of file collinear-swimmer-internal-dynamics-configuration.py.
remainder
collinear-swimmer-internal-dynamics-configuration.remainder
Definition at line 256 of file collinear-swimmer-internal-dynamics-configuration.py.
gsd_path
collinear-swimmer-internal-dynamics-configuration.gsd_path = str(options.u_gsd_path)
Definition at line 258 of file collinear-swimmer-internal-dynamics-configuration.py.
dt
collinear-swimmer-internal-dynamics-configuration.dt = np.double(options.u_dt)
Definition at line 260 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by GSDUtil.readParameters(), and GSDUtil.writeParameters().
ti
collinear-swimmer-internal-dynamics-configuration.ti = np.double(options.u_ti)
Definition at line 261 of file collinear-swimmer-internal-dynamics-configuration.py.
tf
collinear-swimmer-internal-dynamics-configuration.tf = np.double(options.u_tf)
Definition at line 262 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by GSDUtil.readParameters().
R_avg
collinear-swimmer-internal-dynamics-configuration.R_avg = np.double(options.u_R_avg)
Definition at line 264 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by GSDUtil.readSystemSpecifics().
Z_height
collinear-swimmer-internal-dynamics-configuration.Z_height = np.double(options.u_Z_height)
Definition at line 265 of file collinear-swimmer-internal-dynamics-configuration.py.
phase_angle
collinear-swimmer-internal-dynamics-configuration.phase_angle = np.double(options.u_phase_angle)
Definition at line 266 of file collinear-swimmer-internal-dynamics-configuration.py.
U0
collinear-swimmer-internal-dynamics-configuration.U0 = np.double(options.u_U0)
Definition at line 267 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by GSDUtil.readSystemSpecifics().
omega
collinear-swimmer-internal-dynamics-configuration.omega = np.double(options.u_omega)
Definition at line 268 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by GSDUtil.readSystemSpecifics().
image_system
collinear-swimmer-internal-dynamics-configuration.image_system = int(options.u_image_system)
Definition at line 271 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by GSDUtil.readParameters(), and SystemData.setImageSystem().
M
collinear-swimmer-internal-dynamics-configuration.M = int(options.u_number_bodies)
Definition at line 273 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by gsd_write_chunk(), and GSDUtil.readParameters().
N
int collinear-swimmer-internal-dynamics-configuration.N = num_particles_per_body * M
Definition at line 274 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by gsd_write_chunk(), GSDUtil.readHeader(), GSDUtil.writeHeader(), and GSDUtil.writeParticles().
tau
tuple collinear-swimmer-internal-dynamics-configuration.tau = (2.0 * np.pi) / omega
Definition at line 276 of file collinear-swimmer-internal-dynamics-configuration.py.
Referenced by GSDUtil.readParameters().
epsilon
tuple collinear-swimmer-internal-dynamics-configuration.epsilon = (U0 / omega) / R_avg
Definition at line 277 of file collinear-swimmer-internal-dynamics-configuration.py.
gsd_class
def collinear-swimmer-internal-dynamics-configuration.gsd_class
Initial value:
 =  initializeGSD(gsd_path,
                               N, M,
                               dt, ti, tf, tau,
                               num_steps_output,
                               fluid_density, particle_density,
                               wca_epsilon, wca_sigma,
                               image_system)
Definition at line 279 of file collinear-swimmer-internal-dynamics-configuration.py.