bodies-in-potential-flow: collinear-swimmer-wall-configuration Namespace Reference
collinear-swimmer-wall-configuration Namespace Reference
Functions
def initializeGSD ()
def setInitialConditions ()
def setSystemData ()
Variables
parser = OptionParser()
dest
help
metavar
float t = 0.0
float tf = 25.0
int num_steps_output = 10000
float fluid_density = 1.0
float particle_density = 1.0
float wca_epsilon = 0.0
float wca_sigma = 0.0
int n = 6
list types = ['constrained', 'locater']
list typeid = [0, 1, 0, 0, 1, 0]
options
remainder
gsd_path = str(options.u_gsd_path)
dt = np.double(options.u_dt)
R_avg = np.double(options.u_R_avg)
Z_height = np.double(options.u_Z_height)
phase_angle = np.double(options.u_phase_angle)
U0 = np.double(options.u_U0)
omega = np.double(options.u_omega)
tuple epsilon = (U0 / omega) / R_avg
tuple tau = (2.0 * np.pi) / omega
Function Documentation
initializeGSD()
def collinear-swimmer-wall-configuration.initializeGSD ()
Definition at line 69 of file collinear-swimmer-wall-configuration.py.
def initializeGSD():
    global gsd_class
    gsd_class = GSDUtil(gsd_path, create_gsd=True)
    gsd_class.setLogParameters(dt, t, tf, tau, num_steps_output,
                               fluid_density, particle_density, wca_epsilon, wca_sigma)
    gsd_class.setParticleParameters(n, types, typeid)
References initializeGSD().
Referenced by initializeGSD().
setInitialConditions()
def collinear-swimmer-wall-configuration.setInitialConditions ()
Definition at line 78 of file collinear-swimmer-wall-configuration.py.
def setInitialConditions():
    # orientation
    quat = np.zeros((n, 4), dtype=np.double)
    # unit quaternion with rotation angle = zero
    no_rotation_quat = np.array([1.0, 0.0, 0.0, 0.0], dtype=np.double)
    quat = np.tile(no_rotation_quat, (n, 1))
    # position
    pos = np.zeros((n, 3), dtype=np.double)
    pos[0] = [R_avg, 0.0, Z_height]
    pos[1] = [0.0, 0.0, Z_height]
    pos[2] = [- R_avg + (U0 / omega) * np.sin(phase_angle), 0.0, Z_height]
    pos[3] = [R_avg, 0.0, -Z_height]
    pos[4] = [0.0, 0.0, -Z_height]
    pos[5] = [- R_avg + (U0 / omega) * np.sin(phase_angle), 0.0, -Z_height]
    # velocity NOTE[epic=Assumptions]: must be calculated in simulation system (C++)
    vel = np.zeros_like(pos, dtype=np.double)
    # acceleration NOTE[epic=Assumptions]: must be calculated in simulation system (C++)
    acc = np.zeros_like(pos, dtype=np.double)
    # output data
    gsd_class.setKinematics(quat, pos, vel, acc)
References setInitialConditions().
Referenced by setInitialConditions().
setSystemData()
def collinear-swimmer-wall-configuration.setSystemData ()
Definition at line 105 of file collinear-swimmer-wall-configuration.py.
def setSystemData():
    # get snapshot
    snapshot = gsd_class.snapshot
    # convert data to GSD expected type
    l_R_avg = np.array([R_avg], dtype=np.double)
    l_Z_height = np.array([Z_height], dtype=np.double)
    l_U0 = np.array([U0], dtype=np.double)
    l_omega = np.array([omega], dtype=np.double)
    l_phase_angle = np.array([phase_angle], dtype=np.double)
    l_U_swim = np.zeros(6, dtype=np.double)
    l_A_swim = np.zeros(6, dtype=np.double)
    # output data
    snapshot.log['swimmer/R_avg'] = l_R_avg
    snapshot.log['swimmer/Z_height'] = l_Z_height
    snapshot.log['swimmer/U0'] = l_U0
    snapshot.log['swimmer/omega'] = l_omega
    snapshot.log['swimmer/phase_shift'] = l_phase_angle
    snapshot.log['swimmer/U_swim'] = l_U_swim
    snapshot.log['swimmer/A_swim'] = l_A_swim
# !SECTION: (GSD Creation)
# SECTION: For use when being called from command line
References setSystemData().
Referenced by setSystemData().
Variable Documentation
parser
collinear-swimmer-wall-configuration.parser = OptionParser()
Definition at line 18 of file collinear-swimmer-wall-configuration.py.
dest
collinear-swimmer-wall-configuration.dest
Definition at line 19 of file collinear-swimmer-wall-configuration.py.
help
collinear-swimmer-wall-configuration.help
Definition at line 20 of file collinear-swimmer-wall-configuration.py.
metavar
collinear-swimmer-wall-configuration.metavar
Definition at line 21 of file collinear-swimmer-wall-configuration.py.
t
float collinear-swimmer-wall-configuration.t = 0.0
Definition at line 47 of file collinear-swimmer-wall-configuration.py.
Referenced by lerp(), and GSDUtil.readParameters().
tf
float collinear-swimmer-wall-configuration.tf = 25.0
Definition at line 48 of file collinear-swimmer-wall-configuration.py.
Referenced by GSDUtil.readParameters().
num_steps_output
int collinear-swimmer-wall-configuration.num_steps_output = 10000
Definition at line 49 of file collinear-swimmer-wall-configuration.py.
Referenced by GSDUtil.readParameters(), and systemData.setNumStepsOutput().
fluid_density
float collinear-swimmer-wall-configuration.fluid_density = 1.0
Definition at line 52 of file collinear-swimmer-wall-configuration.py.
Referenced by GSDUtil.readParameters(), and systemData.setFluidDensity().
particle_density
float collinear-swimmer-wall-configuration.particle_density = 1.0
Definition at line 53 of file collinear-swimmer-wall-configuration.py.
Referenced by GSDUtil.readParameters(), and systemData.setParticleDensity().
wca_epsilon
float collinear-swimmer-wall-configuration.wca_epsilon = 0.0
Definition at line 56 of file collinear-swimmer-wall-configuration.py.
Referenced by GSDUtil.readParameters(), and systemData.setWcaEpsilon().
wca_sigma
float collinear-swimmer-wall-configuration.wca_sigma = 0.0
Definition at line 57 of file collinear-swimmer-wall-configuration.py.
Referenced by GSDUtil.readParameters(), and systemData.setWcaSigma().
n
int collinear-swimmer-wall-configuration.n = 6
Definition at line 60 of file collinear-swimmer-wall-configuration.py.
Referenced by display_matrix(), mat_norminf(), reflect(), and vec_norminf().
types
list collinear-swimmer-wall-configuration.types = ['constrained', 'locater']
Definition at line 61 of file collinear-swimmer-wall-configuration.py.
Referenced by GSDUtil.readParameters().
typeid
list collinear-swimmer-wall-configuration.typeid = [0, 1, 0, 0, 1, 0]
Definition at line 62 of file collinear-swimmer-wall-configuration.py.
options
collinear-swimmer-wall-configuration.options
Definition at line 137 of file collinear-swimmer-wall-configuration.py.
remainder
collinear-swimmer-wall-configuration.remainder
Definition at line 137 of file collinear-swimmer-wall-configuration.py.
gsd_path
collinear-swimmer-wall-configuration.gsd_path = str(options.u_gsd_path)
Definition at line 138 of file collinear-swimmer-wall-configuration.py.
dt
collinear-swimmer-wall-configuration.dt = np.double(options.u_dt)
Definition at line 139 of file collinear-swimmer-wall-configuration.py.
Referenced by GSDUtil.readParameters(), and GSDUtil.writeParameters().
R_avg
collinear-swimmer-wall-configuration.R_avg = np.double(options.u_R_avg)
Definition at line 140 of file collinear-swimmer-wall-configuration.py.
Referenced by GSDUtil.readSystemSpecifics().
Z_height
collinear-swimmer-wall-configuration.Z_height = np.double(options.u_Z_height)
Definition at line 141 of file collinear-swimmer-wall-configuration.py.
phase_angle
collinear-swimmer-wall-configuration.phase_angle = np.double(options.u_phase_angle)
Definition at line 142 of file collinear-swimmer-wall-configuration.py.
U0
collinear-swimmer-wall-configuration.U0 = np.double(options.u_U0)
Definition at line 143 of file collinear-swimmer-wall-configuration.py.
Referenced by GSDUtil.readSystemSpecifics().
omega
collinear-swimmer-wall-configuration.omega = np.double(options.u_omega)
Definition at line 144 of file collinear-swimmer-wall-configuration.py.
Referenced by GSDUtil.readSystemSpecifics().
epsilon
tuple collinear-swimmer-wall-configuration.epsilon = (U0 / omega) / R_avg
Definition at line 146 of file collinear-swimmer-wall-configuration.py.
tau
tuple collinear-swimmer-wall-configuration.tau = (2.0 * np.pi) / omega
Definition at line 147 of file collinear-swimmer-wall-configuration.py.
Referenced by GSDUtil.readParameters().