Bodies in Potential Flow: test/TestSimulation.cpp File Reference
TestSimulation.cpp File Reference
Prototypes
TEST_CASE ("Open GSD file", "[gsd]")
TEST_CASE ("Collinear swimmer isolated: initialize system", "[Collinear-Isolated][Engine][SystemData][RungeKutta4][PotentialHydrodynamics][gsd][GSDUtil]")
TEST_CASE ("Collinear swimmer isolated: run engine", "[Collinear-Isolated][Engine][ProgressBar][SystemData][RungeKutta4][PotentialHydrodynamics]")
TEST_CASE ("Collinear swimmer wall: initialize system", "[Collinear-Wall][Engine][SystemData][RungeKutta4][PotentialHydrodynamics][gsd][GSDUtil]")
TEST_CASE ("Collinear swimmer wall: run engine", "[Collinear-Wall][Engine][ProgressBar][SystemData][RungeKutta4][PotentialHydrodynamics]")
#include <Engine.hpp>
#include <SystemData.hpp>
#include <catch2/catch.hpp>
#include <gsd.h>
#include <spdlog/fmt/ostr.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/spdlog.h>
#include <fstream>
#include <memory>
#include <string>
Macros
#define CATCH_CONFIG_CONSOLE_WIDTH 300
Macro Definition Documentation
CATCH_CONFIG_CONSOLE_WIDTH
#define CATCH_CONFIG_CONSOLE_WIDTH 300
Definition at line 10 of file TestSimulation.cpp.
Function Documentation
TEST_CASE() [1/5]
TEST_CASE ("Open GSD file" , "" [gsd])
Definition at line 22 of file TestSimulation.cpp.
 {
     // I/O Parameters
     std::string inputDataFile = "input/collinear_swimmer_isolated/initial_frame_dt1e-2.gsd";
     // GSD loading parameters
     std::shared_ptr<gsd_handle> handle{new gsd_handle};
     int                         return_val{-1};
     // verify inputDataFile exists
     std::ifstream inputDataStream(inputDataFile);
     REQUIRE(inputDataStream);
     // verify gsd file can be opened correctly
     REQUIRE_NOTHROW(return_val = gsd_open(handle.get(), inputDataFile.c_str(), GSD_OPEN_READONLY));
     INFO("GSD open return value: " << return_val);
     REQUIRE(return_val == 0);
 }
References gsd_open(), and GSD_OPEN_READONLY.
TEST_CASE() [2/5]
TEST_CASE ("Collinear swimmer isolated: initialize system" , "" [Collinear-Isolated][Engine][SystemData][RungeKutta4][PotentialHydrodynamics][gsd][GSDUtil])
Definition at line 41 of file TestSimulation.cpp.
                                      : initialize system",
           "[Collinear-Isolated][Engine][SystemData][RungeKutta4][PotentialHydrodynamics][gsd][GSDUtil]")
 {
     // close all previous loggers
     spdlog::drop_all();
     // I/O Parameters
     std::string inputDataFile = "input/collinear_swimmer_isolated/initial_frame_dt1e-2.gsd";
     std::string outputDir     = "output-collinear-isolated-SystemData-init";
     // simulation classes
     std::shared_ptr<SystemData> system;
     std::shared_ptr<Engine>     eng;
     // Construct and initialize simulationSystem class
     REQUIRE_NOTHROW(system = std::make_shared<SystemData>(inputDataFile, outputDir));
     REQUIRE_NOTHROW(system->initializeData());
     // Verify data was correctly parsed from GSD to simulation
     REQUIRE(system->gSDParsed());
     // Construct simulation Engine
     REQUIRE_NOTHROW(eng = std::make_shared<Engine>(system));
 }
References SystemData::gSDParsed(), and SystemData::initializeData().
TEST_CASE() [3/5]
TEST_CASE ("Collinear swimmer isolated: run engine" , "" [Collinear-Isolated][Engine][ProgressBar][SystemData][RungeKutta4][PotentialHydrodynamics])
Definition at line 66 of file TestSimulation.cpp.
                                      : run engine",
           "[Collinear-Isolated][Engine][ProgressBar][SystemData][RungeKutta4][PotentialHydrodynamics]")
 {
     // close all previous loggers
     spdlog::drop_all();
     // I/O Parameters
     std::string inputDataFile = "input/collinear_swimmer_isolated/initial_frame_dt1e-2.gsd";
     std::string outputDir     = "output-collinear-isolated-Engine-run";
     // simulation classes
     std::shared_ptr<SystemData> system;
     std::shared_ptr<Engine>     eng;
     // Construct and initialize simulation classes
     REQUIRE_NOTHROW(system = std::make_shared<SystemData>(inputDataFile, outputDir));
     REQUIRE_NOTHROW(system->initializeData());
     REQUIRE_NOTHROW(eng = std::make_shared<Engine>(system));
     // Verify simulation can run without error
     REQUIRE_NOTHROW(eng->run());
 }
References SystemData::initializeData(), and Engine::run().
TEST_CASE() [4/5]
TEST_CASE ("Collinear swimmer wall: initialize system" , "" [Collinear-Wall][Engine][SystemData][RungeKutta4][PotentialHydrodynamics][gsd][GSDUtil])
Definition at line 89 of file TestSimulation.cpp.
                                  : initialize system",
           "[Collinear-Wall][Engine][SystemData][RungeKutta4][PotentialHydrodynamics][gsd][GSDUtil]")
 {
     // close all previous loggers
     spdlog::drop_all();
     // I/O Parameters
     std::string inputDataFile = "input/collinear_swimmer_wall/initial_frame_dt1e-1_Z-height6.gsd";
     std::string outputDir     = "output-collinear-wall-SystemData-init";
     // simulation classes
     std::shared_ptr<SystemData> system;
     std::shared_ptr<Engine>     eng;
     // Construct and initialize simulationSystem class
     REQUIRE_NOTHROW(system = std::make_shared<SystemData>(inputDataFile, outputDir));
     REQUIRE_NOTHROW(system->initializeData());
     // Verify data was correctly parsed from GSD to simulation
     REQUIRE(system->gSDParsed());
     // Construct simulation Engine
     REQUIRE_NOTHROW(eng = std::make_shared<Engine>(system));
 }
References SystemData::gSDParsed(), and SystemData::initializeData().
TEST_CASE() [5/5]
TEST_CASE ("Collinear swimmer wall: run engine" , "" [Collinear-Wall][Engine][ProgressBar][SystemData][RungeKutta4][PotentialHydrodynamics])
Definition at line 114 of file TestSimulation.cpp.
                                  : run engine",
           "[Collinear-Wall][Engine][ProgressBar][SystemData][RungeKutta4][PotentialHydrodynamics]")
 {
     // close all previous loggers
     spdlog::drop_all();
     // I/O Parameters
     std::string inputDataFile = "input/collinear_swimmer_wall/initial_frame_dt1e-1_Z-height6.gsd";
     std::string outputDir     = "output-collinear-wall-Engine-run";
     // simulation classes
     std::shared_ptr<SystemData> system;
     std::shared_ptr<Engine>     eng;
     // Construct and initialize simulation classes
     REQUIRE_NOTHROW(system = std::make_shared<SystemData>(inputDataFile, outputDir));
     REQUIRE_NOTHROW(system->initializeData());
     REQUIRE_NOTHROW(eng = std::make_shared<Engine>(system));
     // Verify simulation can run without error
     REQUIRE_NOTHROW(eng->run());
 }
References SystemData::initializeData(), and Engine::run().