Bodied in Potential Flow: src/data_io/gsd.h File Reference
gsd.h File Reference
Declare GSD data types and C API.
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
Classes
struct gsd_header
struct gsd_index_entry
struct gsd_name_id_pair
struct gsd_name_id_map
struct gsd_index_buffer
struct gsd_byte_buffer
struct gsd_name_buffer
struct gsd_handle
Enumerations
enum gsd_type {
GSD_TYPE_UINT8 = 1 , GSD_TYPE_UINT16 , GSD_TYPE_UINT32 , GSD_TYPE_UINT64 ,
GSD_TYPE_INT8 , GSD_TYPE_INT16 , GSD_TYPE_INT32 , GSD_TYPE_INT64 ,
GSD_TYPE_FLOAT , GSD_TYPE_DOUBLE
}
Identifiers for the gsd data chunk element types.
enum gsd_open_flag { GSD_OPEN_READWRITE = 1 , GSD_OPEN_READONLY , GSD_OPEN_APPEND }
Flag for GSD file open options.
enum gsd_error {
GSD_SUCCESS = 0 , GSD_ERROR_IO = -1 , GSD_ERROR_INVALID_ARGUMENT = -2 , GSD_ERROR_NOT_A_GSD_FILE = -3 ,
GSD_ERROR_INVALID_GSD_FILE_VERSION = -4 , GSD_ERROR_FILE_CORRUPT = -5 , GSD_ERROR_MEMORY_ALLOCATION_FAILED = -6 , GSD_ERROR_NAMELIST_FULL = -7 ,
GSD_ERROR_FILE_MUST_BE_WRITABLE = -8 , GSD_ERROR_FILE_MUST_BE_READABLE = -9
}
Error return values.
enum { GSD_NAME_SIZE = 64 }
enum { GSD_RESERVED_BYTES = 80 }
Functions
uint32_t gsd_make_version (unsigned int major, unsigned int minor)
int gsd_create (const char *fname, const char *application, const char *schema, uint32_t schema_version)
int gsd_create_and_open (struct gsd_handle *handle, const char *fname, const char *application, const char *schema, uint32_t schema_version, enum gsd_open_flag flags, int exclusive_create)
int gsd_open (struct gsd_handle *handle, const char *fname, enum gsd_open_flag flags)
int gsd_truncate (struct gsd_handle *handle)
int gsd_close (struct gsd_handle *handle)
int gsd_end_frame (struct gsd_handle *handle)
int gsd_write_chunk (struct gsd_handle *handle, const char *name, enum gsd_type type, uint64_t N, uint32_t M, uint8_t flags, const void *data)
const struct gsd_index_entry * gsd_find_chunk (struct gsd_handle *handle, uint64_t frame, const char *name)
int gsd_read_chunk (struct gsd_handle *handle, void *data, const struct gsd_index_entry *chunk)
uint64_t gsd_get_nframes (struct gsd_handle *handle)
size_t gsd_sizeof_type (enum gsd_type type)
const char * gsd_find_matching_chunk_name (struct gsd_handle *handle, const char *match, const char *prev)
int gsd_upgrade (struct gsd_handle *handle)
Detailed Description
Declare GSD data types and C API.
Definition in file gsd.h.
Enumeration Type Documentation
gsd_type
enum gsd_type
Identifiers for the gsd data chunk element types.
Enumerator
GSD_TYPE_UINT8
Unsigned 8-bit integer.
GSD_TYPE_UINT16
Unsigned 16-bit integer.
GSD_TYPE_UINT32
Unsigned 32-bit integer.
GSD_TYPE_UINT64
Unsigned 53-bit integer.
GSD_TYPE_INT8
Signed 8-bit integer.
GSD_TYPE_INT16
Signed 16-bit integer.
GSD_TYPE_INT32
Signed 32-bit integer.
GSD_TYPE_INT64
Signed 64-bit integer.
GSD_TYPE_FLOAT
32-bit floating point number.
GSD_TYPE_DOUBLE
64-bit floating point number.
Definition at line 22 of file gsd.h.
    {
        GSD_TYPE_UINT8 = 1,
        GSD_TYPE_UINT16,
        GSD_TYPE_UINT32,
        GSD_TYPE_UINT64,
        GSD_TYPE_INT8,
        GSD_TYPE_INT16,
        GSD_TYPE_INT32,
        GSD_TYPE_INT64,
        GSD_TYPE_FLOAT,
        GSD_TYPE_DOUBLE
    };
gsd_open_flag
enum gsd_open_flag
Flag for GSD file open options.
Enumerator
GSD_OPEN_READWRITE
Open for both reading and writing.
GSD_OPEN_READONLY
Open only for reading.
GSD_OPEN_APPEND
Open only for writing.
Definition at line 56 of file gsd.h.
    {
        GSD_OPEN_READWRITE = 1,
        GSD_OPEN_READONLY,
        GSD_OPEN_APPEND
    };
gsd_error
enum gsd_error
Error return values.
Enumerator
GSD_SUCCESS
Success.
GSD_ERROR_IO
IO error. Check errno for details.
GSD_ERROR_INVALID_ARGUMENT
Invalid argument passed to function.
GSD_ERROR_NOT_A_GSD_FILE
The file is not a GSD file.
GSD_ERROR_INVALID_GSD_FILE_VERSION
The GSD file version cannot be read.
GSD_ERROR_FILE_CORRUPT
The GSD file is corrupt.
GSD_ERROR_MEMORY_ALLOCATION_FAILED
GSD failed to allocated memory.
GSD_ERROR_NAMELIST_FULL
The GSD file cannot store any additional unique data chunk names.
GSD_ERROR_FILE_MUST_BE_WRITABLE
This API call requires that the GSD file opened in with the mode GSD_OPEN_APPEND or GSD_OPEN_READWRITE.
GSD_ERROR_FILE_MUST_BE_READABLE
This API call requires that the GSD file opened the mode GSD_OPEN_READ or GSD_OPEN_READWRITE.
Definition at line 69 of file gsd.h.
    {
        GSD_SUCCESS = 0,
        GSD_ERROR_IO = -1,
        GSD_ERROR_INVALID_ARGUMENT = -2,
        GSD_ERROR_NOT_A_GSD_FILE = -3,
        GSD_ERROR_INVALID_GSD_FILE_VERSION = -4,
        GSD_ERROR_FILE_CORRUPT = -5,
        GSD_ERROR_MEMORY_ALLOCATION_FAILED = -6,
        GSD_ERROR_NAMELIST_FULL = -7,
        GSD_ERROR_FILE_MUST_BE_WRITABLE = -8,
        GSD_ERROR_FILE_MUST_BE_READABLE = -9,
    };
anonymous enum
anonymous enum
Enumerator
GSD_NAME_SIZE
v1 file: Size of a GSD name in memory. v2 file: The name buffer size is a multiple of GSD_NAME_SIZE.
Definition at line 106 of file gsd.h.
    {
        GSD_NAME_SIZE = 64
    };
anonymous enum
anonymous enum
Enumerator
GSD_RESERVED_BYTES
Reserved bytes in the header structure.
Definition at line 114 of file gsd.h.
    {
        GSD_RESERVED_BYTES = 80
    };
Function Documentation
gsd_make_version()
uint32_t gsd_make_version (unsigned int major, unsigned int minor)
Specify a version
Parameters
major major version
minor minor version
Returns
a packed version number aaaa.bbbb suitable for storing in a gsd file version entry.
Definition at line 1563 of file gsd.c.
    {
    return major << (sizeof(uint32_t) * 4) | minor;
    }
Referenced by gsd_append_name(), gsd_find_chunk(), gsd_find_matching_chunk_name(), gsd_initialize_file(), gsd_initialize_handle(), and gsd_upgrade().
gsd_create()
int gsd_create (const char * fname, const char * application, const char * schema, uint32_t schema_version)
Create a GSD file
Parameters
fname File name.
application Generating application name (truncated to 63 chars).
schema Schema name for data to be written in this GSD file (truncated to 63 chars).
schema_version Version of the scheme data to be written (make with gsd_make_version()).
Postcondition
Create an empty gsd file in a file of the given name. Overwrite any existing file at that location.
The generated gsd file is not opened. Call gsd_open() to open it for writing.
Returns
GSD_SUCCESS (0) on success. Negative value on failure:
GSD_ERROR_IO: IO error (check errno).
Definition at line 1568 of file gsd.c.
    {
    int extra_flags = 0;
#ifdef _WIN32
    extra_flags = _O_BINARY;
#endif
    // create the file
    int fd = open(fname,
                  O_RDWR | O_CREAT | O_TRUNC | extra_flags,
                  S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP);
    int retval = gsd_initialize_file(fd, application, schema, schema_version);
    close(fd);
    return retval;
    }
References gsd_initialize_file().
gsd_create_and_open()
int gsd_create_and_open (struct gsd_handle * handle, const char * fname, const char * application, const char * schema, uint32_t schema_version, enum gsd_open_flag flags, int exclusive_create)
Create and open a GSD file
Parameters
handle Handle to open.
fname File name.
application Generating application name (truncated to 63 chars).
schema Schema name for data to be written in this GSD file (truncated to 63 chars).
schema_version Version of the scheme data to be written (make with gsd_make_version()).
flags Either GSD_OPEN_READWRITE, or GSD_OPEN_APPEND.
exclusive_create Set to non-zero to force exclusive creation of the file.
Postcondition
Create an empty gsd file with the given name. Overwrite any existing file at that location.
Open the generated gsd file in handle.
The file descriptor is closed if there when an error opening the file.
Returns
GSD_SUCCESS (0) on success. Negative value on failure:
GSD_ERROR_IO: IO error (check errno).
GSD_ERROR_NOT_A_GSD_FILE: Not a GSD file.
GSD_ERROR_INVALID_GSD_FILE_VERSION: Invalid GSD file version.
GSD_ERROR_FILE_CORRUPT: Corrupt file.
GSD_ERROR_MEMORY_ALLOCATION_FAILED: Unable to allocate memory.
Definition at line 1587 of file gsd.c.
    {
    // zero the handle
    gsd_util_zero_memory(handle, sizeof(struct gsd_handle));
    int extra_flags = 0;
#ifdef _WIN32
    extra_flags = _O_BINARY;
#endif
    // set the open flags in the handle
    if (flags == GSD_OPEN_READWRITE)
        {
        handle->open_flags = GSD_OPEN_READWRITE;
        }
    else if (flags == GSD_OPEN_READONLY)
        {
        return GSD_ERROR_FILE_MUST_BE_WRITABLE;
        }
    else if (flags == GSD_OPEN_APPEND)
        {
        handle->open_flags = GSD_OPEN_APPEND;
        }
    // set the exclusive create bit
    if (exclusive_create)
        {
        extra_flags |= O_EXCL;
        }
    // create the file
    handle->fd = open(fname,
                      O_RDWR | O_CREAT | O_TRUNC | extra_flags,
                      S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP);
    int retval = gsd_initialize_file(handle->fd, application, schema, schema_version);
    if (retval != 0)
        {
        close(handle->fd);
        return retval;
        }
    retval = gsd_initialize_handle(handle);
    if (retval != 0)
        {
        close(handle->fd);
        }
    return retval;
    }
References gsd_handle::fd, gsd_index_entry::flags, GSD_ERROR_FILE_MUST_BE_WRITABLE, gsd_initialize_file(), gsd_initialize_handle(), GSD_OPEN_APPEND, GSD_OPEN_READONLY, GSD_OPEN_READWRITE, gsd_util_zero_memory(), and gsd_handle::open_flags.
gsd_open()
int gsd_open (struct gsd_handle * handle, const char * fname, enum gsd_open_flag flags)
Open a GSD file
Parameters
handle Handle to open.
fname File name to open.
flags Either GSD_OPEN_READWRITE, GSD_OPEN_READONLY, or GSD_OPEN_APPEND.
Precondition
The file name fname is a GSD file.
Postcondition
Open a GSD file and populates the handle for use by API calls.
The file descriptor is closed if there is an error opening the file.
Returns
GSD_SUCCESS (0) on success. Negative value on failure:
GSD_ERROR_IO: IO error (check errno).
GSD_ERROR_NOT_A_GSD_FILE: Not a GSD file.
GSD_ERROR_INVALID_GSD_FILE_VERSION: Invalid GSD file version.
GSD_ERROR_FILE_CORRUPT: Corrupt file.
GSD_ERROR_MEMORY_ALLOCATION_FAILED: Unable to allocate memory.
Definition at line 1642 of file gsd.c.
    {
    // zero the handle
    gsd_util_zero_memory(handle, sizeof(struct gsd_handle));
    int extra_flags = 0;
#ifdef _WIN32
    extra_flags = _O_BINARY;
#endif
    // open the file
    if (flags == GSD_OPEN_READWRITE)
        {
        handle->fd = open(fname, O_RDWR | extra_flags);
        handle->open_flags = GSD_OPEN_READWRITE;
        }
    else if (flags == GSD_OPEN_READONLY)
        {
        handle->fd = open(fname, O_RDONLY | extra_flags);
        handle->open_flags = GSD_OPEN_READONLY;
        }
    else if (flags == GSD_OPEN_APPEND)
        {
        handle->fd = open(fname, O_RDWR | extra_flags);
        handle->open_flags = GSD_OPEN_APPEND;
        }
    int retval = gsd_initialize_handle(handle);
    if (retval != 0)
        {
        close(handle->fd);
        }
    return retval;
    }
References gsd_handle::fd, gsd_index_entry::flags, gsd_initialize_handle(), GSD_OPEN_APPEND, GSD_OPEN_READONLY, GSD_OPEN_READWRITE, gsd_util_zero_memory(), and gsd_handle::open_flags.
Referenced by GSDUtil::GSDUtil().
gsd_truncate()
int gsd_truncate (struct gsd_handle * handle)
Truncate a GSD file
Parameters
handle Open GSD file to truncate.
After truncating, a file will have no frames and no data chunks. The file size will be that of a newly created gsd file. The application, schema, and schema version metadata will be kept. Truncate does not close and reopen the file, so it is suitable for writing restart files on Lustre file systems without any metadata access.
Returns
GSD_SUCCESS (0) on success. Negative value on failure:
GSD_ERROR_IO: IO error (check errno).
GSD_ERROR_NOT_A_GSD_FILE: Not a GSD file.
GSD_ERROR_INVALID_GSD_FILE_VERSION: Invalid GSD file version.
GSD_ERROR_FILE_CORRUPT: Corrupt file.
GSD_ERROR_MEMORY_ALLOCATION_FAILED: Unable to allocate memory.
Definition at line 1677 of file gsd.c.
    {
    if (handle == NULL)
        {
        return GSD_ERROR_INVALID_ARGUMENT;
        }
    if (handle->open_flags == GSD_OPEN_READONLY)
        {
        return GSD_ERROR_FILE_MUST_BE_WRITABLE;
        }
    int retval = 0;
    // deallocate indices
    if (handle->frame_names.data.reserved > 0)
        {
        retval = gsd_byte_buffer_free(&handle->frame_names.data);
        if (retval != GSD_SUCCESS)
            {
            return retval;
            }
        }
    if (handle->file_names.data.reserved > 0)
        {
        retval = gsd_byte_buffer_free(&handle->file_names.data);
        if (retval != GSD_SUCCESS)
            {
            return retval;
            }
        }
    retval = gsd_name_id_map_free(&handle->name_map);
    if (retval != GSD_SUCCESS)
        {
        return retval;
        }
    retval = gsd_index_buffer_free(&handle->file_index);
    if (retval != GSD_SUCCESS)
        {
        return retval;
        }
    if (handle->frame_index.reserved > 0)
        {
        retval = gsd_index_buffer_free(&handle->frame_index);
        if (retval != GSD_SUCCESS)
            {
            return retval;
            }
        }
    if (handle->buffer_index.reserved > 0)
        {
        retval = gsd_index_buffer_free(&handle->buffer_index);
        if (retval != GSD_SUCCESS)
            {
            return retval;
            }
        }
    if (handle->write_buffer.reserved > 0)
        {
        retval = gsd_byte_buffer_free(&handle->write_buffer);
        if (retval != GSD_SUCCESS)
            {
            return retval;
            }
        }
    // keep a copy of the old header
    struct gsd_header old_header = handle->header;
    retval = gsd_initialize_file(handle->fd,
                                 old_header.application,
                                 old_header.schema,
                                 old_header.schema_version);
    if (retval != GSD_SUCCESS)
        {
        return retval;
        }
    return gsd_initialize_handle(handle);
    }
References gsd_header::application, gsd_handle::buffer_index, gsd_name_buffer::data, gsd_handle::fd, gsd_handle::file_index, gsd_handle::file_names, gsd_handle::frame_index, gsd_handle::frame_names, gsd_byte_buffer_free(), GSD_ERROR_FILE_MUST_BE_WRITABLE, GSD_ERROR_INVALID_ARGUMENT, gsd_index_buffer_free(), gsd_initialize_file(), gsd_initialize_handle(), gsd_name_id_map_free(), GSD_OPEN_READONLY, GSD_SUCCESS, gsd_handle::header, gsd_handle::name_map, gsd_handle::open_flags, gsd_index_buffer::reserved, gsd_byte_buffer::reserved, gsd_header::schema, gsd_header::schema_version, and gsd_handle::write_buffer.
Referenced by GSDUtil::truncateGSD().
gsd_close()
int gsd_close (struct gsd_handle * handle)
Close a GSD file
Parameters
handle GSD file to close.
Precondition
handle was opened by gsd_open().
gsd_end_frame() has been called since the last call to gsd_write_chunk().
Postcondition
The file is closed.
handle is freed and can no longer be used.
Warning
Ensure that all gsd_write_chunk() calls are committed with gsd_end_frame() before closing the file.
Returns
GSD_SUCCESS (0) on success. Negative value on failure:
GSD_ERROR_IO: IO error (check errno).
GSD_ERROR_INVALID_ARGUMENT: handle is NULL.
Definition at line 1763 of file gsd.c.
    {
    if (handle == NULL)
        {
        return GSD_ERROR_INVALID_ARGUMENT;
        }
    // save the fd so we can use it after freeing the handle
    int fd = handle->fd;
    int retval = gsd_index_buffer_free(&handle->file_index);
    if (retval != GSD_SUCCESS)
        {
        return retval;
        }
    if (handle->frame_index.reserved > 0)
        {
        retval = gsd_index_buffer_free(&handle->frame_index);
        if (retval != GSD_SUCCESS)
            {
            return retval;
            }
        }
    if (handle->buffer_index.reserved > 0)
        {
        retval = gsd_index_buffer_free(&handle->buffer_index);
        if (retval != GSD_SUCCESS)
            {
            return retval;
            }
        }
    if (handle->write_buffer.reserved > 0)
        {
        retval = gsd_byte_buffer_free(&handle->write_buffer);
        if (retval != GSD_SUCCESS)
            {
            return retval;
            }
        }
    retval = gsd_name_id_map_free(&handle->name_map);
    if (retval != GSD_SUCCESS)
        {
        return retval;
        }
    if (handle->frame_names.data.reserved > 0)
        {
        handle->frame_names.n_names = 0;
        retval = gsd_byte_buffer_free(&handle->frame_names.data);
        if (retval != GSD_SUCCESS)
            {
            return retval;
            }
        }
    if (handle->file_names.data.reserved > 0)
        {
        handle->file_names.n_names = 0;
        retval = gsd_byte_buffer_free(&handle->file_names.data);
        if (retval != GSD_SUCCESS)
            {
            return retval;
            }
        }
    // close the file
    retval = close(fd);
    if (retval != 0)
        {
        return GSD_ERROR_IO;
        }
    return GSD_SUCCESS;
    }
References gsd_handle::buffer_index, gsd_name_buffer::data, gsd_handle::fd, gsd_handle::file_index, gsd_handle::file_names, gsd_handle::frame_index, gsd_handle::frame_names, gsd_byte_buffer_free(), GSD_ERROR_INVALID_ARGUMENT, GSD_ERROR_IO, gsd_index_buffer_free(), gsd_name_id_map_free(), GSD_SUCCESS, gsd_name_buffer::n_names, gsd_handle::name_map, gsd_index_buffer::reserved, gsd_byte_buffer::reserved, and gsd_handle::write_buffer.
Referenced by systemData::~systemData().
gsd_end_frame()
int gsd_end_frame (struct gsd_handle * handle)
Commit the current frame and increment the frame counter.
Parameters
handle Handle to an open GSD file
Precondition
handle was opened by gsd_open().
gsd_write_chunk() has been called at least once since the last call to gsd_end_frame().
Postcondition
The current frame counter is increased by 1 and cached indexes are written to disk.
Returns
GSD_SUCCESS (0) on success. Negative value on failure:
GSD_ERROR_IO: IO error (check errno).
GSD_ERROR_INVALID_ARGUMENT: handle is NULL.
GSD_ERROR_FILE_MUST_BE_WRITABLE: The file was opened read-only.
GSD_ERROR_MEMORY_ALLOCATION_FAILED: Unable to allocate memory.
Definition at line 1842 of file gsd.c.
    {
    if (handle == NULL)
        {
        return GSD_ERROR_INVALID_ARGUMENT;
        }
    if (handle->open_flags == GSD_OPEN_READONLY)
        {
        return GSD_ERROR_FILE_MUST_BE_WRITABLE;
        }
    // increment the frame counter
    handle->cur_frame++;
    // flush the namelist buffer
    int retval = gsd_flush_name_buffer(handle);
    if (retval != GSD_SUCCESS)
        {
        return retval;
        }
    // flush the write buffer
    retval = gsd_flush_write_buffer(handle);
    if (retval != GSD_SUCCESS)
        {
        return retval;
        }
    // write the frame index to the file
    if (handle->frame_index.size > 0)
        {
        // ensure there is enough space in the index
        if ((handle->file_index.size + handle->frame_index.size) > handle->file_index.reserved)
            {
            gsd_expand_file_index(handle, handle->file_index.size + handle->frame_index.size);
            }
        // sort the index before writing
        retval = gsd_index_buffer_sort(&handle->frame_index);
        if (retval != 0)
            {
            return retval;
            }
        // write the frame index entries to the file
        int64_t write_pos = handle->header.index_location
                            + sizeof(struct gsd_index_entry) * handle->file_index.size;
        size_t bytes_to_write = sizeof(struct gsd_index_entry) * handle->frame_index.size;
        ssize_t bytes_written
            = gsd_io_pwrite_retry(handle->fd, handle->frame_index.data, bytes_to_write, write_pos);
        if (bytes_written == -1 || bytes_written != bytes_to_write)
            {
            return GSD_ERROR_IO;
            }
#if !GSD_USE_MMAP
        // add the entries to the file index
        memcpy(handle->file_index.data + handle->file_index.size,
               handle->frame_index.data,
               sizeof(struct gsd_index_entry) * handle->frame_index.size);
#endif
        // update size of file index
        handle->file_index.size += handle->frame_index.size;
        // clear the frame index
        handle->frame_index.size = 0;
        }
    return GSD_SUCCESS;
    }
References gsd_handle::cur_frame, gsd_index_buffer::data, gsd_handle::fd, gsd_handle::file_index, gsd_handle::frame_index, GSD_ERROR_FILE_MUST_BE_WRITABLE, GSD_ERROR_INVALID_ARGUMENT, GSD_ERROR_IO, gsd_expand_file_index(), gsd_flush_name_buffer(), gsd_flush_write_buffer(), gsd_index_buffer_sort(), gsd_io_pwrite_retry(), GSD_OPEN_READONLY, GSD_SUCCESS, gsd_handle::header, gsd_header::index_location, gsd_handle::open_flags, gsd_index_buffer::reserved, and gsd_index_buffer::size.
Referenced by GSDUtil::writeFrame().
gsd_write_chunk()
int gsd_write_chunk (struct gsd_handle * handle, const char * name, enum gsd_type type, uint64_t N, uint32_t M, uint8_t flags, const void * data)
Write a data chunk to the current frame
Parameters
handle Handle to an open GSD file.
name Name of the data chunk.
type type ID that identifies the type of data in data.
N Number of rows in the data.
M Number of columns in the data.
flags set to 0, non-zero values reserved for future use.
data Data buffer.
Precondition
handle was opened by gsd_open().
name is a unique name for data chunks in the given frame.
data is allocated and contains at least N * M * gsd_sizeof_type(type) bytes.
Postcondition
The given data chunk is written to the end of the file and its location is updated in the in-memory index.
Note
If the GSD file is version 1.0, the chunk name is truncated to 63 bytes. GSD version 2.0 files support arbitrarily long names.
N == 0 is allowed. When N is 0, data may be NULL.
Returns
GSD_SUCCESS (0) on success. Negative value on failure:
GSD_ERROR_IO: IO error (check errno).
GSD_ERROR_INVALID_ARGUMENT: handle is NULL, N == 0, M == 0, type is invalid, or flags* != 0.
GSD_ERROR_FILE_MUST_BE_WRITABLE: The file was opened read-only.
GSD_ERROR_NAMELIST_FULL: The file cannot store any additional unique chunk names.
GSD_ERROR_MEMORY_ALLOCATION_FAILED: failed to allocate memory.
Definition at line 1916 of file gsd.c.
    {
    // validate input
    if (N > 0 && data == NULL)
        {
        return GSD_ERROR_INVALID_ARGUMENT;
        }
    if (M == 0)
        {
        return GSD_ERROR_INVALID_ARGUMENT;
        }
    if (handle->open_flags == GSD_OPEN_READONLY)
        {
        return GSD_ERROR_FILE_MUST_BE_WRITABLE;
        }
    if (flags != 0)
        {
        return GSD_ERROR_INVALID_ARGUMENT;
        }
    uint16_t id = gsd_name_id_map_find(&handle->name_map, name);
    if (id == UINT16_MAX)
        {
        // not found, append to the index
        int retval = gsd_append_name(&id, handle, name);
        if (retval != GSD_SUCCESS)
            {
            return retval;
            }
        if (id == UINT16_MAX)
            {
            // this should never happen
            return GSD_ERROR_NAMELIST_FULL;
            }
        }
    struct gsd_index_entry entry;
    // populate fields in the entry's data
    gsd_util_zero_memory(&entry, sizeof(struct gsd_index_entry));
    entry.frame = handle->cur_frame;
    entry.id = id;
    entry.type = (uint8_t)type;
    entry.N = N;
    entry.M = M;
    size_t size = N * M * gsd_sizeof_type(type);
    // decide whether to write this chunk to the buffer or straight to disk
    if (size < handle->write_buffer.reserved / 2)
        {
        // flush the buffer if this entry won't fit
        if (size > (handle->write_buffer.reserved - handle->write_buffer.size))
            {
            gsd_flush_write_buffer(handle);
            }
        entry.location = handle->write_buffer.size;
        // add an entry to the buffer index
        struct gsd_index_entry* index_entry;
        int retval = gsd_index_buffer_add(&handle->buffer_index, &index_entry);
        if (retval != GSD_SUCCESS)
            {
            return retval;
            }
        *index_entry = entry;
        // add the data to the write buffer
        if (size > 0)
            {
            retval = gsd_byte_buffer_append(&handle->write_buffer, data, size);
            if (retval != GSD_SUCCESS)
                {
                return retval;
                }
            }
        }
    else
        {
        // add an entry to the frame index
        struct gsd_index_entry* index_entry;
        int retval = gsd_index_buffer_add(&handle->frame_index, &index_entry);
        if (retval != GSD_SUCCESS)
            {
            return retval;
            }
        *index_entry = entry;
        // find the location at the end of the file for the chunk
        index_entry->location = handle->file_size;
        // write the data
        ssize_t bytes_written = gsd_io_pwrite_retry(handle->fd, data, size, index_entry->location);
        if (bytes_written == -1 || bytes_written != size)
            {
            return GSD_ERROR_IO;
            }
        // update the file_size in the handle
        handle->file_size += bytes_written;
        }
    return GSD_SUCCESS;
    }
References gsd_handle::buffer_index, gsd_handle::cur_frame, gsd_handle::fd, gsd_handle::file_size, gsd_index_entry::flags, gsd_index_entry::frame, gsd_handle::frame_index, gsd_append_name(), gsd_byte_buffer_append(), GSD_ERROR_FILE_MUST_BE_WRITABLE, GSD_ERROR_INVALID_ARGUMENT, GSD_ERROR_IO, GSD_ERROR_NAMELIST_FULL, gsd_flush_write_buffer(), gsd_index_buffer_add(), gsd_io_pwrite_retry(), gsd_name_id_map_find(), GSD_OPEN_READONLY, gsd_sizeof_type(), GSD_SUCCESS, gsd_util_zero_memory(), gsd_index_entry::id, gsd_index_entry::location, gsd_index_entry::M, gsd_index_entry::N, gsd_handle::name_map, gsd_handle::open_flags, gsd_byte_buffer::reserved, gsd_byte_buffer::size, gsd_index_entry::type, and gsd_handle::write_buffer.
Referenced by GSDUtil::writeHeader(), GSDUtil::writeParameters(), and GSDUtil::writeParticles().
gsd_find_chunk()
const struct gsd_index_entry * gsd_find_chunk (struct gsd_handle * handle, uint64_t frame, const char * name)
Find a chunk in the GSD file
Parameters
handle Handle to an open GSD file
frame Frame to look for chunk
name Name of the chunk to find
Precondition
handle was opened by gsd_open() in read or readwrite mode.
The found entry contains size and type metadata and can be passed to gsd_read_chunk() to read the data.
Returns
A pointer to the found chunk, or NULL if not found.
Definition at line 2039 of file gsd.c.
    {
    if (handle == NULL)
        {
        return NULL;
        }
    if (name == NULL)
        {
        return NULL;
        }
    if (frame >= gsd_get_nframes(handle))
        {
        return NULL;
        }
    if (handle->open_flags == GSD_OPEN_APPEND)
        {
        return NULL;
        }
    // find the id for the given name
    uint16_t match_id = gsd_name_id_map_find(&handle->name_map, name);
    if (match_id == UINT16_MAX)
        {
        return NULL;
        }
    if (handle->header.gsd_version >= gsd_make_version(2, 0))
        {
        // gsd 2.0 files sort the entire index
        // binary search for the index entry
        ssize_t L = 0;
        ssize_t R = handle->file_index.size - 1;
        struct gsd_index_entry T;
        T.frame = frame;
        T.id = match_id;
        while (L <= R)
            {
            size_t m = (L + R) / 2;
            int cmp = gsd_cmp_index_entry(handle->file_index.data + m, &T);
            if (cmp == -1)
                {
                L = m + 1;
                }
            else if (cmp == 1)
                {
                R = m - 1;
                }
            else
                {
                return &(handle->file_index.data[m]);
                }
            }
        }
    else
        {
        // gsd 1.0 file: use binary search to find the frame and linear search to find the entry
        size_t L = 0;
        size_t R = handle->file_index.size;
        // progressively narrow the search window by halves
        do
            {
            size_t m = (L + R) / 2;
            if (frame < handle->file_index.data[m].frame)
                {
                R = m;
                }
            else
                {
                L = m;
                }
            } while ((R - L) > 1);
        // this finds L = the rightmost index with the desired frame
        int64_t cur_index;
        // search all index entries with the matching frame
        for (cur_index = L; (cur_index >= 0) && (handle->file_index.data[cur_index].frame == frame);
             cur_index--)
            {
            // if the frame matches, check the id
            if (match_id == handle->file_index.data[cur_index].id)
                {
                return &(handle->file_index.data[cur_index]);
                }
            }
        }
    // if we got here, we didn't find the specified chunk
    return NULL;
    }
References gsd_index_buffer::data, gsd_handle::file_index, gsd_index_entry::frame, gsd_cmp_index_entry(), gsd_get_nframes(), gsd_make_version(), gsd_name_id_map_find(), GSD_OPEN_APPEND, gsd_header::gsd_version, gsd_handle::header, gsd_index_entry::id, gsd_handle::name_map, gsd_handle::open_flags, and gsd_index_buffer::size.
Referenced by GSDUtil::readChunk().
gsd_read_chunk()
int gsd_read_chunk (struct gsd_handle * handle, void * data, const struct gsd_index_entry * chunk)
Read a chunk from the GSD file
Parameters
handle Handle to an open GSD file.
data Data buffer to read into.
chunk Chunk to read.
Precondition
handle was opened in read or readwrite mode.
chunk was found by gsd_find_chunk().
data points to an allocated buffer with at least N * M * gsd_sizeof_type(type) bytes.
Returns
GSD_SUCCESS (0) on success. Negative value on failure:
GSD_ERROR_IO: IO error (check errno).
GSD_ERROR_INVALID_ARGUMENT: handle is NULL, data is NULL, or chunk is NULL.
GSD_ERROR_FILE_MUST_BE_READABLE: The file was opened in append mode.
GSD_ERROR_FILE_CORRUPT: The GSD file is corrupt.
Definition at line 2133 of file gsd.c.
    {
    if (handle == NULL)
        {
        return GSD_ERROR_INVALID_ARGUMENT;
        }
    if (data == NULL)
        {
        return GSD_ERROR_INVALID_ARGUMENT;
        }
    if (chunk == NULL)
        {
        return GSD_ERROR_INVALID_ARGUMENT;
        }
    if (handle->open_flags == GSD_OPEN_APPEND)
        {
        return GSD_ERROR_FILE_MUST_BE_READABLE;
        }
    size_t size = chunk->N * chunk->M * gsd_sizeof_type((enum gsd_type)chunk->type);
    if (size == 0)
        {
        return GSD_ERROR_FILE_CORRUPT;
        }
    if (chunk->location == 0)
        {
        return GSD_ERROR_FILE_CORRUPT;
        }
    // validate that we don't read past the end of the file
    if ((chunk->location + size) > (uint64_t)handle->file_size)
        {
        return GSD_ERROR_FILE_CORRUPT;
        }
    ssize_t bytes_read = gsd_io_pread_retry(handle->fd, data, size, chunk->location);
    if (bytes_read == -1 || bytes_read != size)
        {
        return GSD_ERROR_IO;
        }
    return GSD_SUCCESS;
    }
References gsd_handle::fd, gsd_handle::file_size, GSD_ERROR_FILE_CORRUPT, GSD_ERROR_FILE_MUST_BE_READABLE, GSD_ERROR_INVALID_ARGUMENT, GSD_ERROR_IO, gsd_io_pread_retry(), GSD_OPEN_APPEND, gsd_sizeof_type(), GSD_SUCCESS, gsd_index_entry::location, gsd_index_entry::M, gsd_index_entry::N, gsd_handle::open_flags, and gsd_index_entry::type.
Referenced by GSDUtil::readChunk().
gsd_get_nframes()
uint64_t gsd_get_nframes (struct gsd_handle * handle)
Get the number of frames in the GSD file
Parameters
handle Handle to an open GSD file
Precondition
handle was opened by gsd_open().
Returns
The number of frames in the file, or 0 on error.
Definition at line 2029 of file gsd.c.
    {
    if (handle == NULL)
        {
        return 0;
        }
    return handle->cur_frame;
    }
References gsd_handle::cur_frame.
Referenced by gsd_find_chunk(), GSDUtil::GSDUtil(), GSDUtil::writeHeader(), and GSDUtil::writeParticles().
gsd_sizeof_type()
size_t gsd_sizeof_type (enum gsd_type type)
Query size of a GSD type ID.
Parameters
type Type ID to query.
Returns
Size of the given type in bytes, or 0 for an unknown type ID.
Definition at line 2177 of file gsd.c.
    {
    size_t val = 0;
    if (type == GSD_TYPE_UINT8)
        {
        val = sizeof(uint8_t);
        }
    else if (type == GSD_TYPE_UINT16)
        {
        val = sizeof(uint16_t);
        }
    else if (type == GSD_TYPE_UINT32)
        {
        val = sizeof(uint32_t);
        }
    else if (type == GSD_TYPE_UINT64)
        {
        val = sizeof(uint64_t);
        }
    else if (type == GSD_TYPE_INT8)
        {
        val = sizeof(int8_t);
        }
    else if (type == GSD_TYPE_INT16)
        {
        val = sizeof(int16_t);
        }
    else if (type == GSD_TYPE_INT32)
        {
        val = sizeof(int32_t);
        }
    else if (type == GSD_TYPE_INT64)
        {
        val = sizeof(int64_t);
        }
    else if (type == GSD_TYPE_FLOAT)
        {
        val = sizeof(float);
        }
    else if (type == GSD_TYPE_DOUBLE)
        {
        val = sizeof(double);
        }
    else
        {
        return 0;
        }
    return val;
    }
References GSD_TYPE_DOUBLE, GSD_TYPE_FLOAT, GSD_TYPE_INT16, GSD_TYPE_INT32, GSD_TYPE_INT64, GSD_TYPE_INT8, GSD_TYPE_UINT16, GSD_TYPE_UINT32, GSD_TYPE_UINT64, GSD_TYPE_UINT8, and gsd_index_entry::type.
Referenced by gsd_is_entry_valid(), gsd_read_chunk(), gsd_write_chunk(), and GSDUtil::readChunk().
gsd_find_matching_chunk_name()
const char * gsd_find_matching_chunk_name (struct gsd_handle * handle, const char * match, const char * prev)
Search for chunk names in a gsd file.
Parameters
handle Handle to an open GSD file.
match String to match.
prev Search starting point.
Precondition
handle was opened by gsd_open()
prev was returned by a previous call to gsd_find_matching_chunk_name()
To find the first matching chunk name, pass NULL for prev. Pass in the previous found string to find the next after that, and so on. Chunk names match if they begin with the string in match*. Chunk names returned by this function may be present in at least one frame.
Returns
Pointer to a string, NULL if no more matching chunks are found found, or NULL if prev* is invalid
Definition at line 2228 of file gsd.c.
    {
    if (handle == NULL)
        {
        return NULL;
        }
    if (match == NULL)
        {
        return NULL;
        }
    if (handle->file_names.n_names == 0)
        {
        return NULL;
        }
    // return nothing found if the name buffer is corrupt
    if (handle->file_names.data.data[handle->file_names.data.reserved - 1] != 0)
        {
        return NULL;
        }
    // determine search start index
    const char* search_str;
    if (prev == NULL)
        {
        search_str = handle->file_names.data.data;
        }
    else
        {
        // return not found if prev is not in range
        if (prev < handle->file_names.data.data)
            {
            return NULL;
            }
        if (prev >= (handle->file_names.data.data + handle->file_names.data.reserved))
            {
            return NULL;
            }
        if (handle->header.gsd_version < gsd_make_version(2, 0))
            {
            search_str = prev + GSD_NAME_SIZE;
            }
        else
            {
            search_str = prev + strlen(prev) + 1;
            }
        }
    size_t match_len = strlen(match);
    while (search_str < (handle->file_names.data.data + handle->file_names.data.reserved))
        {
        if (search_str[0] != 0 && 0 == strncmp(match, search_str, match_len))
            {
            return search_str;
            }
        if (handle->header.gsd_version < gsd_make_version(2, 0))
            {
            search_str += GSD_NAME_SIZE;
            }
        else
            {
            search_str += strlen(search_str) + 1;
            }
        }
    // searched past the end of the list, return NULL
    return NULL;
    }
References gsd_byte_buffer::data, gsd_name_buffer::data, gsd_handle::file_names, gsd_make_version(), GSD_NAME_SIZE, gsd_header::gsd_version, gsd_handle::header, gsd_name_buffer::n_names, and gsd_byte_buffer::reserved.
Referenced by gsd_upgrade().
gsd_upgrade()
int gsd_upgrade (struct gsd_handle * handle)
Upgrade a GSD file to the latest specification.
Parameters
handle Handle to an open GSD file
Precondition
handle was opened by gsd_open() with a writable mode.
There are no pending data to write to the file in gsd_end_frame()
Returns
GSD_SUCCESS (0) on success. Negative value on failure:
GSD_ERROR_IO: IO error (check errno).
GSD_ERROR_INVALID_ARGUMENT: handle is NULL
GSD_ERROR_FILE_MUST_BE_WRITABLE: The file was opened in read-only mode.
Definition at line 2300 of file gsd.c.
    {
    if (handle == NULL)
        {
        return GSD_ERROR_INVALID_ARGUMENT;
        }
    if (handle->open_flags == GSD_OPEN_READONLY)
        {
        return GSD_ERROR_INVALID_ARGUMENT;
        }
    if (handle->frame_index.size > 0 || handle->frame_names.n_names > 0)
        {
        return GSD_ERROR_INVALID_ARGUMENT;
        }
    if (handle->header.gsd_version < gsd_make_version(2, 0))
        {
        if (handle->file_index.size > 0)
            {
            // make a copy of the file index
            struct gsd_index_buffer buf;
            gsd_util_zero_memory(&buf, sizeof(struct gsd_index_buffer));
            int retval = gsd_index_buffer_allocate(&buf, handle->file_index.size);
            if (retval != GSD_SUCCESS)
                {
                return retval;
                }
            memcpy(buf.data,
                   handle->file_index.data,
                   sizeof(struct gsd_index_entry) * handle->file_index.size);
            buf.size = handle->file_index.size;
            // sort the copy and write it back out to the file
            retval = gsd_index_buffer_sort(&buf);
            if (retval != GSD_SUCCESS)
                {
                gsd_index_buffer_free(&buf);
                return retval;
                }
            ssize_t bytes_written = gsd_io_pwrite_retry(handle->fd,
                                                        buf.data,
                                                        sizeof(struct gsd_index_entry) * buf.size,
                                                        handle->header.index_location);
            if (bytes_written == -1 || bytes_written != sizeof(struct gsd_index_entry) * buf.size)
                {
                gsd_index_buffer_free(&buf);
                return GSD_ERROR_IO;
                }
            retval = gsd_index_buffer_free(&buf);
            if (retval != GSD_SUCCESS)
                {
                return retval;
                }
            // sync the updated index
            retval = fsync(handle->fd);
            if (retval != 0)
                {
                return GSD_ERROR_IO;
                }
            }
        if (handle->file_names.n_names > 0)
            {
            // compact the name list without changing its size or position on the disk
            struct gsd_byte_buffer new_name_buf;
            gsd_util_zero_memory(&new_name_buf, sizeof(struct gsd_byte_buffer));
            int retval = gsd_byte_buffer_allocate(&new_name_buf, handle->file_names.data.reserved);
            if (retval != GSD_SUCCESS)
                {
                return retval;
                }
            const char* name = gsd_find_matching_chunk_name(handle, "", NULL);
            while (name != NULL)
                {
                retval = gsd_byte_buffer_append(&new_name_buf, name, strlen(name) + 1);
                if (retval != GSD_SUCCESS)
                    {
                    gsd_byte_buffer_free(&new_name_buf);
                    return retval;
                    }
                name = gsd_find_matching_chunk_name(handle, "", name);
                }
            if (new_name_buf.reserved != handle->file_names.data.reserved)
                {
                gsd_byte_buffer_free(&new_name_buf);
                return GSD_ERROR_FILE_CORRUPT;
                }
            // write the new names out to disk
            ssize_t bytes_written = gsd_io_pwrite_retry(handle->fd,
                                                        new_name_buf.data,
                                                        new_name_buf.reserved,
                                                        handle->header.namelist_location);
            if (bytes_written == -1 || bytes_written != new_name_buf.reserved)
                {
                gsd_byte_buffer_free(&new_name_buf);
                return GSD_ERROR_IO;
                }
            // swap in the re-organized name buffer
            retval = gsd_byte_buffer_free(&handle->file_names.data);
            if (retval != GSD_SUCCESS)
                {
                gsd_byte_buffer_free(&new_name_buf);
                return retval;
                }
            handle->file_names.data = new_name_buf;
            // sync the updated name list
            retval = fsync(handle->fd);
            if (retval != 0)
                {
                gsd_byte_buffer_free(&new_name_buf);
                return GSD_ERROR_IO;
                }
            }
        // label the file as a v2.0 file
        handle->header.gsd_version = gsd_make_version(GSD_CURRENT_FILE_VERSION, 0);
        // write the new header out
        ssize_t bytes_written
            = gsd_io_pwrite_retry(handle->fd, &(handle->header), sizeof(struct gsd_header), 0);
        if (bytes_written != sizeof(struct gsd_header))
            {
            return GSD_ERROR_IO;
            }
        // sync the updated header
        int retval = fsync(handle->fd);
        if (retval != 0)
            {
            return GSD_ERROR_IO;
            }
        // remap the file index
        retval = gsd_index_buffer_free(&handle->file_index);
        if (retval != 0)
            {
            return retval;
            }
        retval = gsd_index_buffer_map(&handle->file_index, handle);
        if (retval != 0)
            {
            return retval;
            }
        }
    return GSD_SUCCESS;
    }
References gsd_index_buffer::data, gsd_byte_buffer::data, gsd_name_buffer::data, gsd_handle::fd, gsd_handle::file_index, gsd_handle::file_names, gsd_handle::frame_index, gsd_handle::frame_names, gsd_byte_buffer_allocate(), gsd_byte_buffer_append(), gsd_byte_buffer_free(), GSD_CURRENT_FILE_VERSION, GSD_ERROR_FILE_CORRUPT, GSD_ERROR_INVALID_ARGUMENT, GSD_ERROR_IO, gsd_find_matching_chunk_name(), gsd_index_buffer_allocate(), gsd_index_buffer_free(), gsd_index_buffer_map(), gsd_index_buffer_sort(), gsd_io_pwrite_retry(), gsd_make_version(), GSD_OPEN_READONLY, GSD_SUCCESS, gsd_util_zero_memory(), gsd_header::gsd_version, gsd_handle::header, gsd_header::index_location, gsd_name_buffer::n_names, gsd_header::namelist_location, gsd_handle::open_flags, gsd_byte_buffer::reserved, and gsd_index_buffer::size.