name: Code Linting
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch actions (v2)
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Super-Linter
        uses: github/super-linter@v4.8.1
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
