name: Language Linting
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
    
      - name: Fetch actions (v2)
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: alex
        uses: theashraf/alex-action@master