name: Test
on: [push, pull_request]

jobs:
  run:
    name: Code Coverage
    runs-on: ubuntu-latest
    
    env:
      CLICOLOR_FORCE: '0'

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        path: code
        submodules: true
  
    - name: Configure
      run: |
        cmake ${{ github.workspace }} -G Ninja -B build \
                      -DCMAKE_BUILD_TYPE=Debug \
                      -DENABLE_TESTING=True \
                      -DENABLE_COVERAGE=True \
                      -DCMAKE_TOOLCHAIN_FILE=$${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
    
    - name: Build
      run: ninja -j $(($(getconf _NPROCESSORS_ONLN) + 2))
      working-directory: build

    - name: Run tests
      run: "ninja coverage"
      working-directory: build

    - name: Upload results to CodeCov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        verbose: true # optional (default = false)