name: Test
on: [push, pull_request]

jobs:
  run:
    name: Code Coverage
    runs-on: ubuntu-latest
    
    env:
      CLICOLOR_FORCE: '0'

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        path: code
        submodules: true
  
    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake .. -GNinja \
                      -DCMAKE_BUILD_TYPE=Debug \
                      -DENABLE_TESTING=True \
                      -DENABLE_COVERAGE=True \
    
    - name: Build
      run: ninja -j $(($(getconf _NPROCESSORS_ONLN) + 2))
      working-directory: build

    - name: Run tests
      run: "ninja coverage"
      working-directory: build
