name: Test
on: [push, pull_request]

jobs:
  run:
    name: Code Coverage
    runs-on: ubuntu-20.04
    continue-on-error: true
    
    env:
      CLICOLOR_FORCE: '0'
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'


    steps:
      
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          path: code
          submodules: true
    
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: List $RUNNER_WORKSPACE before build
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        id: runvcpkg 
        with:
          # This is the default location of the directory containing vcpkg sources.
          # Change it to the right location if needed.
          vcpkgDirectory: '${{ github.workspace }}/code/vcpkg'

          # If not using a submodule for vcpkg sources, this specifies which commit
          # id must be checkout from a Git repo. It must not set if using a submodule
          # for vcpkg.
          vcpkgGitCommitId: '4474aba1e77be2d643eb684298b7d5479cad9a1f'

      - name: Prints output of run-vcpkg's action.
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}

      - name: Configure
        run: |
          cmake ${{ github.workspace }}/code -G Ninja -B build \
                        -DCMAKE_BUILD_TYPE=Debug \
                        -DENABLE_TESTING=True \
                        -DENABLE_COVERAGE=True \
                        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/code/vcpkg/scripts/buildsystems/vcpkg.cmake
      
      - name: Build
        run: ninja -j $(($(getconf _NPROCESSORS_ONLN) + 2))
        working-directory: code/build

      - name: Run tests
        run: "ninja coverage"
        working-directory: code/build

      - name: Upload results to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          verbose: true # optional (default = false)